### ISSUE TITLE
with AQT?

### ISSUE THREAD

**Issue by wicatfly** [Xruptor/BagSync#100]
2x BagSync\wireframe\scanner.lua:294: attempt to perform arithmetic on field '?' (a nil value)
BagSync\wireframe\scanner.lua:294: in function `SaveAuctionHouse'
BagSync\wireframe\events.lua:160: in function <BagSync\wireframe\events.lua:160>
[C]: ?
...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...AQT\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
AQT\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <AQT\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Xruptor** [comment]
I'm assuming this is on Classic right?

**Comment by wicatfly** [comment]
Yes！
2020年2月23日 +0800 20:53 Xruptor <notifications@github.com>，写道：

**Comment by Xruptor** [comment]
I think I found the issue.  I will repair it right now.

**Comment by wicatfly** [comment]
Thank you！
2020年2月23日 +0800 21:33 Xruptor <notifications@github.com>，写道：

**Comment by Xruptor** [comment]
> Thank you！ 2020年2月23日 +0800 21:33 Xruptor <notifications@github.com>，写道：
> […](#)
> Closed #100 via [85cc7ef](https://github.com/Xruptor/BagSync/commit/85cc7ef7cac735849401e48dfce78f9146fa6681). — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

You're very welcome!
