### ISSUE TITLE
With enough alts the tooltip extends past the game window.

### ISSUE THREAD

**Issue by DiscordGregory** [Xruptor/BagSync#102]
![Capture](https://user-images.githubusercontent.com/59945495/83800778-06e14600-a676-11ea-97d5-f2faf7d17730.PNG)

**Comment by Xruptor** [comment]
WOW I never thought someone would have THAT many alts.  How do you suggest I fix it?  Can you give me some ideas?  If I just limit the amount that is shown there may be alts you want shown that would be cut off after a set limit.

So any suggestions would be great!

**Comment by Xruptor** [comment]
It's been 5 days and I haven't heard a suggestion from you. I don't see a way to fix this without limiting the amount of characters that get shown in the tooltip.  Which again as I have mentioned above, may cut off a character you are really interested in seeing in the tooltip.

Therefore I'm closing this ticket.
