### ISSUE TITLE
I don't know why bagsync is scanning the auction house? its pausing other addons from working.

### ISSUE THREAD

**Issue by strickland** [Xruptor/BagSync#107]
I got two addons that scan the AH, Collectme ->> this for collectionshop tab on AH, which shows me cheap mounits/pets/toys that I don't have.

anyway when I open the tab to scan the AH, here bagsync starts scanning then it keeps going forever, also pausing the collectme addon from scanning, here's a screenshot.

I wonder why BagSync scans the AH in the first place? I don't know.

https://imgur.com/a/2Kp4yeX

**Comment by Xruptor** [comment]
To let you know how many items you have on the auction house of course.  Also just go into the bagsync settings, you can turn off auction house scanning.

**Comment by strickland** [comment]
Back to this, I couldn't find the option to turn of AH scanning, can you tell me exactly where mate?

Can't find it in Main or Display or Color?

**Comment by Xruptor** [comment]
Sure not a problem, i'll be glad to help.  When you open the BagSync options go to the Display options.  Find an option labeled, "Display auction house items."  Make sure that is not checked (not enabled). That option is the one that turns on the auction house scanning abilities.

**Comment by strickland** [comment]
Thanks brother, I appreciate it, I thought this only for displays and doesnt actually scan or anything.

**Comment by Xruptor** [comment]
> Thanks brother, I appreciate it, I thought this only for displays and doesnt actually scan or anything.

Cool, glad you were able to find it.  Hmm.. you do have a point.  Maybe I'll add a warning text next to the setting to let folks know that turning "Display auction house items." disabled the AH scanning feature.  That way folks will know that if they want to turn it off, all they need to do is disable that feature.

**Comment by strickland** [comment]
ye sure, that would be nice info tbh.

but what does scanning AH exactly do for me? I still dont know, maybe to add the items list in bagsync? 

btw I got a reques,t dunno if i can post here or new thread, but can bagsync check for the same pet battle name if its caged or not caged and consider them as one? I duno if that make any sense but u can imagine, have two pets the same, one caged one prior to learning it, see what i mean.
