### ISSUE TITLE
Caged Battle Pet issues

### ISSUE THREAD

**Issue by Deavan** [Xruptor/BagSync#11]
The first issue is that caged battle pets ("Pet Cages") are only being recorded in guild banks and not personal banks or equipped bags.

The second issue is that caged battle pets are searchable as "Pet Cage" and not what pet is in them. So you can can see how many caged pets there are but not search on the particular caged pet you are looking for.

**Comment by Xruptor** [comment]
I'm not hearing about this issue anymore nor are any of my friends experiencing this issue.  I believe it has been solved.  If not, then please file another issue ticket.
