### ISSUE TITLE
Libraries need an update for WoW 9.0/Shadowlands

### ISSUE THREAD

**Issue by Nevcairiel** [Xruptor/BagSync#110]
Good to see that BagSync is going to be ready for 9.0 still!

But one thing thats missing is updating the various libraries bundled with BagSync. At least Ace3 and LibQTip need fixes for 9.0 to function properly. Would be great if you could roll those updates in. :)

**Comment by Xruptor** [comment]
Hey Nevcairiel its great to hear from you! Doh! I knew I had forgotten something ;)  I don't have an active subscription at the moment so I rely currently on others to update BagSync so I can do a merge.  Hmm I'll have to see where I can grab the latest versions that are stable for those libraries. :)

**Comment by Nevcairiel** [comment]
Ace3 is where it always was:
https://www.wowace.com/projects/ace3/files

LibQTip doesn't have a "release" version yet, but this one works:
https://www.wowace.com/projects/libqtip-1-0/files/3043725

**Comment by Xruptor** [comment]
Ah thanks for pointing me in the right direction.  I'll put those together in a moment.

**Comment by Nevcairiel** [comment]
Unfortunately something seems to conflict when using the pre-packaged library with the packager, it somehow mangles the library, so I've created a (tested) PR with a clean version to hopefully resolve it.
