### ISSUE TITLE
[bug] some items don't have anything in the tooltip, other have incorrect quantities

### ISSUE THREAD

**Issue by Altoholic** [Xruptor/BagSync#115]
https://imgur.com/a/6NDoMSm

For the item mouseovered (solid stone), it don't say i have it. For others items the tooltip have wildly incorrect quantities.
I put the display option too on the screenshot, just in case.

**Comment by Altoholic** [comment]
Update: for the items who have something in the tooltip, it's wildly inaccurate.

**Comment by Altoholic** [comment]
Update: my gut feeling is quantities are fetched from the past. They don't actualise.

**Comment by Altoholic** [comment]
Update: another lua error

10x BagSync\wireframe\events.lua:81: attempt to call field 'GuildRoster' (a nil value)
BagSync\wireframe\events.lua:81: in function <BagSync\wireframe\events.lua:77>
[C]: ?
...ceBagSync\libs\AceAddon-3.0\AceAddon-3.0-13.lua:70: in function <...ceBagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...ceBagSync\libs\AceAddon-3.0\AceAddon-3.0-13.lua:527: in function `EnableAddon'
...ceBagSync\libs\AceAddon-3.0\AceAddon-3.0-13.lua:540: in function `EnableAddon'
...ceBagSync\libs\AceAddon-3.0\AceAddon-3.0-13.lua:630: in function <...ceBagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by Xruptor** [comment]
I'll take a look into this.  It should be displaying the correct amount.

**Comment by Xruptor** [comment]
I just released version 14.2.

Please try that and see if you have an issue.  If you still have an issue try doing a DB reset as your db may have been corrupted.
Type the following in your chat window.

/bgs resetdb

**Comment by Altoholic** [comment]
Seem to be good again.
TY!

(it was Classic, btw. Sorry, i tend to forget there's something else than Classic ^^)
