### ISSUE TITLE
Wireframe issue

### ISSUE THREAD

**Issue by Jackyl1122** [Xruptor/BagSync#119]
Message: Interface\AddOns\BagSync\wireframe\events.lua:81: attempt to call field 'GuildRoster' (a nil value)
Time: Wed Oct 14 15:27:05 2020
Count: 1
Stack: Interface\AddOns\BagSync\wireframe\events.lua:81: attempt to call field 'GuildRoster' (a nil value)
Interface\AddOns\BagSync\wireframe\events.lua:81: in function <Interface\AddOns\BagSync\wireframe\events.lua:77>
[C]: ?
...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function EnableAddon' ...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:540: in function EnableAddon'
...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:630: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals:

Recently downloaded the addon for the first time. I know literally nothing about coding or scripting. What should I do about this?
I posted this issue in another thread and later deleted it after realizing that the thread had nothing to do with my own issue.
I'm not an ElvUI user. If needed, I can make a list of all of the addons I use.
Thank you!

**Comment by Xruptor** [comment]
Thanks :) I'll take a look at it.

**Comment by Xruptor** [comment]
For future research on this ticket, this bug is also referenced here (https://github.com/Xruptor/BagSync/issues/115)

**Comment by Jackyl1122** [comment]
Thank you kindly!

**Comment by Xruptor** [comment]
> Thank you kindly!

No problem, is this on Classic or Retail?

**Comment by Jackyl1122** [comment]
I only play Classic.

**Comment by Jackyl1122** [comment]
I'm really excited to have this looked into. I've been looking for an addon that would essentially let me look into the bags of my alts like other addons do, except I wanted to keep the default bags. BagSync is the closest thing I've found.

**Comment by Xruptor** [comment]
Interesting, I need you to test something for me as I do not have Classic Installed.

Please type the following in your chat and let me know if it fires a bug.  It has to be exactly as shown below.  So copy and paste :)

/script C_GuildInfo.GuildRoster()

**Comment by Jackyl1122** [comment]
Message: [string "C_GuildInfo.GuildRoster()"]:1: attempt to call field 'GuildRoster' (a nil value)
Time: Thu Oct 15 10:47:14 2020
Count: 1
Stack: [string "C_GuildInfo.GuildRoster()"]:1: attempt to call field 'GuildRoster' (a nil value)
[string "C_GuildInfo.GuildRoster()"]:1: in main chunk
[C]: in function `RunScript'
Interface\FrameXML\ChatFrame.lua:2033: in function `?'
Interface\FrameXML\ChatFrame.lua:4695: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4356: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4392: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: (*temporary) = nil
(*temporary) = "attempt to call field 'GuildRoster' (a nil value)"

**Comment by Jackyl1122** [comment]
I also received the original error as well if that matters much at the moment.

**Comment by Xruptor** [comment]
This is extremely interesting.  It appears that on Retail that function works but on Classic they killed it.  Can you try the following instead?  I suspect they never migrated over their changes to C_GuildInfo over to Classic.

/script GuildRoster()

**Comment by Jackyl1122** [comment]
No alerts when I ran that command.

**Comment by Xruptor** [comment]
wowzers... okay then that's it.  Are you part of a guild by any chance?  If so, is the data for guild totals showing up on your tooltips?

**Comment by Jackyl1122** [comment]
Which tooltips? Like for a guild bank or something?

**Comment by Jackyl1122** [comment]
Guild banks aren't a feature in Classic unfortunately.

**Comment by Xruptor** [comment]
> Which tooltips? Like for a guild bank or something?

LOL you are right.  Gosh i'm so out of it these days.  I had completely forgotten about that.  So basically none of the BagSync guild features should be working in Classic.  

Regardless are you in a guild?

**Comment by Jackyl1122** [comment]
I am in a guild, that is correct.

**Comment by Xruptor** [comment]
Alright thanks I know how to fix this then.  What I'll do is just not push a Guild Roster request update and have it just pull normally when a player logins.  Since you are on Classic this won't matter to you as guild stuff is not currently enabled.  But on retail it should still work perfectly fine.  Thanks again for your incredible help debugging this issue. 👍

**Comment by Jackyl1122** [comment]
I'm just grinding to HWL, I got nothing but time. xD Thank you sir!

**Comment by Jackyl1122** [comment]
Printed yes.

**Comment by Jackyl1122** [comment]
Suggestion for future functionality:
Ability to assign bags certain items like retail does.
Organizing my bags manually is a pain sometimes with flash powder, blinding powder, poisons, grenades, and all these damned trinkets. XD

**Comment by Xruptor** [comment]
> Printed yes.

Buwhaha Perfect!  I'll just do that to check for GuildRoster :)  It will be fixed in the next major release push okay.

In terms of your feature request, that really is something a Bag Addon should do.  BagSync just really scans and keeps a record of items, currency, etc.. etc..

You could use a Bag Sorter addon, there are plenty of them online.  You can set specific sorting options for items to go into certain bags :)

**Comment by Xruptor** [comment]
Major releases are ones that I push to WowInterface and Curse.com.  There are times I just patch stuff locally to GitHub but don't really push yet as a major release.  Basically I like to squash a lot of bugs before I push anything out live.

**Comment by Jackyl1122** [comment]
Gotcha! Will the Twitch app trigger an update?

**Comment by Xruptor** [comment]
It will once I push it live.  BTW there are alternatives to the TwitchApp  https://wowup.io/
In case you wanted to try something differently.  It pulls from multiple sites 👍
