### ISSUE TITLE
Killed World Boss and got Error

### ISSUE THREAD

**Issue by vandiel01** [Xruptor/BagSync#120]
Not exactly sure what happened, killed world boss and tried bonus roll or the likes and got this error:

`1x BagSync\wireframe\tooltip.lua:24: bad argument #1 to 'match' (string expected, got nil)
[string "=[C]"]: in function `match'
[string "@BagSync\wireframe\tooltip.lua"]:24: in function <BagSync\wireframe\tooltip.lua:23>
[string "@BagSync\wireframe\tooltip.lua"]:500: in function `CurrencyTooltip'
[string "@BagSync\wireframe\tooltip.lua"]:592: in function <BagSync\wireframe\tooltip.lua:586>
[string "=[C]"]: in function `SetCurrencyByID'
[string "*:OnEnter"]:2: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = nil
(*temporary) = "^([^%d]*%d)(%d*)(.-)$"
(*temporary) = "string expected, got nil"`

**Comment by Xruptor** [comment]
Wow that shouldn't have happened.  Let me see what's going on.

**Comment by Xruptor** [comment]
Okay I see what it is.  It was an error triggered by all the Currency issues with BagSync since 9.0.
