### ISSUE TITLE
Bagsync and Elvui issue

### ISSUE THREAD

**Issue by greatestfall** [Xruptor/BagSync#121]
With both bagsync and elvui enabled I get a X close button in the middle of my screen, unable to be clicked through and you have to click the X about 10 times to get it to go away, it's there every time you reload the UI.  

https://i.imgur.com/vL2ozRV.jpg  

When I disable elvui, it goes away, when i disable bagsync it goes away.  when both are on though it pops that X up there and it's quite annoying.

**Comment by greatestfall** [comment]
I see that this issue was actually resolved a few hours ago, I apologize.

**Comment by BaronPlucky** [comment]
I updated to the bagsync release from a few hours ago and this non-clickthrough window is still happening for me.

**Comment by greatestfall** [comment]
https://git.tukui.org/elvui/elvui/-/issues/2066 @BaronPlucky this is the fix.

**Comment by Xruptor** [comment]
> I see that this issue was actually resolved a few hours ago, I apologize.

That is correct.  It should be fixed on ElvUI next version push.  Please see the following issue ticket.
https://github.com/Xruptor/BagSync/issues/116
