### ISSUE TITLE
Empty windows when using with ElvUI

### ISSUE THREAD

**Issue by Zon-github** [Xruptor/BagSync#122]
Took me a bit to figure it out, but I get empty windows in the middle of my screen I can't click through when using bagsync with ElvUI. Theres a small X that I can use to close them, but they reappear everytime. They empty window goes away when I disable bagsync.

https://imgur.com/a/Hic8Txx

**Comment by Xruptor** [comment]
This has been fixed.  It was an ElvUI error.  They addressed it.

Please see the following issue tickets.
https://github.com/Xruptor/BagSync/issues/113
https://github.com/Xruptor/BagSync/issues/121
https://github.com/Xruptor/BagSync/issues/116

Official ElvUI fix found here
https://git.tukui.org/elvui/elvui/-/commit/7d3091988a65986cac1abe1ae73e4f945b4841e7

https://git.tukui.org/elvui/elvui/-/issues/2066

**Comment by Xruptor** [comment]
Actually I'm going to keep a few of these tickets opened so folks could see them rather then putting new ones in 😄

**Comment by Aurylia** [comment]
> 
> 
> Actually I'm going to keep a few of these tickets opened so folks could see them rather then putting new ones in 😄

Thank you, found the fix cos of this because it's not in the release version of ElvUI yet and I was going crazy without this addon.

**Comment by Xruptor** [comment]
Downloading the latest version of ElvUI now has the fix.  Closing the ticket.
