### ISSUE TITLE
Error with latest update

### ISSUE THREAD

**Issue by Kittywulfe** [Xruptor/BagSync#124]
Thank you so much for the update! However since installing it, I am still getting the following error message:

2x BagSync\wireframe\tooltip.lua:24: bad argument #1 to 'match' (string expected, got nil)
[string "=[C]"]: in function `match'
[string "@BagSync\wireframe\tooltip.lua"]:24: in function <BagSync\wireframe\tooltip.lua:23>
[string "@BagSync\wireframe\tooltip.lua"]:500: in function `CurrencyTooltip'
[string "@BagSync\wireframe\tooltip.lua"]:583: in function <BagSync\wireframe\tooltip.lua:577>
[string "=[C]"]: in function `SetCurrencyTokenByID'
[string "*:OnEnter"]:2: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = nil
(*temporary) = "^([^%d]*%d)(%d*)(.-)$"
(*temporary) = "string expected, got nil"

Thank you again and I hope this helps to make the addon even better.

**Comment by Xruptor** [comment]
This was already taken care of and will be fixed in next major push release.

Please see the following:
https://github.com/Xruptor/BagSync/issues/120
