### ISSUE TITLE
Not working in crafting windows

### ISSUE THREAD

**Issue by PirateKain** [Xruptor/BagSync#126]
The main place I need this addon to show what characters have what reagents, is the crafting windows. But it don't show me that.
  I use Bagnon and it comes with an addon similar to BagSync called Bagbrother. Bagbrother does do this but I like how BagSync does a few things better. Except this part that is either missing or broken.
Could you fix or add it so I can see what character has the Reagents needed to craft things within the crafting windows.

   Thank you

**Comment by Xruptor** [comment]
I will look into this.
