### ISSUE TITLE
It does not update my reagents

### ISSUE THREAD

**Issue by sodade21** [Xruptor/BagSync#128]
When im crafting something with reagents i have at my bank the tooltip is not refreshed/synced. it says the wrong amount of reagents. it syncs only when i go and open my bank again. is there any way to fix this? thanks.
Ps: I use ARKinventory for bags/bank/gbank

**Comment by Xruptor** [comment]
This is working as intended.  Unfortunately, Blizzard only allows addon authors to update Reagent data when a player visits a bank.  Once you open the bank window, we can scan the Reagents as it's considered a special bank space.  Outside of that we aren't able to update it and can't make predictions as to what item was removed from it when crafting.  Bank, Auction, Void Bank, Reagents are all locations that must be visited in order for any data to be updated.  This is the same for pretty much any addon that relies on scanning.  It's just a built in limitation in the Blizzard code, sorry to say. 😢 

Player bags though are updated in real time as that can be scanned at any point in time.  Sorry if this isn't the news you were hoping for.

**Comment by sodade21** [comment]
> 
> 
> This is working as intended. Unfortunately, Blizzard only allows addon authors to update Reagent data when a player visits a bank. Once you open the bank window, we can scan the Reagents as it's considered a special bank space. Outside of that we aren't able to update it and can't make predictions as to what item was removed from it when crafting. Bank, Auction, Void Bank, Reagents are all locations that must be visited in order for any data to be updated. This is the same for pretty much any addon that relies on scanning. It's just a built in limitation in the Blizzard code, sorry to say. 😢
> 
> Player bags though are updated in real time as that can be scanned at any point in time. Sorry if this isn't the news you were hoping for.
Alright! Thank you for the time to clarifying all these and for your time to make the addon! I still like it! and as you say no other addon can do more. Ill keep using it! thanks again 👍  :-)

**Comment by Xruptor** [comment]
> > Alright! Thank you for the time to clarifying all these and for your time to make the addon! I still like it! and as you say no other addon can do more. Ill keep using it! thanks again 👍  :-)

No problem anytime! If you come across any other issues, please don't hesitate to file an issue ticket.  I try to get to them as quickly as I can.

Oh on a side note, another user had an issue similar to yours but in addition he mentioned Mailbox scanning.  You can see my response here.
https://github.com/Xruptor/BagSync/issues/130

**Comment by Xruptor** [comment]
v14.9
-Finalized code that will calculate and predict the amount of items that were used while crafting from the Bank and ReagentBank and store it to the database.

-Prediction algorithm should be fairly accurate when consuming items from the Bank and ReagentBank when crafting.  However, it's not 100% foolproof.  It will definitely be 100% accurate once the player visits the bank though.  This is due to limitation imposed by Blizzard on the WOW client.

-Some code cleanup.
