### ISSUE TITLE
Error with SetBackdrop on LibQTip with legacy "BadPet"addon

### ISSUE THREAD

**Issue by Kream** [Xruptor/BagSync#129]
Bagsync may still be attempting to call SetBackdrop. This only happens when the legacy addon "BadPet" is enabled AND you mouse over a battle pet. Just thought you should know. 

207x ...faceBagSync\libs\LibQTip-1.0\LibQTip-1.0-47.lua:540: attempt to call method 'SetBackdrop' (a nil value)
[string "@BagSync\libs\LibQTip-1.0\LibQTip-1.0-47.lua"]:540: in function <...faceBagSync\libs\LibQTip-1.0\LibQTip-1.0.lua:534>
[string "@BagSync\libs\LibQTip-1.0\LibQTip-1.0-47.lua"]:127: in function `Acquire'
[string "@BagSync\wireframe\tooltip.lua"]:328: in function `TallyUnits'
[string "@BagSync\wireframe\tooltip.lua"]:663: in function <BagSync\wireframe\tooltip.lua:658>
[string "=[C]"]: in function `FloatingBattlePet_Show'
[string "@FrameXML\FloatingPetBattleTooltip.lua"]:57: in function `FloatingBattlePet_Toggle'
[string "@FrameXML\ItemRef.lua"]:197: in function <FrameXML\ItemRef.lua:11>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Blizzard_CombatLog\Blizzard_CombatLog.lua"]:3520: in function `SetItemRef'
[string "@FrameXML\ChatFrame.lua"]:3906: in function <FrameXML\ChatFrame.lua:3905>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "*:OnHyperlinkClick"]:1: in function <[string "*:OnHyperlinkClick"]:1>
[string "=[C]"]: ?

Locals:
tooltip = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
key = "FloatingBattlePetTooltip"
backdrop = <table> {
 backdropColor = <table> {
 }
 edgeSize = 16
 tileEdge = true
 backdropBorderColor = <table> {
 }
 tileSize = 16
 edgeFile = "Interface/Tooltips/UI-Tooltip-Border"
 tile = true
 bgFile = "Interface/Tooltips/UI-Tooltip-Background"
 insets = <table> {
 }
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
(*temporary) = <table> {
 backdropColor = <table> {
 }
 edgeSize = 16
 tileEdge = true
 backdropBorderColor = <table> {
 }
 tileSize = 16
 edgeFile = "Interface/Tooltips/UI-Tooltip-Border"
 tile = true
 bgFile = "Interface/Tooltips/UI-Tooltip-Background"
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
GameTooltip = GameTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 RightEdge = <unnamed> {
 }
 SetVoidWithdrawalItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 SetLootItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 numMoneyFrames = 1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 SetMerchantItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 TopRightCorner = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 updateTooltip = 0.184000
 SetInventoryItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 SetAuctionSellItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 SetBagItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 SetAuctionItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 SetCurrencyByID = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 SetCurrencyToken = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 SetVoidItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 TextRight1 = GameTooltipTextRight1 {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 SetUnitDebuff = <function> defined =[C]:-1
 comparing = false
 __tooltipUpdated = false
 SetQuestItem = <function> defined =[C]:-1
 hasMoney = 1
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 SetBackpackToken = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 BottomLeftCorner = <unnamed> {
 }
 SetInboxItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wr

**Comment by Xruptor** [comment]
That's a bit odd as I recall the LibQTip having the updates to prevent the backdrop bug.  In fact I'm looking at it now and it does have the Backdrop Mixin in all it's frames.  I wonder if the other addon BadPet is creating it's own tooltip that doesn't have the Backdrop Mixin and it's being parsed by LibQTip library which causes the error.

**Comment by Xruptor** [comment]
It appears that the LibQTip is being sent old tooltips that don't have the new Backdrop Mixin.  So therefore, it's missing the necessary functions for it to properly display.  This is what fires off the error.  I'm pretty sure it's the legacy addon BadPet that is doing this.  Regardless, I've filed a ticket with the creator of LibQTip. 

Please see the following issue.
https://www.wowace.com/projects/libqtip-1-0/issues/48
