### ISSUE TITLE
TBC-Classic Version

### ISSUE THREAD

**Issue by Rerox-WoW** [Xruptor/BagSync#134]
Could we please get a TBC-Classic-Version of BagSync please? Not sure if it needs more work than just changing the TOC, but it would be cool to have it up to date.

**Comment by Xruptor** [comment]
I don't have an active account anymore or access to TBC.  I wasn't accept for the developer beta for some reason.  Anyways, I don't see why it shouldn't work in TBC.  It probably just needs a TOC upgrade.  Hopefully someone can test it out and let me know.  Classic has some restrictions that can probably be lifted in TBC for BagSync.

**Comment by stiffsen** [comment]
I just manually installed the latest classic version of BagSync rather than through wowup. It seems to be working fine in TBC classic. I have never tried BagSync before TBC classic, 'though, so I cannot say with 100% certainty that everything works.

**Comment by Xruptor** [comment]
> I just manually installed the latest classic version of BagSync rather than through wowup. It seems to be working fine in TBC classic. I have never tried BagSync before TBC classic, 'though, so I cannot say with 100% certainty that everything works.

That's what I figured.  Not much was changed from classic to TBC.  It should still work properly.  The only major changes happened in WOTLK.  When I get a moment I'll still review it just to make sure.  I just have no means of testing it myself.

**Comment by Alkaersig** [comment]
Everything seems to be working perfectly fine in TBC pre-patch. No errors from the addon and everything shows up as it should, just like before the patch.

Would be lovely with a little TBC update, so CurseForge picks it up as a TBC addon and our addon managers stops crying about not having a compatible version available :)

**Comment by MilaPi** [comment]
Can I just add that the addon does not show up in WoWUP in "TBC Classic" addons? It only shows in "Classic Classic(?)". It does show though in Curseforge/overwolf and can be installed from there/manually.

**Comment by Xruptor** [comment]
> Can I just add that the addon does not show up in WoWUP in "TBC Classic" addons? It only shows in "Classic Classic(?)". It does show though in Curseforge/overwolf and can be installed from there/manually. BTW, thank you for developing and maintaining it <3

I don't really use WOWUp and I just make sure the addon is properly listed on CurseForge and WoWInterface.  I double checked and the addon is before correctly listed as Retail, Classic and TBC on both websites.  Also you are more then welcome! :smile: I'm glad you are enjoying the addon.

The only thing I can suggest is to file a ticket for WOWUp on their support.
https://github.com/WowUp/WowUp/issues/new/choose

Let them know that the addon doesn't show up on the TBC section of their software but it's correctly listed on both WOWInterface and Curseforge.
