### ISSUE TITLE
Bug when hovering over battle pets in the AH

### ISSUE THREAD

**Issue by DiscordGregory** [Xruptor/BagSync#141]
Nothing special needs to be done, just go to the AH, select the BattlePets category then click search and mouseover the results

29x BagSync\wireframe\tooltip.lua:316: attempt to call method 'GetOwner' (a nil value)
[string "@BagSync\wireframe\tooltip.lua"]:316: in function `TallyUnits'
[string "@BagSync\wireframe\tooltip.lua"]:691: in function <BagSync\wireframe\tooltip.lua:686>
[string "=[C]"]: ?
[string "=[C]"]: in function `BattlePetToolTip_Show'
[string "@FrameXML\BattlePetTooltip.lua"]:19: in function `BattlePetToolTip_ShowLink'
[string "@Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua"]:540: in function <...lizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:527>
[string "=[C]"]: in function `SetAuctionHouseTooltip'
[string "@Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua"]:578: in function `lineOnEnterCallback'
[string "@Blizzard_AuctionHouseUI\Blizzard_AuctionHouseItemList.lua"]:176: in function `OnEnterListLine'
[string "@Blizzard_AuctionHouseUI\Blizzard_AuctionHouseItemList.lua"]:21: in function `OnLineEnter'
[string "@SharedXML\TableBuilder.lua"]:42: in function <SharedXML\TableBuilder.lua:41>

Locals:
self = <table> {
 ItemCount = <function> defined @BagSync\wireframe\tooltip.lua:291
 HexColor = <function> defined @BagSync\wireframe\tooltip.lua:34
 Enable = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 EnableModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 defaultModuleLibraries = <table> {
 }
 UnitTotals = <function> defined @BagSync\wireframe\tooltip.lua:248
 SetDefaultModulePrototype = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 name = "BagSync_Tooltip"
 IsEnabled = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 ColorizeUnit = <function> defined @BagSync\wireframe\tooltip.lua:54
 TallyUnits = <function> defined @BagSync\wireframe\tooltip.lua:309
 GetSortIndex = <function> defined @BagSync\wireframe\tooltip.lua:41
 SetDefaultModuleState = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:387
 HookTooltip = <function> defined @BagSync\wireframe\tooltip.lua:553
 SetEnabledState = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 __lastTally = <table> {
 }
 baseName = "BagSync"
 OnEnable = <function> defined @BagSync\wireframe\tooltip.lua:724
 HookBattlePetTooltip = <function> defined @BagSync\wireframe\tooltip.lua:681
 SetDefaultModuleLibraries = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 CurrencyTooltip = <function> defined @BagSync\wireframe\tooltip.lua:511
 IterateModules = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 IsModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:217
 MoneyTooltip = <function> defined @BagSync\wireframe\tooltip.lua:175
 GetName = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 moduleName = "Tooltip"
 defaultModuleState = true
 Disable = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
}
objTooltip = BattlePetTooltip {
 0 = <userdata>
 linePool = <table> {
 }
 BorderBottomLeft = <unnamed> {
 }
 Owned = <unnamed> {
 }
 AddLine = <function> defined @FrameXML\FloatingPetBattleTooltip.lua:124
 Speed = <unnamed> {
 }
 textLineAnchor = <unnamed> {
 }
 SpeedTexture = <unnamed> {
 }
 Background = <unnamed> {
 }
 HealthTexture = <unnamed> {
 }
 speciesID = 2916
 __tooltipUpdated = false
 BorderTop = <unnamed> {
 }
 PetType = <unnamed> {
 }
 BorderTopLeft = <unnamed> {
 }
 BorderTopRight = <unnamed> {
 }
 BorderLeft = <unnamed> {
 }
 Power = <unnamed> {
 }
 PowerTexture = <unnamed> {
 }
 PetTypeTexture = <unnamed> {
 }
 BattlePet = <unnamed> {
 }
 Name = <unnamed> {
 }
 Health = <unnamed> {
 }
 Level = <unnamed> {
 }
 BorderBottom = <unnamed> {
 }
 BorderBottomRight = <unnamed> {
 }
 BorderRight = <unnamed> {
 }
}
link = "10308829066;1;2;2916"
source = "BattlePetToolTip_Show"
isBattlePet = true
(*temporary) = nil
(*temporary) = BattlePetTooltip {
 0 = <userdata>
 linePool = <table> {
 }
 BorderBottomLeft = <unnamed> {
 }
 Owned = <unnamed> {
 }
 AddLine = <function> defined @FrameXML\FloatingPetBattleTooltip.lua:124
 Speed = <unnamed> {
 }
 textLineAnchor = <unnamed> {
 }
 SpeedTexture = <unnamed> {
 }
 Ba

**Comment by Xruptor** [comment]
I can't seem to replicate this error at all.  It works absolutely fine for me.  I added a check for that null function regardless.

**Comment by Xruptor** [comment]
![image](https://user-images.githubusercontent.com/202515/133927556-0871895a-d21c-4a35-b0ea-ac0ff4d1a695.png)

See works fine... no error.
