### ISSUE TITLE
Guild Bank support for TBC

### ISSUE THREAD

**Issue by Alkaersig** [Xruptor/BagSync#142]
Hello,

I absolutely love this addon, it makes it so easy to figure out where you stored your shit and how much you got. However the guild support does not seem to be in the TBC version (at least it's not showing and it's not possible to toggle it on/off either). 

I saw in some other issue that you are currently very busy, but if you get time at some point, i would love if support were fixed/added for TBC version, since a lot of people will make personal banking guild and store lot of their shit there, but that is probably not a surprise :)

**Comment by Xruptor** [comment]
I would love to update this, but at the moment I don't have an active subscription.  So I cannot access Classic or TBC.  If this was retail I could probably make a free toon to debug.   The only thing I can possibly think of is that I make changes and someone tests then.

**Comment by Alkaersig** [comment]
Ohh that obviously makes it harder @Xruptor. If there's anything i can help test i'll gladly do it. Unfortunately i have never gotten into LUA myself.

**Comment by arrrrlikeapirate** [comment]
If you had game time gifted would you be able to work on it?

**Comment by Xruptor** [comment]
> If you had game time gifted would you be able to work on it?

I'd probably be able to work on it if I had a subscription.  My money is tight right now and I can only only focus on one game or platform at a time.

**Comment by arrrrlikeapirate** [comment]
I dm'ed you on Curse

**Comment by Xruptor** [comment]
> I dm'ed you on Curse

I'll check it now.  I don't go there often I'm afraid. :)

**Comment by b-morgan** [comment]
I am the author of Skillet (for Retail) and Skillet-Classic (for Classic Era and Burning Crusade Classic). The guild bank code is essentially identical in both versions.

I'd be happy to test and help debug.

**Comment by Xruptor** [comment]
I will be resubbing probably tomorrow and will see about fixing these issues.  A few of them have cropped up and I'd like to address them.

**Comment by Alkaersig** [comment]
Hi @Xruptor 

Thank you for looking into this! I am getting the error below now when opening my Guildbank in TBC Classic. Some items have been scanned and shows the correct count, other items does not show a count at all, which is guess is due to the error.

Date: 2021-09-20 08:35:18
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\BagSync\wireframe\scanner.lua line 159:
   'for' limit must be a number
Debug:
   [string "=[C]"]: ?
   [string "@BagSync\wireframe\scanner.lua"]:159: SaveGuildBank()
   [string "@BagSync\wireframe\events.lua"]:254: GUILDBANKBAGSLOTS_CHANGED()
   [string "@BagSync\wireframe\events.lua"]:169: func()
   [string "@Ace3\AceTimer-3.0\AceTimer-3.0.lua"]:57:
      Ace3\AceTimer-3.0\AceTimer-3.0.lua:50
Locals:
