### ISSUE TITLE
Guildbank scanning error

### ISSUE THREAD

**Issue by martinboy1974** [Xruptor/BagSync#145]
First, thx for bringing this great addon to bcc.

When I scan the guildbank, I get this error:

1x BagSync\wireframe\scanner.lua:159: 'for' limit must be a number
[string "@BagSync\wireframe\scanner.lua"]:159: in function `SaveGuildBank'
[string "@BagSync\wireframe\events.lua"]:254: in function `GUILDBANKBAGSLOTS_CHANGED'
[string "@BagSync\wireframe\events.lua"]:169: in function `func'
[string "@Ace3\AceTimer-3.0\AceTimer-3.0-17.lua"]:57: in function <Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 SaveBag = <function> defined @BagSync\wireframe\scanner.lua:49
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 SaveReagents = <function> defined @BagSync\wireframe\scanner.lua:102
 defaultModuleLibraries = <table> {
 }
 SaveBank = <function> defined @BagSync\wireframe\scanner.lua:86
 CleanupProfessions = <function> defined @BagSync\wireframe\scanner.lua:505
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 StartupScans = <function> defined @BagSync\wireframe\scanner.lua:32
 name = "BagSync_Scanner"
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 isScanningGuild = true
 IsModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:217
 baseName = "BagSync"
 SetDefaultModuleState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:387
 SaveCraftedReagents = <function> defined @BagSync\wireframe\scanner.lua:553
 SaveGuildBank = <function> defined @BagSync\wireframe\scanner.lua:147
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 SaveProfessions = <function> defined @BagSync\wireframe\scanner.lua:364
 enabledState = true
 SaveVoidBank = <function> defined @BagSync\wireframe\scanner.lua:110
 GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 GetModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 SaveAuctionHouse = <function> defined @BagSync\wireframe\scanner.lua:243
 ParseCraftedInfo = <function> defined @BagSync\wireframe\scanner.lua:529
 GetXRGuild = <function> defined @BagSync\wireframe\scanner.lua:128
 IterateModules = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:437
 SaveMailbox = <function> defined @BagSync\wireframe\scanner.lua:194
 SaveEquipment = <function> defined @BagSync\wireframe\scanner.lua:70
 SaveCurrency = <function> defined @BagSync\wireframe\scanner.lua:326
 moduleName = "Scanner"
 defaultModuleState = true
 Disable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
}
numTabs = 4
slotItems = <table> {
}
(for index) = 1
(for limit) = 4
(for step) = 1
tab = 1
name = "Må tages Pots"
icon = 134800
isViewable = true
canDeposit = true
numWithdrawals = 10
remainingWithdrawals = 0
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
Unit = <table> {
 GetUnitInfo = <function> defined @BagSync\wireframe\unit.lua:79
 Enable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 defaultModuleLibrar

**Comment by Xruptor** [comment]
Is this in TBC or Retail?

**Comment by martinboy1974** [comment]
In TBC

Venlig hilsen

Martin Møller

**Comment by Xruptor** [comment]
I don't exactly have a character in a guild that has access to a guild bank.  So you are going to have to debug for me

[BagSync-debug.zip](https://github.com/Xruptor/BagSync/files/7203076/BagSync-debug.zip)

Try this one when next you are online in WOW and let me know if you still get the error.
.

**Comment by arrrrlikeapirate** [comment]
I was getting the same error so I downloaded and installed the debug version attached above. Works perfectly!

**Comment by Xruptor** [comment]
> I was getting the same error so I downloaded and installed the debug version attached above. Works perfectly!
> 
> Do you have a donation link or something that I can contribute to? I really do appreciate your help and follow through on this.

https://www.paypal.com/donate?hosted_button_id=NS5FMSRHQ8P4U
You really don't have to though.  :) I do this on the side.
