### ISSUE TITLE
[Question] Guild Bank Scanning

### ISSUE THREAD

**Issue by Imiona** [Xruptor/BagSync#146]
Hello

I wanted to ask if there is an option to throttel the constant Guild Bank scanning.

I open the bank, take something out, its scanning.
10 Seconds later i put something in, its scanning again. 
30 seconds later i open the bank again, because i forgot something, its scanning AGAIN^^

It feels really unnecessary having it scanning so often.

thx

**Comment by Xruptor** [comment]
There isn't a throttle per say as BagSync scans the entire Guild Bank each time its opened.  This is to maintain an accurate count of all items in the Guild Bank.  It has to scan each tab of the Guild Bank and the Blizzard servers only allows so many queries to do this.  That is why it's done in batches.

You can however remove the alert box temporarily until I add a setting to disable it.

open the events.lua file in the BagSync folder in notepad or a text editor.  (Don't use Microsoft Word)
find the following line and delete it.

`showEventAlert(numTab, "GUILDBANK")`

Now save events.lua and you won't have the alert popup anymore when you enter the guild bank.  This is a temporary fix until I can design something better,
