### ISSUE TITLE
Found an error, enter the following command

### ISSUE THREAD

**Issue by nanjuekaien1** [Xruptor/BagSync#147]
Found an error, enter the following command: 
/bgs gold (or /bgs money)
/bgs currency
/bgs profiles
/bgs config
/bgs professions
/bgs blacklist

All are into the search window

**Comment by Xruptor** [comment]
This commands are meant to be typed in the chat window.  They are chat slash commands that open up certain module frames for BagSync.  I've never thought of testing it in the BagSync search window to see if it causes an error.
