### ISSUE TITLE
Lua Error when using BagSync external tooltip

### ISSUE THREAD

**Issue by DiscordGregory** [Xruptor/BagSync#152]
Enabling "Display item count data in an external tooltip" results in this error. No error when this setting isn't enabled.

10x ...faceBagSync\libs\LibQTip-1.0\LibQTip-1.0-48.lua:527: attempt to call method 'GetBackdrop' (a nil value)
[string "@BagSync\libs\LibQTip-1.0\LibQTip-1.0-48.lua"]:527: in function <...faceBagSync\libs\LibQTip-1.0\LibQTip-1.0.lua:521>
[string "@BagSync\libs\LibQTip-1.0\LibQTip-1.0-48.lua"]:132: in function `Acquire'
[string "@BagSync\wireframe\tooltip.lua"]:354: in function `TallyUnits'
[string "@BagSync\wireframe\tooltip.lua"]:578: in function <BagSync\wireframe\tooltip.lua:569>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML\ContainerFrame.lua"]:1372: in function `ContainerFrameItemButton_OnUpdate'
[string "@FrameXML\ContainerFrame.lua"]:1419: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
tooltip = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
key = "GameTooltip"
(*temporary) = <function> defined @SharedXML\Backdrop.lua:321
(*temporary) = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 SetCurrencyByID = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetRecipeReagentItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 TextLeft1 = GameTooltipTextLeft1 {
 }
 ItemTooltip = <unnamed> {
 }
 SetQuestLogItem = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 hasMoney = 1
 TextRight1 = GameTooltipTextRight1 {
 }
 textRight1Font = "GameTooltipHeaderText"
 SetMerchantCostItem = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 SetCurrencyToken = <function> defined =[C]:-1
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 textLeft1Font = "GameTooltipHeaderText"
 TopOverlay = <unnamed> {
 }
 shownMoneyFrames = 1
 shoppingTooltips = <table> {
 }
 needsReset = true
 updateTooltipTimer = 0.200000
 textRight2Font = "GameTooltipText"
 SetQuestItem = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
}
(*temporary) = "attempt to call method 'GetBackdrop' (a nil value)"
GameTooltip = GameTooltip {
 0 = <userdata>
 SetCurrencyByID = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetRecipeReagentItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 TextLeft1 = GameTooltipTextLeft1 {
 }
 ItemTooltip = <unnamed> {
 }
 SetQuestLogItem = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 hasMoney = 1
 TextRight1 = GameTooltipTextRight1 {
 }
 textRight1Font = "GameTooltipHeaderText"
 SetMerchantCostItem = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 SetCurrencyToken = <function> defined =[C]:-1
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 textLeft1Font = "GameTooltipHeaderText"
 TopOverlay = <unnamed> {
 }
 shownMoneyFrames = 1
 shoppingTooltips = <table> {
 }
 needsReset = true
 updateTooltipTimer = 0.200000
 textRight2Font = "GameTooltipText"
 SetQuestItem = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
}
AcquireTable = <function> defined @BagSync\libs\LibQTip-1.0\LibQTip-1.0.lua:507
labelProvider = <table> {
 cells = <table> {
 }
 cellMetatable = <table> {
 }
 cellPrototype = <table> {
 }
 heap = <table> {
 }
}
CELL_MARGIN_H = 6
CELL_MARGIN_V = 3
ResetTooltipSize = <function> defined @BagSync\libs\LibQTip-1.0\LibQTip-1.0.lua:847

**Comment by mbattersby** [comment]
This is a bug in LibQTip-1.0. See:

https://www.curseforge.com/wow/addons/libqtip-1-0/issues/49

**Comment by Xruptor** [comment]
> This is a bug in LibQTip-1.0. See:
> 
> https://www.curseforge.com/wow/addons/libqtip-1-0/issues/49

Nice thank you for posting this bug and LQtip bug report!  Helps me tracks down these issues and fix them.
