### ISSUE TITLE
Feature Request: Add item browsing

### ISSUE THREAD

**Issue by Jakobud** [Xruptor/BagSync#155]
This is a great addon. Been using it for a while.

It would be really nice if you could use the interface not only to search for items, but also just to browse the available items each character has. You already have a database of the items available on each character. Just list out the items in the interface so you can just scroll down and browse what is there. Technically the search field at the top of the interface becomes more like an item filter.

Also you could add some dropdowns at the top of the interface where you could choose which character you want to view. So if you only want to browse or search for items on a specific character you could pick them from the dropdown and then either browse their items directly or search/filter the items.

**Comment by Xruptor** [comment]
Hey there!

Thanks for posting the enhancement suggestion.  This particular enhancement is already somewhat programmed into BagSync.  If you go to the Advanced Search function of BagSync, you can select which characters and what locations you would like to view the items for.  This advanced searched also lets you locate an item on a specific character and location as well.  Let me know if this is what you were looking for?

**Comment by Jakobud** [comment]
Not exactly what I was looking for. It still only allows you to search for an item. There is no way to simply browse all items. Here is an example:

"I wonder what herbs I have on my bank alt?"

BagSync's current interface does not help you answer this because you have to know what items are on that character. You can't use BagSync to look for all the herbs unless you manually search for every single type of herb. If you could simply browse a list of all the items on your Bankalt, then you could easily see all the herbs (and all of every other type of item that bank alt has).

The advanced search window is helpful yes but I would imagine you could combine that into the primary search interface pretty easily. Here is a quick mockup of what I am envisioning:

![image](https://user-images.githubusercontent.com/87356/140964237-056a8219-baee-4b30-83dc-99f3a489c929.png)

1. Get rid of the Advanced Search window and just combine the interfaces into one. Add in a dropdown at the top where you can select which characters to search. No need for the advanced search window anymore with this UI.
2. You can now see ALL the items on all characters (or whatever characters you have selected in the dropdown) without having to search for them.
3. The Search input field is now better described as a "Filter" input. It simply filters the browsed item results. You could type in "ring" only items that contain the word "ring" in it will show up in the list. If you clear the Filter field, it will revert back to showing all items.

BagSync already contains the database of all items and where they are. This would simply be changing the interface to display the information differently.

**Comment by Xruptor** [comment]
This is great feedback!  Thank you for providing the picture.  Hmm what I just don't understand is that you can already search for items on specific characters using the Advanced search.  Just select your character from the list.  Then select the location and type the items name above.  When you press search it will restrict it to that character and location.  You can even select multiple characters and locations.  Its pretty much the same thing you have there on your drop down menu.  The only difference is that its on a separate window.  Maybe, I'm just not understanding what you are looking for still.   That or I'm not getting the exact functionality you are seeking?  The only thing I can think of is that you want to streamline the advanced window to a dropdown.  That is why I am a bit puzzled as the functionality is already there.  Don't forget you can also use the @bank, @bag, @auction, etc.. commands to see items on your current character in the search window too.

**Comment by Jakobud** [comment]
Okay so an example:

I want to know all the herbs on my bank alt. How do I do that? I have no idea what kind of herbs are on my bank alt. I just want to see all of them.

**Comment by Xruptor** [comment]
Sorry for the delay.  I've been extremely busy as of late and with the holiday things are ramping up.  I should have some time this weekend to review this again :)

**Comment by Xruptor** [comment]
I'm finally back from a hiatus and I can sit down and review all the bugs and feature requests.  With this particular one I spoke with two of my programming buddies for some input.  Although we all agreed it would definitely be more streamlined, one of my friends pointed out something that did not occur to me.  Since the characters will be displayed in the dropdown, if a person has a ludicrous amount of characters spanning multiple servers, it will be difficult to display ALL of them under the dropdown.  Technically it is possible to put them under Realm names then another character listing.  But that would add yet another layer of dropdowns to go through.  In the end we felt that just having a window where you can scroll through all available characters was much quicker and would be flexible enough to allow any number of characters without having to be restricted to screen space from dropdowns.

I do plan on redesigning BagSync possible for the next expansion.  One of the things I will be looking at is the UI design and especially the advanced search.  Thank you very much for your feedback though and suggestion.  It has given me ideas in what to do for the future. :)

**Comment by Jakobud** [comment]
Sounds good. You mentioned that you can use the @bank, @bag, @auction search options. I didn't even know those existed. I don't see anything in the documentation or instructions about those. I think just making the UI more clear would be ideal.

**Comment by Xruptor** [comment]
> Sounds good. You mentioned that you can use the @bank, @bag, @auction search options. I didn't even know those existed. I don't see anything in the documentation or instructions about those. I think just making the UI more clear would be ideal.

Actually you make a good point.  I think I will make it more apparent and add a help or tip section to the interface to demonstrate search options.

**Comment by Jakobud** [comment]
My recommendation is not to have "Search" and "Advanced Search". Just have a single "Search" and have all the advanced options in there.
