### ISSUE TITLE
Bug report: color code in data string

### ISSUE THREAD

**Issue by dale206Git** [Xruptor/BagSync#156]
Hi, I am seeing a color code and other characters before the expected values (in the screenshot, the values are "1" and "15")

![Untitled-1](https://user-images.githubusercontent.com/84369924/144171384-1a767188-f6dd-4a84-a3b3-4853fb1d50d8.png)

I think this happened after changing the primary and secondary tooltip colors.

I just installed this addon.

**Comment by Xruptor** [comment]
I will take a look at this when I get a chance.  I've been out of WOW for quite some time now.  Moved on to other games but I will take a moment to review the code and see if I can fix it.

**Comment by Xruptor** [comment]
I've been in on a hiatus for awhile.  I'm trying to get back and fix a couple of these bugs.  Is this still an issue?

**Comment by dale206Git** [comment]
I'm not sure, I reinstalled the addon leaving the default colors untouched as a workaround. I think it should be easy to replicate though, happened as soon as I set some custom colors...

**Comment by Xruptor** [comment]
Interesting, its possible that the ACE libraries that BagSync relies on (and so do many other addons) may have been updated and the issue is with the ColorPicker from it that it uses.  I'll need to see if I can replicate the issue.

**Comment by Xruptor** [comment]
I was able to reproduce the issue.  It had to do with comma separated values.  I have fixed it :)

**Comment by Xruptor** [comment]
I will upload it once I get a few more bugs fixed.  I even added an option to reset the colors to the default ones as well in the config screen.

**Comment by dale206Git** [comment]
Great, thanks!
