### ISSUE TITLE
Feature request: total count for all items found in Search results

### ISSUE THREAD

**Issue by dale206Git** [Xruptor/BagSync#157]
Thank you for this addon. I would like to see a global total for the total counts of every item found in the Search window, ideally split by category (gems, tradeskill...)

**Comment by dale206Git** [comment]
![Untitled-2](https://user-images.githubusercontent.com/84369924/144174479-636a316a-f0d2-4cd3-b96b-dbf8ce4acce7.png)

**Comment by dale206Git** [comment]
I just found out about all search syntax options, so no need to split by category but would still find the global total very useful.

**Comment by Xruptor** [comment]
I'm slowly getting back to fixing and updating my addons since my hiatus.  I'll see about adding this.
