### ISSUE TITLE
Feature request: using the results in a macro or script

### ISSUE THREAD

**Issue by dale206Git** [Xruptor/BagSync#158]
Is there a way to use the search results as input data in a macro or Lua script? Are APIs available?

**Comment by Xruptor** [comment]
There currently isn't a way to output the search results.  I'm afraid there is no API other then calling the functions yourself or outputting the data from the tables/arrays generated.  You can view all the information for BagSync though from the WTF folder.

C:\your wow installation\_retail\WTF\Account Name\SavedVariables\BagSync.lua
