### ISSUE TITLE
Bug report: Enter the game and report an error after updating to 16.2

### ISSUE THREAD

**Issue by zhouksheng11** [Xruptor/BagSync#160]
58x ...BagSync\libs\LibItemSearch-1.2\LibItemSearch-1.2-15.lua:230: attempt to call field 'GetAzeriteCurrencyID' (a nil value)
[string "@BagSync\libs\LibItemSearch-1.2\LibItemSearch-1.2-15.lua"]:230: in main chunk

Locals:
Search = <table> {
 OR = "或者"
 NOT_MATCH = "否"
 NOT = "否"
 Find = <function> defined @ElvUI\Libraries\Core\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:133
 Match = <function> defined @ElvUI\Libraries\Core\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:56
 MatchAny = <function> defined @ElvUI\Libraries\Core\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:48
 ACCENTS = <table> {
 }
 MatchAll = <function> defined @ElvUI\Libraries\Core\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:38
 UseFilter = <function> defined @ElvUI\Libraries\Core\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:123
 Compare = <function> defined @ElvUI\Libraries\Core\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:153
 Matches = <function> defined @ElvUI\Libraries\Core\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:29
 Filter = <function> defined @ElvUI\Libraries\Core\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:101
 Clean = <function> defined @ElvUI\Libraries\Core\LibItemSearch-1.2\CustomSearch-1.0\CustomSearch-1.0.lua:142
}
Unfit = <table> {
 IsItemUnusable = <function> defined @ElvUI\Libraries\Core\LibItemSearch-1.2\Unfit-1.0\Unfit-1.0.lua:113
 IsClassUnusable = <function> defined @ElvUI\Libraries\Core\LibItemSearch-1.2\Unfit-1.0\Unfit-1.0.lua:120
 unusable = <table> {
 }
 cannotDual = true
}
Lib = <table> {
 Scanner = LibItemSearchTooltipScanner {
 }
 Matches = <function> defined @BagSync\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:19
 TooltipLine = <function> defined @BagSync\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:41
 TooltipPhrase = <function> defined @BagSync\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:27
 InSet = <function> defined @BagSync\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:31
 Tooltip = <function> defined @BagSync\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:23
 BelongsToSet = <function> defined @BagSync\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:78
 Filters = <table> {
 }
}
(*temporary) = <table> {
 artifact = <table> {
 }
 type = <table> {
 }
 sets = <table> {
 }
 items = <table> {
 }
 name = <table> {
 }
 requiredlevel = <table> {
 }
 level = <table> {
 }
 usable = <table> {
 }
 quality = <table> {
 }
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to call field 'GetAzeriteCurrencyID' (a nil value)"

**Comment by Xruptor** [comment]
Hmm and here I thought updating the Library would fix it. I will add a check for that error manually then.  Thanks for putting in the ticket to let me know!

**Comment by zhouksheng11** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhouksheng11** [comment]
First of all thanks for your reply, currently I put this code

Lib.Filters.azerite = {
  keyword = C_CurrencyInfo.GetBasicCurrencyInfo(C_CurrencyInfo.GetAzeriteCurrencyID()).name:lower(),

  canSearch = function(self, operator, search)
    return not operator and self.keyword:find(search)
  end,

  match = function(self, link)
    return C_AzeriteItem.IsAzeriteItemByID(link) or C_AzeriteEmpoweredItem.IsAzeriteEmpoweredItemByID(link)
  end
}

Temporarily eliminated this error after removing

**Comment by Xruptor** [comment]
Removing the code is not a good way to fix it.  Best is to check for Azerite coding and then if it's available then process the code.  This will make it compatible with the Live version as well.  

```
if C_AzeriteItem and C_CurrencyInfo.GetAzeriteCurrencyID then
	Lib.Filters.azerite = {
		keyword = C_CurrencyInfo.GetBasicCurrencyInfo(C_CurrencyInfo.GetAzeriteCurrencyID()).name:lower(),

		canSearch = function(self, operator, search)
			return not operator and self.keyword:find(search)
		end,

		match = function(self, link)
			return C_AzeriteItem.IsAzeriteItemByID(link) or C_AzeriteEmpoweredItem.IsAzeriteEmpoweredItemByID(link)
		end
	}
end
```

I'll make a manual edit to the Library. I'll let the Library Author know there is an issue in the library with TBC.
https://github.com/Jaliborc/LibItemSearch-1.2/issues
