### ISSUE TITLE
Deleted character data not being removed and remains in tooltip.

### ISSUE THREAD

**Issue by realrobd** [Xruptor/BagSync#162]
When running /bgs fixdb, deleted character data still remains.
Maybe there is another method or command to remove it?

**Comment by Xruptor** [comment]
Use the BagSync Profiles window to remove the old/deleted character.

**Comment by Xruptor** [comment]
It should be `/bgs profiles`  as a command.

**Comment by realrobd** [comment]
> Use the BagSync Profiles window to remove the old/deleted character.

Thank you very much :)

**Comment by Xruptor** [comment]
Sure thing :) anytime!
