### ISSUE TITLE
Currency window is empty

### ISSUE THREAD

**Issue by drewkeller** [Xruptor/BagSync#163]
First of all, thanks for this addon!

The currency window opens, and it has a title "BagSync - Currency" but otherwise, it's just a black, empty window. All of the other BagSync windows are working fine. If I mouse over a currency in a vendor, the currency in the tooltip is correct for multiple characters.

I turned on console errors and I'm not seeing any messages when I open the currency window.

![image](https://user-images.githubusercontent.com/954172/166106886-f109fc39-900a-4291-942a-87755732d6be.png)

**Comment by Xruptor** [comment]
So just to clarify, the currency is being shown correctly in the tooltips but doesn't show up in the BagSync Currency window correct?

**Comment by drewkeller** [comment]
Exactly

**Comment by drewkeller** [comment]
Hmm... now I got this.

Message: Interface\AddOns\BagSync\modules\currency.lua:123: attempt to concatenate field 'header' (a nil value)
Time: Sat Apr 30 08:30:11 2022
Count: 1
Stack: Interface\AddOns\BagSync\modules\currency.lua:123: attempt to concatenate field 'header' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\BagSync\modules\currency.lua"]:123: in function `DisplayList'
[string "@Interface\AddOns\BagSync\modules\currency.lua"]:47: in function <Interface\AddOns\BagSync\modules\currency.lua:46>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\BagSync\modules\minimap.lua"]:68: in function `func'
[string "@Interface\SharedXML\UIDropDownMenu.lua"]:914: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:

**Comment by Xruptor** [comment]
Thanks, I'll see what I can do.  I don't exactly have an active subscription and it's at times difficult to debug GUI elements without launching it within game.  Can you please provide me your WTF data for BagSync.  You can zip it up here and attach it to your post.

`C:\World of Warcraft\_retail_\WTF\<Account>\SavedVariables\BagSync.lua`

**Comment by drewkeller** [comment]
[AdiBags.zip](https://github.com/Xruptor/BagSync/files/8597001/AdiBags.zip)

**Comment by Xruptor** [comment]
Wrong one I need the BagSync.lua file that has all the data in it.

**Comment by drewkeller** [comment]
doh!
[BagSync.zip](https://github.com/Xruptor/BagSync/files/8597004/BagSync.zip)

**Comment by Xruptor** [comment]
very interesting, the currency isn't pulling the header information (currency category) for your Draenei character.  Hmmmmmmmmmmmmmmm  that is very odd.  Let me take a look.

**Comment by Xruptor** [comment]
Do me a favor and go to your Draenei character having the issue and open and close your Character Currency window found under your character window.  (not the BagSync one).  Then type the following.  /reloadui or /reload ui  to reload the UI.  Check the BagSync currency window and see if it works?

**Comment by drewkeller** [comment]
Looking at a few others in the data, it looks like characters that I've played recently are also missing the header field, while characters that I haven't played in a while are OK.

**Comment by Xruptor** [comment]
They must have updated their code and as always Blizzard breaks everything.  Seriously it gets annoying after awhile.  Let me try something first with you.

**Comment by drewkeller** [comment]
After opening currency window (I moused over a few currencies and the tooltip looked correct) and then reloaded UI. Got the same error when opening the currencies window:

Message: Interface\AddOns\BagSync\modules\currency.lua:123: attempt to concatenate field 'header' (a nil value)
Time: Sat Apr 30 08:46:23 2022
Count: 1
Stack: Interface\AddOns\BagSync\modules\currency.lua:123: attempt to concatenate field 'header' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\BagSync\modules\currency.lua"]:123: in function `DisplayList'
[string "@Interface\AddOns\BagSync\modules\currency.lua"]:47: in function <Interface\AddOns\BagSync\modules\currency.lua:46>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\BagSync\modules\minimap.lua"]:68: in function `func'
[string "@Interface\SharedXML\UIDropDownMenu.lua"]:914: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:

**Comment by Xruptor** [comment]
[BagSync.zip](https://github.com/Xruptor/BagSync/files/8597034/BagSync.zip)

Try this custom version of BagSync.  Overwrite your BagSync in the Addons folder with this one.  Then do a `/reloadui` or `/reload ui` to load it again.  The currency window should at least display something generic.  Let me know if it does.

**Comment by drewkeller** [comment]
Well, that fixes it.

![image](https://user-images.githubusercontent.com/954172/166108293-26f2f512-a83a-4af5-9b6b-ef0e4875bbd5.png)

**Comment by Xruptor** [comment]
Not really since it just puts everything into a generic "Currency" label if the header isn't recorded or found.  It's a temporary fix and I'll just have to see what the heck they broke a bit later today.  I'll experiment a bit more now that I know they changed the code for the currencies (yet again).  Keep an eye out for an updated version of BagSync, it should update this ticket when I do.

**Comment by drewkeller** [comment]
OK, I see.

**Comment by Xruptor** [comment]
Using the PTR I was able to determine what was going on.  It looks like they changed the way how headers are shown.  I've updated the code and now it works fine.  All the Currency/Token categories have to be expanded in the Character frame Currency/Token window for BagSync to record.  I added additional code to ensure everything always gets expanded before it scans it.
