### ISSUE TITLE
Missing Character Data

### ISSUE THREAD

**Issue by DCCXVIII** [Xruptor/BagSync#165]
I have a character that has NOT been removed from the database yet for whatever reason is being excluded from bagsyncs display for items/currencies. When logging onto that character, bagsync displays it without issue. It is only when logging onto other characters that this information pertaining to that character is missing.  I have performed a fix database command but it did not resolve my issue.

**Comment by Xruptor** [comment]
Is the character on the same server as the others?  If not is the character on a Connected Realm with the other characters? (https://wowpedia.fandom.com/wiki/Connected_Realms)  Are they in different factions?  Need a bit more details before I can give some suggestions :)

**Comment by DCCXVIII** [comment]
Yes, its on the same faction and same server. Although being on different factions has never been an issue for this addon in the passed as far as I can tell anyway.

**Comment by Xruptor** [comment]
Yes different factions on same server isn't an issue. I was just asking generic questions so I have a general idea of your characters and their server locations.

If it's on the same server and same faction then something is going on internally as it should be displaying that information.  I will need to analyze your BagSync data to see what's going on.  I need a few things from you so I can look into this issue further :)

1) Could you give me the name of the affected character and the server name.
2) I need you to attach _(you can drag/drop files or selecting and paste them here)_ your BagSync data here so I can view it.  You may need to ZIP it up first.  You can find the data in your WOW folder under the following location.
**C:\your wow install folder\_Retail\WTF\<account name>\SavedVariables\BagSync.lua**

Then I can use that to replicate your data and see if I can figure out why your character isn't displaying correctly.

**Comment by DCCXVIII** [comment]
Upon further review, it appears the issue is limited to only certain currencies. E.g. Anima, Stygia etc. So it appears to be limited to some of the SL currencies. No idea why. The affected character is Amisra-Dalaran US. 

I do not have any files in that folder path you specified.

**Comment by Xruptor** [comment]
LOL had to update the comment above as apparently the GitHub formatting was slapping around the file path XD

**Comment by DCCXVIII** [comment]
[BagSync.zip](https://github.com/Xruptor/BagSync/files/8756154/BagSync.zip)

I think I found it.

**Comment by DCCXVIII** [comment]
Just currencies. Items in bags are unaffected. They show the characters items correctly.

**Comment by DCCXVIII** [comment]
That fixed it! Thanks!

**Comment by Xruptor** [comment]
> That fixed it! Thanks!

Sure thing :) any time!  Glad it helped.
