### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by zkpjy** [Xruptor/BagSync#168]
Can I directly read Saved and store without scanning, Fix the problem of frame role lag in the BNET。
The BNET It's just needed :(
Thank you!

**Comment by Xruptor** [comment]
Hello,

I already explained why this cannot be fixed.  It's not a bug.  There is simply TOO MUCH DATA to go through without there being a performance hit or lag caused when displaying tooltips with BNET option on.

Please see your previous ticket.

https://github.com/Xruptor/BagSync/issues/140

I posted the explanation here:
https://github.com/Xruptor/BagSync/issues/140#issuecomment-927301498

**Comment by zkpjy** [comment]
I just want to read only the saved information for display. I don't have to repeat 10+ times every time. I wonder if this is OK?
As an account information display plug-in, it is not recommended to set BNET display, which is really a bit embarrassing.
