### ISSUE TITLE
[Request] Update for WOTLK classic.

### ISSUE THREAD

**Issue by Fixetza** [Xruptor/BagSync#174]
Could we get the addon updated for WOTLK classic please?

**Comment by Xruptor** [comment]
Hmm that's odd, Is it broken? Have you tried clicking on "Load out of date addons?"  If it still works with that option enabled, then it's just a TOC file version update to match the latest patch version of WOW. Something that needs to be updated every time a patch for WOW comes out.  Needless to say a super annoyance for addon makers lol. ;)

**Comment by Xruptor** [comment]
![image](https://user-images.githubusercontent.com/202515/187906399-07884351-634c-4283-bdf3-c16426c3d6d3.png)

**Comment by Fixetza** [comment]
Oh silly me... Since i'm installing addons manually i forgot to unzip it in the addons folder. Sorry for bothering you and thank you for your time!

**Comment by Xruptor** [comment]
Not a problem and no bother at all!  Glad you were able to figure it out :)
