### ISSUE TITLE
[Request] focus search bar on show

### ISSUE THREAD

**Issue by silverhawke249** [Xruptor/BagSync#178]
title says it all.

when i hit the keybind to show the search window, the search bar isn't automatically focused, which means i have to still move my mouse and click the search bar instead of typing straight away.

this would be a great QoL improvement (at least to me) if you put this in, thanks you!

**Comment by Xruptor** [comment]
I used to have this actually.  However, some folks got upset that their keystrokes will being diverted to the window when it was opened.  Forcing them to click off to re-establish focus back to lets say their chat window or what not.  The quickest way was just to close the BagSync window.  This is why it was just removed and instead implemented as a search parameter in the chat.

Such as searching for everything that has "ore" in it.

/bagsync ore

If this is still something that completely interests you, I may be inclined to add it as an option.  However, I would have to give it some thought :)

**Comment by mcavanagh** [comment]
Just installed this addon and this was the first thing that I noticed.  Consider this an up-vote for enabling the search text field to be focused (either by default, or behind a config setting).

Being able to just hit my bagsync search keybind, then start typing feels much better than using the /bagsync blah way, although I appreciate that it exists.

**Comment by mcavanagh** [comment]
I've put together a pull request at https://github.com/Xruptor/BagSync/pull/181

Apologies if it's a bit janky.  I've never really done any .lua before, but hopefully it shows the basic idea.

**Comment by Xruptor** [comment]
Option added.  Please refer to #181

**Comment by silverhawke249** [comment]
sorry it took me so long to reply to this again, but this addition is perfect -- exactly what i wanted! thank you @Xruptor, @mcavanagh!

**Comment by Xruptor** [comment]
> sorry it took me so long to reply to this again, but this addition is perfect -- exactly what i wanted! thank you @Xruptor, @mcavanagh!

Sure thing! Glad it worked out and you enjoy it. 😄
