### ISSUE TITLE
Errors (Line 33 and 37)?

### ISSUE THREAD

**Issue by ghost** [Xruptor/BagSync#180]
Date: 2022-10-05 14:54:41
ID: 1
Error occured in: Global
Count: 1
Message: ...ce\AddOns\BagSync\libs\AceEvent-3.0\AceEvent-3.0.lua line 33:
   Attempt to register unknown event "CURSOR_UPDATE"
Debug:
   [string "=[C]"]: RegisterEvent()
   [string "@BagSync\libs\AceEvent-3.0\AceEvent-3.0.lua"]:33: OnUsed()
   [string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:142: RegisterEvent()
   [string "@tdPack2\UI\RuleView.lua"]:60:
      tdPack2\UI\RuleView.lua:58
   [string "=[C]"]: Show()
   [string "@Interface_Wrath\FrameXML\UIParent.lua"]:2711: ShowUIPanel()
   [string "@tdPack2\UI\UI.lua"]:58: Show()
   [string "@tdPack2\Core\Command.lua"]:65: func()
   [string "@tdPack2\Core\Command.lua"]:151: RunCommand()
   [string "@tdPack2\Button\Button.lua"]:25:
      tdPack2\Button\Button.lua:23
Locals:
(*temporary) = AceEvent30Frame {
 0 = <userdata>
}
(*temporary) = "CURSOR_UPDATE"

AddOns:
BagSync, v16.8
  

Date: 2022-10-05 14:55:00
ID: 2
Error occured in: Global
Count: 1
Message: ...ce\AddOns\BagSync\libs\AceEvent-3.0\AceEvent-3.0.lua line 37:
   Attempt to unregister unknown event "CURSOR_UPDATE"
Debug:
   [string "=[C]"]: UnregisterEvent()
   [string "@BagSync\libs\AceEvent-3.0\AceEvent-3.0.lua"]:37: OnUnused()
   [string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:197: UnregisterAllEvents()
   [string "@tdPack2\UI\RuleView.lua"]:65:
      tdPack2\UI\RuleView.lua:64
   [string "=[C]"]: Hide()
   [string "@Interface_Wrath\FrameXML\UIParent.lua"]:2731: HideUIPanel()
   [string "@..\SharedXML\SharedUIPanelTemplates.lua"]:313: HideParentPanel()
   [string "@..\SharedXML\SharedUIPanelTemplates.lua"]:180:
      ..\SharedXML\SharedUIPanelTemplates.lua:174
Locals:
(*temporary) = AceEvent30Frame {
 0 = <userdata>
}
(*temporary) = "CURSOR_UPDATE"

AddOns:
BagSync, v16.8

**Comment by Xruptor** [comment]
This looks like an ACE3 Plugin error.  It's being triggered in EventEvent.  So perhaps ACE3 plugin broken in a patch mmm....
