### ISSUE TITLE
Pre-patch issues, addon nonfunctional

### ISSUE THREAD

**Issue by vellocets** [Xruptor/BagSync#183]
The addon is nonfunctional in the pre-patch and throwing up a lot of LUA errors. I'm not sure which is the most important, but here are the most common:

15x Interface/AddOns/BagSync/wireframe/tooltip.lua:316: attempt to index field 'options' (a nil value)
[string "@Interface/AddOns/BagSync/wireframe/tooltip.lua"]:316: in function `TallyUnits'
[string "@Interface/AddOns/BagSync/wireframe/tooltip.lua"]:601: in function <Interface/AddOns/BagSync/wireframe/tooltip.lua:592>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1477: in function `OnUpdate'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1445: in function `OnEnter'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1441: in function <Interface/FrameXML/ContainerFrame.lua:1440>

------

7x Interface/AddOns/BagSync/wireframe/events.lua:181: attempt to index field 'db' (a nil value)
[string "@Interface/AddOns/BagSync/wireframe/events.lua"]:181: in function `?'
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

-------

5x Interface/AddOns/BagSync/wireframe/scanner.lua:59: attempt to index field 'db' (a nil value)
[string "@Interface/AddOns/BagSync/wireframe/scanner.lua"]:59: in function `SaveBag'
[string "@Interface/AddOns/BagSync/wireframe/events.lua"]:207: in function `?'
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

-------

6x Interface/AddOns/BagSync/wireframe/scanner.lua:79: attempt to index field 'db' (a nil value)
[string "@Interface/AddOns/BagSync/wireframe/scanner.lua"]:79: in function `SaveEquipment'
[string "@Interface/AddOns/BagSync/wireframe/scanner.lua"]:42: in function `StartupScans'
[string "@Interface/AddOns/BagSync/wireframe/events.lua"]:173: in function <Interface/AddOns/BagSync/wireframe/events.lua:74>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by Xruptor** [comment]
It looks like they just disabled and reworked a lot of their code to break addons.  Why am I not surprised.  They do this every patch and every expansion.  I'll take a look at it, but without an active account this will be interesting.

**Comment by vellocets** [comment]
> It looks like they just disabled and reworked a lot of their code to break addons. Why am I not surprised. They do this every patch and every expansion. I'll take a look at it, but without an active account this will be interesting.

If there's anything I can do to help beyond posting LUA errors let me know. Your addon is a lifesaver.
