### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nanjuekaien1** [Xruptor/BagSync#184]
AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "VOID_STORAGE_OPEN"
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface/AddOns/BagSync/libs/AceEvent-3.0/AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Interface/AddOns/BagSync/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:142: in function `RegisterEvent'
[string "@Interface/AddOns/BagSync/wireframe/unit.lua"]:54: in main chunk

Interface/AddOns/BagSync/wireframe/data.lua:50: attempt to call method 'GetUnitInfo' (a nil value)
Count: 1

Call Stack:
[string "=(tail call)"]: ?
[string "@Interface/AddOns/BagSync/wireframe/data.lua"]:50: in function <Interface/AddOns/BagSync/wireframe/data.lua:45>
[string "=[C]"]: ?
[string "@Interface/AddOns/BagSync/libs/AceAddon-3.0/AceAddon-3.0.lua"]:70: in function <...ce/AddOns/BagSync/libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Interface/AddOns/BagSync/libs/AceAddon-3.0/AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface/AddOns/BagSync/libs/AceAddon-3.0/AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface/AddOns/BagSync/libs/AceAddon-3.0/AceAddon-3.0.lua"]:630: in function <...ce/AddOns/BagSync/libs/AceAddon-3.0/AceAddon-3.0.lua:615>

**Comment by Xruptor** [comment]
Hmm did they get rid of Void Storage?  That seems like such a simple event.  I don't have a subscription so this is going to be interesting.
