### ISSUE TITLE
Items in Bank Slot 7 aren't counted

### ISSUE THREAD

**Issue by theUPquark** [Xruptor/BagSync#189]
I can swap items out of the bag in Bank Slot 7 and then they are counted as normal.

**Comment by Xruptor** [comment]
I'll have to check.  Please let me know what are you using.  Classic, WOTLK, or Retail.  In the past I didn't have to ask that but these days it's important.

**Comment by Xruptor** [comment]
Looks like they added another bag slot and it's not counted as part of their constants.  Why am I not surprised.  I'll see about adding it.
