### ISSUE TITLE
Profession Links

### ISSUE THREAD

**Issue by EthanCentaurai** [Xruptor/BagSync#19]
Blizzard deliberately changed profession links in Patch 5.4 to prevent players and addons from using them on different characters.

Unfortunately, this has broken BagSync's profession link feature. The links do nothing when they are clicked on in the chatframe and my advice is to remove or disable the feature for the time being.

**Comment by Xruptor** [comment]
https://twitter.com/Bashiok/status/383017871208906752

Still waiting...
