### ISSUE TITLE
scanner.lua use of tmpRecipe

### ISSUE THREAD

**Issue by b-morgan** [Xruptor/BagSync#190]
I am the author of [Skillet](https://www.curseforge.com/wow/addons/skillet) and am working on updating it for 10.0.0. I am looking at scanner.lua to get a handle on the new C_TradeSkillUI API functions. Thanks for the well written code and comments!

At line 549-552 (see below) you are testing the table tmpRecipe but I don't see where you add an entry to tmpRecipe. Is this a bug?
```
		--now store the recipe information, but make sure we don't already have the recipe stored
		if not tmpRecipe[recipeData.recipeID] then
			subCatSlot.recipes = (subCatSlot.recipes or "").."|"..recipeData.recipeID
		end
```

**Comment by Xruptor** [comment]
That looks like a bug.  I may have gotten removed during a code rewrite and I forgot to add it in.  Let me double check but that's a nice catch.

**Comment by Xruptor** [comment]
P.S: I'm flattered you use my Addon as a reference.  I've known of Skillet for a long time and it's a great addon.
