### ISSUE TITLE
Can not detect something in my bank

### ISSUE THREAD

**Issue by palalapili** [Xruptor/BagSync#191]
hi, I have hardened-magnificent-hide both in my bag and bank, but it only show the number in my bag.

https://i.imgur.com/hd5ENm3.png

thanks

**Comment by Xruptor** [comment]
Make sure you are using the latest version of BagSync.  This bug was fixed in it.  If you are still having issues with the newest version.  Please let me know here.

**Comment by palalapili** [comment]
I download the latest version on curse
https://i.imgur.com/g5h3P0W.png

**Comment by Xruptor** [comment]
Okay I'll take a look at it.  Can you please provide me your WTF Cache BagSync.lua?  You can find it in the WTF/AccountName/Server/SavedVariables folder.  It will allow me to see if the data is even being recorded. You can attach it here.  Just drag and drop or select the option below.

**Comment by palalapili** [comment]
[BagSync.txt](https://github.com/Xruptor/BagSync/files/9996845/BagSync.txt)
.lua file cannot be upload, so I change it to .txt
thank you!

**Comment by Xruptor** [comment]
> [BagSync.txt](https://github.com/Xruptor/BagSync/files/9996845/BagSync.txt) .lua file cannot be upload, so I change it to .txt thank you!

["addonversion"] = "17.1",

You're still using 17.1 the version where I fixed the bag issue was 17.2.  You need to update again to fix the issue.  I mentioned that above. 😄

**Comment by palalapili** [comment]
ok,thanks!
sorry about bothering you!

**Comment by Xruptor** [comment]
> ok,thanks! sorry about bothering you!

Oh no problem at all!  😄 It's not a bother.  I'm glad I was able to help.  I will close this ticket now.
