### ISSUE TITLE
Reagent bank bug with new profession interface 

### ISSUE THREAD

**Issue by Rolfeg** [Xruptor/BagSync#193]
When i use "Transmute: Living Steel" or craft "Jard's Peculiar Energy Source" bagsync doubles the amount of reagents as if they were in a material bank too.
1st picture - i have 90 Ghost Iron Bar in my bag and nowhere else.
![изображение](https://user-images.githubusercontent.com/86924313/202641274-a55abda7-8a79-4c75-be6e-0450c47cb200.png)
2nd picture - i craft 1 Jard's Peculiar Energy Source, mouseover to iron, and now i "have" 80 in the bag and another 80 in reagent bank,
![изображение](https://user-images.githubusercontent.com/86924313/202641076-23422ed6-bb5b-4102-ad31-88e04a4a24d6.png)
Also same story with living steel.
Can you please fix this?

**Comment by Xruptor** [comment]
Hmm it shouldn't be doing that.  I suspect it has something to do with the new tradeskill interface. I'll take a look at it.

**Comment by Xruptor** [comment]
Okay to try to replicate this.  You have the bars in your bag right and ONLY in your bags?  You use transmute living steel and it updates your bags, but not tells you that you have some in the bank right?

**Comment by Rolfeg** [comment]
Only in my bags. Here is the small video without editing - https://www.youtube.com/watch?v=GyhBEp5Nn1c
And another one (without elvui and bad quality, sorry) - https://www.youtube.com/watch?v=Lj7uKEmO0wk
Noticed that if i keep the bag open, then the bug will only happen on the second time when i mouseover trillium.

**Comment by Rolfeg** [comment]
Only in my bags. Here is the small video without editing - https://www.youtube.com/watch?v=GyhBEp5Nn1c
And another one (without elvui and bad quality, sorry) - https://www.youtube.com/watch?v=Lj7uKEmO0wk
Noticed that if i keep the bag open, then the bug will only happen on the second time when i mouseover trillium.

**Comment by Xruptor** [comment]
Thanks those videos help a lot and will give me a better idea of what is going on.  Let me see now if I can reproduce the issue.

**Comment by Xruptor** [comment]
Okay I was able to reproduce the issue.  It looks like GetItemCount() from Blizzard API returns reagent count regardless if there are items in the bank or not.  This includes adding it together with the bag count.  So it was returning the wrong item counts which BagSync was using.  This is a Blizzard issue and I'll compensate for it, but they really should not return the bag totals + bank totals (reagent) when an addon doesn't request it.

It's a simple enough loophole to get by.  Just requires a bit of math but it's fixable.  I'll implement it now and will release fix on next update push.
