### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by agentschmitt** [Xruptor/BagSync#197]
Today i got some lua errors with latest version 17.3 of Bagsync

183x Interface/AddOns/BagSync/wireframe/scanner.lua:773: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/BagSync/wireframe/scanner.lua"]:773: in function `SaveCraftedReagents'
[string "@Interface/AddOns/BagSync/wireframe/events.lua"]:248: in function `func'
[string "@Interface/AddOns/Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
self = <table> {
 IsKeyring = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:67
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 GetBagSlots = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:41
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 SaveReagents = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:166
 defaultModuleLibraries = <table> {
 }
 SaveBank = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:149
 CleanupProfessions = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:603
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 StartupScans = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:84
 name = "BagSync_Scanner"
 invertedRecipeIDs = <table> {
 }
 IsEnabled = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 IsBackpackBag = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:62
 IsBank = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:71
 reagentCount = <table> {
 }
 IsBackpack = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:58
 isCheckingMail = false
 SaveCraftedReagents = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:661
 baseName = "BagSync"
 recipeIDs = <table> {
 }
 IsBankBag = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:75
 IsModule = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:213
 GetXRGuild = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:192
 SetDefaultModuleState = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:383
 SaveProfessions = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:441
 IsReagentBag = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:80
 SetEnabledState = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 GetName = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 enabledState = true
 SaveVoidBank = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:174
 SaveGuildBank = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:211
 SaveBag = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:102
 SaveAuctionHouse = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:307
 ParseCraftedInfo = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:627
 SaveEquipment = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:133
 IterateModules = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:433
 SaveMailbox = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:258
 EnableModule = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 SaveCurrency = <function> defined @Interface/AddOns/BagSync/wireframe/scanner.lua:390
 moduleName = "Scanner"
 defaultModuleState = true
 Disable = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
}
bagtype = "reagents"
rootItems = <table> {
}
slotItems = <table> {
}
bankCount = 0
(*temporary) = nil
(*temporary) = -3
(*temporary) = 36916
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 258
(*temporary) = 36916
(*temporary) = true
(*temporary) = false
(*temporary) = false
(*temporary) = 258
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
BSYC = <table> {

**Comment by Xruptor** [comment]
Hey there!  Thanks for the ticket report.  This issue has already been addressed in a previous ticket.  #194
I have pushed the changes to the repository here but haven't pushed it live yet.  I'm working on a few other tickets before I push another major version update.  This fix will be part of them.  😄
