### ISSUE TITLE
Feature Request: Advanced Search Always Expanded With Search Window

### ISSUE THREAD

**Issue by Jdaddy0007** [Xruptor/BagSync#199]
With the recent loss of Bagnon I've been looking for a great tool like yours!  It has really served the need and now with the "stock" ElvUI bags + BagSync, I have everything I need!  Can't thank you enough!

As in the request, I find that more often than not, I am searching for a specific character's items (especially prepatch ensuring every alt has what it should).  I've keybound a macro (within Opie) which does the trick:
/run AceGUI30Button3:Click()
/bgs search
I figured I wasn't the only one who might appreciate this as an option 😄
Thanks again!

**Comment by Xruptor** [comment]
Did something happen to Bagnon?  I keep hearing stuff about it but wondered what is going on?  I'm assuming it has something to do with the fact it hasn't been updated since October?

Also I don't see that being a major issue to implement.  So to recap you just want an option that always opens it to the Advanced Search?

**Comment by Jdaddy0007** [comment]
The add-on has been defunct/not working at all for 3 plus weeks now with no evidence that it's currently being worked on. No one I know is currently using it or planning on using in the future.

You stated the request perfectly. Would save me a click every time! And if the focus on search window edit box worked with this, that would be Epic!

**Comment by Xruptor** [comment]
Added in version v17.7 which I just pushed live.

**Comment by Xruptor** [comment]
BTW thanks for the explanation on Bagnon.  I wondered what was going on.  It's a shame as that addon has been around as long as mine has.

**Comment by Jdaddy0007** [comment]
Thanks again! 👊

In fairness to Bagnon, apparently the author had IRL pop-up just as pre-patch broke everything. I never gave ElvUI bags a try since I had Bagnon. But now that I have, I wouldn't go back, just need BagSync 😉 (I needed 6 Bagnon addons for the same effect).

**Comment by Xruptor** [comment]
Oh that makes sense.  He was always such a nice guy to work with.  Hope things get better for him.
