### ISSUE TITLE
support for linkwrangler?

### ISSUE THREAD

**Issue by Bugfinder90** [Xruptor/BagSync#20]
Hi, the mentioned addon makes it possible to have multiple item tooltips opened.
i asked http://www.curse.com/addons/wow/linkwrangler_auctioneer who added support for the LibExtraTip library and was being told that your tooltip code was kinda "locked away".
is there a chance that your addons will work together someday?
thanks

**Comment by Xruptor** [comment]
Hey, the code is not locked away.  It's just programmed differently.  New libraries and modules come out all the time for addons.  It's hard to keep everything working together and insync.  Half the time modders find themselves rewriting code or adding support for other addons.  I'll see if I can add support for the future for LinkWrangler.  Right now though I don't have a subscription and don't see myself returning anytime soon.  Maybe someone will be kind enough to do the code updates here and I can merge them to the master copy.
