### ISSUE TITLE
High CPU usage when open bags with AdiBags

### ISSUE THREAD

**Issue by Defmaster** [Xruptor/BagSync#207]
Hi,

lately i noticed that whenever i open my bags, i have a 1-2s freeze.
As base bag addon i am using AdiBags.

Before opening bags:
Memory: 7.63 Mb
CPU: 2290 ms

After opening bags;
Memory: 10.04 Mb
CPU: 2448 ms

EDIT: Those numbers are with pretty empty inventory. The more items i got in inventory the higher the CPU usage (got to like 300ms for 1 bag opening on char that has ~80 Slots filled)

So just opening bags 1 time, causes Bagsync to use up 158 ms. (Using Lib version, but having Ace3 as seperat Library, which also takes some CPU whenever opening the bags)
When i disable BagSync the freeze goes away.

When disabling AdiBags and using default WoW combined bag, BagSync does not use CPU when opening bags (only when hovering over item and creating tooltip)

Can't tell if problem is AdiBags or how BagSync works together with it.

**Comment by Xruptor** [comment]
It sounds to me like AdiBags is triggering a LOT of bag update events when it opens.  It's possible that because of this BagSync is scanning the inventory a ludicrous amount of times.  I want to point out that BagSync doesn't scan anything in the bags when it's opened.  The only time BagSync scans the bags is when an item is moved around or added to the bags.  So I'm guess that AdiBags is triggering these events somehow.

**Comment by Xruptor** [comment]
As a suggestion, try another Bag addon and see if that makes a difference?

https://www.curseforge.com/wow/addons/ark-inventory
https://www.curseforge.com/wow/addons/litebag
https://www.curseforge.com/wow/addons/onebag3
https://www.curseforge.com/wow/addons/baggins
https://www.curseforge.com/wow/addons/baud-bag

etc.. etc..

If you use ElvUI it has it's own Bag addon that is similar to Bagnon.

If those work and it's just AdiBags then something else is going on that would require investigation.

**Comment by Defmaster** [comment]
Yeah, with Default Bags and ElvUI bags the problem does not appear.
So AdiBags doing something.

My guess would be, that it maybe uses hidden tooltip scanning for filtering and triggering BagSync everytime.

I like the design and layout from AdiBags, but the constant freeze when opening stuff is really daunting :-(

**Comment by Xruptor** [comment]
If it's only being triggered by AdiBags then that should be something that the AdiBags developer should look into.  It would seem sorta odd for me to change the code just for one addon my friend.  Especially if it works fine with all other bag addons.  Perhaps you should file a ticket with them?

https://github.com/AdiAddons/AdiBags/issues

I wish I could be of more help.  I normally go out of my way to help people and find a solution, but this one seems a bit out of my hands as I would be incorporating code in BagSync just to accommodate AdiBags.  I hope you understand 💚

**Comment by Cidan** [comment]
AdiBags developer here! We'll take a look at this, as the user has opened a bug with us. This is definitely not a good experience, and we'll see if we're trigging something we're not supposed to (which seems likely!).

Thanks for the redirect :)

**Comment by Cidan** [comment]
Oh, update: it's not us, it's third party developers/plugin authors that are doing this. Disregard, and thanks again :)

**Comment by Xruptor** [comment]
> Oh, update: it's not us, it's third party developers/plugin authors that are doing this. Disregard, and thanks again :)

Oh I'm glad you took the opportunity to look into this.  It's greatly appreciated!
