### ISSUE TITLE
Old items no longer there remain in tooltip

### ISSUE THREAD

**Issue by Druneakt** [Xruptor/BagSync#208]
Hello, I'm running v17.8. I just did a bunch of inventory cleanup across all my characters, and I've noticed one instance where items that were removed from my character A's bank are still listed as being there when I hover over the items in character B's inventory. I have triple-checked that there are not any of those items lingering in character A's bank. I tried running a FixDB but the issue remains. Let me know if there are any specific details, tests I can run, files I can share etc. to help track this down. Thanks!

**Comment by Xruptor** [comment]
Please provide me your BagSync.lua from the version of WOW you are playing on.  if retail it would be **_retail_/WTF/Account/<ACCOUNTNAME>/SavedVariables/BagSync.lua**

You will need to zip it up as lua files are not supported to be attached here.  Then please provide me with Characters A name and the item.  That way I can do some tests on my end to see what's going on.  It's possible that there may be a scanning issue but I need to check on my end.

**Comment by Druneakt** [comment]
I created a zip file with bagsync.lua, bagsync.lua.bak, and 2 screenshots showing what I am seeing.

Tamiller sent all of her Progenitor Essentia to Hillerit, but the bagsync tooltip still shows 9 in Tamiller's bank.

Thanks for looking into this, and for creating the addon! Been using yours for years, I love it!
[BagSync.zip](https://github.com/Xruptor/BagSync/files/10096545/BagSync.zip)

**Comment by Xruptor** [comment]
Thanks I'll take a look and see if I can replicate the issue.

**Comment by Xruptor** [comment]
Alright yes I see the item in Tamiller bank in the DB.  Have you tried going back to that character and opening the bank?  Does it still have it listed as having 9 items in the bank?  Even after logging out and going back to Hillerit?  If it STILL remains there, then there is definitely a bug.

**Comment by Druneakt** [comment]
Yes I went back and forth a lot, I wanted to make sure I hadn't missed out on seeing it before reporting it.

**Comment by Xruptor** [comment]
That is extremely odd then.  I may have to have you use a debugging version of BagSync I'll make for you to see what's going on.

**Comment by Druneakt** [comment]
OK thanks! I'll do a capture video of running it too. Will be gone most of the rest of today but will be back tomorrow.

**Comment by Xruptor** [comment]
[BagSync-Debug.zip](https://github.com/Xruptor/BagSync/files/10097118/BagSync-Debug.zip)

Load this special version of BagSync.  I bundled the tekDebug addon I use.  I need you to login with Tamiller and go to the bank.  When you get there do a reload and make sure not to click anything other then the bank teller.  Open up the tekDebug by typing /td in the chat.  Select "bagSync".  It should show you some debug information.  Each bank bag and slot and it's item information.

I want to see if it's storing the 187707 item at all.  Thanks in advance.  BTW you can scroll in the tekDebug using the mouse scrollwheel or using the page up and down on keyboard.

**Comment by Druneakt** [comment]
Here you go! I looked for an output file but didn't see one. Please let me know if there's anything else I should try.

https://youtu.be/lf8tYGBJhyk

**Comment by Xruptor** [comment]
> Here you go! I looked for an output file but didn't see one. Please let me know if there's anything else I should try.
> 
> https://youtu.be/lf8tYGBJhyk

That video helped tremendously.  I already spotted the issue and I'm working on a fix.  The itemID was not located in that list.  Which means there is orphaned bags from when Dragonflight changed all the bag numbers.  (They did that when they added that new reagent bag for characters to equip).  So I'll just do a cleanup for it on login.  I'm going to test it a bit before I give you a new version to try.

In the meantime, I suggest you remove that debugging version of BagSync and tekDebug and use the live one.  Until I give you a new one to try ;)

**Comment by Druneakt** [comment]
Ok thanks so much!! Super appreciate this!

**Comment by Xruptor** [comment]
Okay I implemented the fix but I'm now working on something else I just noticed.  Apparently Blizzard spams the crap out of the bags even during loading screens.  Need to add spam checks for that.

**Comment by PirateKain** [comment]
I came here to report the same issue. Its not just inventory and bank, it is also doing this in the Guild Bank. Also I notice the addon isn't working at all. It is no longer keeping track of anything in any of my characters inventories or banks. I've downloaded each update as they came out in the past month or so, hoping it would start working but still nothing. Some characters show things they do not have and all the rest like most of them show nothing. I'm not using any bag addon so don't know what's up. Thanks

**Comment by Xruptor** [comment]
> I came here to report the same issue. Its not just inventory and bank, it is also doing this in the Guild Bank.
> 
> Also, I notice the addon isn't working with profession Recipes, patterns, schematics and what not within their bags, banks and guild banks. Some characters show Recipes they do not have and all the rest like most of them show no Recipes at all. I'm on retail and not using any bag addon so don't know what's up.
> 
> Oh just remembered this. The addon also doesn't show if a character has an item equipped in the Profession journal.
> 
> Thanks

Okay this is a completely different and unrelated issue in regards to this ticket.  This ticket is about an old item still be represented in the tooltip even after the user scanned the bank with said character.  Your issue is completely different as you are claiming that no items are being tracked anywhere on your characters.  This is extremely unusual as it's working fine for me and various other friends that use it.  So something must be going on your end that needs to be looked into.  Please create a separate ticket and I'll help you there with the issue.

**Comment by Xruptor** [comment]
Okay i solved the problem.  It will be available in the next live version update okay.  💚

**Comment by Xruptor** [comment]
Sure thing, thanks for being patient with me.  You will need to rescan all your toons to make it work properly.
