### ISSUE TITLE
[Ru][Wrath] Not searching across characters on same faction and realm

### ISSUE THREAD

**Issue by kanodiry** [Xruptor/BagSync#212]
I have banker character and I can't find any of the items in the search, but I know they are in the bag.
Items can be found if the same item is in the current character's bag.
Tooltips, btw, are fine.

**Comment by Xruptor** [comment]
I'm not sure I follow.  Can you give me screenshots to explain the situation?  Try to be as descriptive as possible as to what items, where, and what exactly you do to replicate it.  Which bags and if you are on Classic, Retail, WOTLK.  The more details the better I can help you.

**Comment by kanodiry** [comment]
Okay. Here is an example:
1. Character 1 have Item [Ruined Pelt]. 
2. I logged as Character 2, who don't owe [Ruined Pelt], opened search window /bgs search and type Ruined Pelt and press Enter - no items found (Search Window is Empty)
![image](https://user-images.githubusercontent.com/62216589/205685970-cf35aae3-2017-408e-9e00-cb37182016b1.png)
3. Then I got [Ruined Pelt] for Character 2, and redo search, and found [Ruined Pelt].
![Снимок экрана 2022-12-05 190728](https://user-images.githubusercontent.com/62216589/205686191-9c5cec6d-e355-4ace-99e0-23c4db49b622.png)
![image](https://user-images.githubusercontent.com/62216589/205686037-12774749-0a93-4964-910d-855af7741f6d.png)
4. At the end I removed [Ruined Pelt] from Character 2 and redo search - again nothing found

**Comment by Xruptor** [comment]
I'm assuming that character 1 is Fizzlespin and Character 2 is Nheffily?  It would be better to use the character names as that can be a bit confusing with the pictures.  Unless character 1 isn't shown above at all even with their character name.  So unless I'm reading this incorrectly.

1. You have a **[Ruined Pelt]** on Fizzlespin.
2. You login to Nheffily and do a search for **[Ruined Pelt]** but get no results.  Even though you know you have a **[Ruined Pelt]** on Fizzlespin.
3. You get a **[Ruined Pelt]** on Nheffily and found the **[Ruined Pelt]**.  But this time it also shows you that you have one on Fizzlespin right?

If the above is incorrect let me know.

**Comment by kanodiry** [comment]
You got it right.

**Comment by Xruptor** [comment]
I was able to reproduce the issue and will fix it in next major version update.  I'm currently working on wrapping up two other tickets for BagSync.
