### ISSUE TITLE
Wrath Classic: error when trying to access config, cant hide minimap icon

### ISSUE THREAD

**Issue by insectdude1258** [Xruptor/BagSync#218]
**Addon version 18.1
Game version: wrath classic 3.4.0 (46902)

i cant get the minimap button to go away and im getting errors on load as well as when i try to choose options in config. It was working fine a week ago when i played last.

Typing the /bgs resetdb command says "unknown command"

This happens on load:**

6x Interface\AddOns\BagSync\wireframe\debug.lua:229: attempt to index global 'BagSyncDB' (a nil value)
[string "@Interface\AddOns\BagSync\wireframe\debug.lua"]:229: in function <Interface\AddOns\BagSync\wireframe\debug.lua:226>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:66: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:61>
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:536: in function `EnableAddon'
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:626: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:611>

6x Interface\AddOns\BagSync\modules\minimap.lua:161: attempt to index field 'options' (a nil value)
[string "@Interface\AddOns\BagSync\modules\minimap.lua"]:161: in function <Interface\AddOns\BagSync\modules\minimap.lua:160>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:66: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:61>
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:536: in function `EnableAddon'
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:626: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:611

**When i try and go to the config options; Main, Display, and Color are all blank and it gives this error when i click that tab**

1x Interface\AddOns\BagSync\modules\config.lua:43: attempt to index field 'options' (a nil value)
[string "@Interface\AddOns\BagSync\modules\config.lua"]:43: in function `member'
[string "@Interface\AddOns\Atlas\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:215: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:164>
[string "@Interface\AddOns\Atlas\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:1193: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1110>
[string "@Interface\AddOns\Atlas\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:1639: in function `FeedGroup'
[string "@Interface\AddOns\Atlas\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:1919: in function `Open'
[string "@Interface\AddOns\Atlas\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:1947: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1945>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:66: in function <Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua:64>
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:300: in function `Fire'
[string "@Interface\AddOns\Ace3\AceGUI-3.0-41\widgets\AceGUIContainer-BlizOptionsGroup.lua"]:20: in function <...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:19>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\InterfaceOptionsFrame.lua"]:29: in function `InterfaceOptionsList_DisplayPanel'
[string "@Interface\FrameXML\InterfaceOptionsFrame.lua"]:47: in function `InterfaceOptionsListButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>
![image](https://user-images.githubusercontent.com/24449926/206833740-e5bab8b1-c7b2-4b43-a6f6-912a25f23181.png)
![image](https://user-images.githubusercontent.com/24449926/206833796-096b5113-262b-451b-9ba4-d58a675efc50.png)
![image](https://user-images.githubusercontent.com/24449926/206833838-45c3d501-4ffb-44d2-b5bd-c24b70462414.png)

**Comment by insectdude1258** [comment]
tried reverting to 18.0 and error still occurred, reverted to 17.9 and problem is resolved

**Comment by Xruptor** [comment]
I'll take a look into this.  I think I know what it is.  But I'll need you to test for me.

**Comment by Xruptor** [comment]
Never mind XD  I found the issue.  I'll fix it in the next update.
