### ISSUE TITLE
[Feature Request] Add an option to sort character db/list manually

### ISSUE THREAD

**Issue by Toasticon** [Xruptor/BagSync#222]
While I appreciate the default being ABC instead of something random like a _certain_ addon. Would it be possible to have your own way to sort things akin to Saved Instances?

I sort my chars on a per gear spec basis more or less which is why I'm asking.

**Comment by Xruptor** [comment]
Hmm I'm not sure I completely understand this request.  So I'll have to take a look at "Saved Instances" as I'm not familiar with that addon.

**Comment by Toasticon** [comment]
See https://github.com/Jaliborc/Bagnon/issues/1484 2nd pic.
You manually pick where they fall in the list by designating them a number.

**Comment by Xruptor** [comment]
> See [Jaliborc/Bagnon#1484](https://github.com/Jaliborc/Bagnon/issues/1484) 2nd pic. You manually sort where they fall in the list by designating them a number. I keep the same layout on the character select screen which makes memorizing who when and where much easier if using the above method.

Oh okay wow, that adds a level of complexity to program that I'm not sure if I'd want to add it.  I would have to program a separate frame that displays all the characters and guilds.  Then provide sorting index editboxes for each.  Add error checks for things like not numbers or negatives when the user types in it the boxes.  In addition create a checkbox somewhere to enable the feature..  Then create logic that checks for the sort index and apply it based on what the user entered.  It may not sound like a lot but that is quite a bit of work for a feature that I'm not sure how many people would use.  Regardless, I always give every request some careful thought.  So let me see if I can figure out a better way to do this and still provide you the request.  Otherwise, I'd have to consider possibly not implementing it.  Let me wrap up another bug ticket and I'll take a look at this afterwards.

**Comment by Toasticon** [comment]
I've compared Saved Instances with Bagsync DB and the code looks fairly similar apart from ["Order"] being used. I only really wanted to replicate Bagbrother functionality without everything else included else but at least I have a starting point now so thanks. I've only ever dealt with lua on a basic level, but I guess it's better late than never. Getting a sorting table up and running doesn't look that fairly advanced if it's just for bags/bank and nothing else.

**Comment by Xruptor** [comment]
> I've compared Saved Instances with Bagsync DB and the code looks fairly similar apart from ["Order"] being used. I only really wanted to replicate Bagbrother functionality without everything else included but at least I have a starting point now so thanks. I've only ever dealt with lua on a basic level, but I guess it's better late than never. Getting a sorting table up and running doesn't look that fairly advanced if it's just for bags/bank and nothing else.

Creating the sorting table isn't what is time consuming, creating a GUI interface that has error checks is what will take some time.  In addition would have to implement code checks for the sorting algorithm and logic checks based on previous selections. Example, if sort by totals is on, then disable that and gray out options for it.  If totals is enabled, then turn off custom sorting and gray that option out.  It can get tedious doing the little things.  I've wrapped up my previous tickets and waiting for a response from the user, I can now take a look at this and see if it's worth implementing without too much hassle.

**Comment by Xruptor** [comment]
After some review, I can probably recycle the BagSync Profiles manager and update the custom BagSyncInteractive Label to support an edit box.  It would require setting up numbers on the characters from 1 to whatever in how you want it sorted.  I don't think I will implement up and down arrows.  So it would require a numbered sequence on the editboxes.  With matching numbers sorting at the same levels.  I.e  1, 2 ,3, 4, 4, 5 the two fours would be in the same level.  I'll look into this a bit more, but if you went ahead and did your own project, please let me know.

**Comment by Toasticon** [comment]
I haven't started yet and and I wont til after a new year at least since I'm busy with other things. Depending how hard is it to implement. Using the profile window sounds like a good idea though. I was thinking of if it were possible to just rearrange them by making each character draggable in the list.

**Comment by Xruptor** [comment]
Implemented.  Will be available next version push.
