### ISSUE TITLE
Interaction with SexyMap Addon

### ISSUE THREAD

**Issue by HausmeistaHausmeista** [Xruptor/BagSync#224]
The addon SexyMap has a functionality to control how visible minimap buttons are shown.
WoW Options -> SexyMap -> Buttons -> Enable "Let SexyMap control button visibility" lets you set the options in the table beneath
As every other addon I use is listed there apart from BagSync, could you maybe look into the issue what makes your minimap button special? :)
Thank you very much

**Comment by Xruptor** [comment]
My minimap button dates back years and years ago.  So it's a bit out of date but is the only one that allows you to position it anywhere on your screen, not just attached to the minimap.  Please give me an addon that works with SexyMap that has the minimap the way you are describing.  I bet you anything it's a DataBroker thing when it comes to the minimap.
