### ISSUE TITLE
CAUSE LAG by fast switching bank tab 

### ISSUE THREAD

**Issue by MorningMistS** [Xruptor/BagSync#228]
1:fast switching bank tab results in high frequency calls of Scanner:SaveGuildBank and findBattlePet

2:findBattlePet can be optimized
ep:
```
local data = C_TooltipInfo.GetGuildBankItem(arg1, arg2)
if data and data.args and data.args[2] and data.args[2].intVal then
	return data.args[2].intVal
end
```

**Comment by Xruptor** [comment]
Technically this is just one less step then what I'm currently doing as I'm pretty much doing the same thing except grabbing the TooltipData and pushing it to TooltipUtil.SurfaceArgs to make it easier to read for battlePetSpeciesID.  However, if you found this method is more efficient and optmized, I will switch it to it.  Thanks 😄 💚

**Comment by Xruptor** [comment]
Oh before I forget some lag will usually occur with the Guild Bank when dealing with Battle Pets because of the tooltip scanning required.  No real way around this until Blizzard gives us the ability to grab BattlePet data without tooltip scanning in the Guild Bank. :(
