### ISSUE TITLE
Enhancement/Issue: Units must be selected by default to 

### ISSUE THREAD

**Issue by Jdaddy0007** [Xruptor/BagSync#237]
By default, one must select characters for the advanced search to even work.  Is there any way this could be defaulted like locations, "selecting none defaults to selecting all?"
![image](https://user-images.githubusercontent.com/73510236/209703432-eebad94a-b41b-451f-b63d-6fefbaefe925.png)

**Comment by Jdaddy0007** [comment]
Or if it could "remember" the units & locations selected from previous searches?

**Comment by Xruptor** [comment]
The feature is more of an heavy duty search and was never intended to have everything constantly selected.  i.e a search to allow you to fine tune searches and customize whom and where you wanted to search.  If you wanted to do a heavy search through all your characters on the normal search window, all you would have to do is enabled BNET account access.  It's not recommended though as that's A LOT of data to have to go through when searching.  It's usually best to keep the data between characters on the same or connected realms.

I will consider the possibility of adding a select all button, but again that defeats the whole purpose of the Advanced Search.

**Comment by Jdaddy0007** [comment]
I see!  And I am able to search/use this for 99% of everything...  Thanks for the consideration!

**Comment by Xruptor** [comment]
I added a 'Select All' button.  Though to be honest, like I mentioned before, this was not the intended purpose of the Advanced Search window.  If you really wanted to just search through all your BNET characters, just enable the BNET option in the BagSync config window and use the regular search window instead.

**Comment by Jdaddy0007** [comment]
I get what you are saying now!  Thank you so much for explaining and adding this feature! One the most responsive creators I've met!   Happy New Year!!!

**Comment by Xruptor** [comment]
> I get what you are saying now! Thank you so much for explaining and adding this feature! One the most responsive creators I've met! Happy New Year!!!

Thank you!  Happy New Year to you too!! 💚
