### ISSUE TITLE
Moving item from guild bank to reagent bag doesn't update tooltip

### ISSUE THREAD

**Issue by b-morgan** [Xruptor/BagSync#245]
On Dragonflight, 10.0.5, the tooltip shows that I have 10 of an item in the guild bank and 20 in my inventory (in the reagent bag) I moved the item from my guild bank directly to my reagent bag. The tooltip showed that the item was no longer in the guild bank but the count in my inventory was still the old value (20). I moved the stack to my backpack and the tooltip was now correct (30). I moved the stack back to my reagent bag.

**Comment by Xruptor** [comment]
It probably has to do with the recent BAG_UPDATE_DELAYED bug they had on all the servers.  It wasn't being fired and many bag addons broke because of it (Including Bagnon).  I'll double check if this is the case.

**Comment by b-morgan** [comment]
You may be right... I see a BAG_UPDATE_DELAYED when I move the item to and from my backpack but I don't see it when I move the item to and from my reagent bag. I do see BAG_UPDATE(5) events.

**Comment by Xruptor** [comment]
> You may be right... I see a BAG_UPDATE_DELAYED when I move the item to and from my backpack but I don't see it when I move the item to and from my reagent bag. I do see BAG_UPDATE(5) events.

Yep it's a major issue and multiple addons rely on that event being fired.  It broke on literally every version of WOW.  They are aware of it and I thought they fixed it, but apparently not.  Let me see if I can do a loophole fix.  I will also check the Discord channel to see if anyone mentioned it.

https://discord.gg/f3tWAP6j

**Comment by Xruptor** [comment]
https://github.com/Stanzilla/WoWUIBugs/issues

https://github.com/Stanzilla/WoWUIBugs/issues/381

For example, I'll check to see it's something that was reported.

**Comment by Xruptor** [comment]
Okay yep they broke it again.  It's not working now on the Retail servers.  This is ridiculous, I don't understand how this issue keeps coming back after resets.
