### ISSUE TITLE
Enhancement request, option to display which guild bank tab

### ISSUE THREAD

**Issue by b-morgan** [Xruptor/BagSync#246]
At some time in the past, I had an addon which displayed in the tooltip not only how many of the item were in the guild bank, but it displayed which tab(s) the item was in.

I'd like BagSync to add an option (because not everyone will want it) to identify which tab contains the item in the guild bank.

**Comment by Xruptor** [comment]
This may be a little difficult since I don't exactly store the tab information where items are stored.  It's just one long table array.  I'd have to investigate how to implement this as a tag identifier.  Not sure at the moment.  I'll have to investigate in order to consider implementing this.

**Comment by b-morgan** [comment]
Thanks for looking into it. I wish I could remember the name of the addon that did keep track. My addons, Skillet and Skillet-Classic capture the guild bank info two ways, as one long table array and as per tab arrays. The per tab arrays are used while I'm fetching items needed to craft something.

**Comment by Xruptor** [comment]
After reviewing this, I'm wondering on how exactly to display the guild tab information if an item is found in multiple tabs.  It would add a bit of clutter I think.  Been contemplating ways to do this without it being over the top.  Especially if they choose not to display the guild names separately but rather as part of each Character name.  Right now it displays **Guild:** for that.  So not entirely sure how I would incorporate tabs into that display.  I suppose I can use brackets but that may be a bit messy or ugly.  If I display tabs, do I list the totals for each tab or just the tabs involved?  Things like that...

**Comment by b-morgan** [comment]
I'd be happy with G1-G7 and G*, i.e. add a single character. When an item is in multiple tabs, just list the total. I'm OK with doing my own sleuthing if an item is in multiple tabs.

**Comment by Xruptor** [comment]
I'm still working on this.  I've rewritten the optional values in BagSync to be expansive for future content.  Meaning I can add values easier in the future when needed, instead of constantly rewriting the order of a comma separated index.  I've already added the guild tabs but need to do some cleanup before I will add the visuals.

**Comment by b-morgan** [comment]
Fantastic! Let me know if there's anything you need from me.

**Comment by Xruptor** [comment]
I finalized the guild bank display changes.  I'll push it live once I cleanup everything.
