### ISSUE TITLE
BagSync Debug window (title) can be moved off-screen

### ISSUE THREAD

**Issue by b-morgan** [Xruptor/BagSync#247]
My curiosity caused me to open the BagSync debug window to see if I could learn anything about issue #245. While adjusting the window location so that my bags and the guild bank didn't cover up the BagSync debug window, I managed to get the debug window title bar off screen. Can't fix that!

Maybe add a "/bgs debug reset" command to reset the window position.

**Comment by Xruptor** [comment]
DOH! I must have forgotten making it snap to the screen XD. Thanks for pointing this out!  I'll see about fixing this issue and resetting the window position.
