### ISSUE TITLE
Enable ExternalTooltip to flash on the AuctionUI(Except for battlepet)

### ISSUE THREAD

**Issue by MorningMistS** [Xruptor/BagSync#259]
I like ebable ExtTooltip

**Comment by Xruptor** [comment]
I'm not sure I completely understand this request?  You want it to flash? The tooltip should work with the AuctionUI.  Unless you mean something else?

**Comment by Xruptor** [comment]
Never mind I see what you are talking about.

**Comment by MorningMistS** [comment]
I mean,this ExternalTooltip is high frequency show/hide

like this

https://user-images.githubusercontent.com/120701230/221332874-61b1e357-0a95-4023-a342-85068cc1016c.mp4

**Comment by Xruptor** [comment]
> I mean,this ExternalTooltip is high frequency show/hide
> 
> like this

Thanks for the video.  I was actually able to reproduce this.  It will be fixed in the next version. 😄
