### ISSUE TITLE
Bug (or enhancement?): currency tracking doesn't display in external tooltip w/ option selected, nor can be turned off

### ISSUE THREAD

**Issue by johndp977** [Xruptor/BagSync#268]
With the "display item in an external tooltip" option selected, currency tooltips still embed BagSync's tracking data in the default tooltip, and the tooltip modifier key has no effect.

Also, when "enable BagSync tooltips" is unchecked, currency tooltips still display BagSync's tracking data.

This feels like it could be a bug, but could also be because currency tooltips work differently than normal item tooltips. In my case, I actually have a separate addon that I hacked together to do currency and gold tracking, and ideally I'd like to be able to just turn off BagSync's currency tracking all together. I certainly don't mind if it's still done in the background, as long as there's not anything visible outside of the dedicated BagSync window for it.

I believe you did something recently to hide extra info for Trader's Tender, but it was a hard-coded special rule, so this would just be something more generic that I can apply to any/all of my currencies if I choose to get the exact same behavior as Trader's Tender.

I think there are a few options to accomplish this.

1. If it's just a bug, then maybe it's something easy to fix ;)

2. If it's because currency is some sort of unique tooltip case, provide a config option to toggle tooltip integration specifically for currencies. All background tracking could remain the same, just short-circuit whatever code appends it to the currency tooltip.

3. Provide a way to blacklist currency IDs, then theoretically I could blacklist all relevant IDs to keep them from showing up in tooltips. A little tedious but certainly fine since currencies aren't added that often. Or, perhaps an option to just blacklist currency tracking all together.

Hopefully there is something you would consider implementing, thanks!

**Comment by Xruptor** [comment]
Currency in your bags and inventory is treated differently then currency in the currency window.  One has an ItemID the other has CurrencyID.  You can blame Blizzard for this lol.  The reason the tooltips show for the currency in the bags is because they are treated as actual items with ItemID's.

Now if you just mean the Currency window, I can put an option to turn off Currency display there.  Otherwise if it's in your bags that's something totally different.

**Comment by johndp977** [comment]
Yep, I'm only referring to the tooltip displayed from the currency window, not currency shown on bags (if any). An option to turn off BagSync's currency display from the currency window would do the trick (ie short-circuit the logic in Tooltip:CurrencyTooltip()).

I recall some of these difficulties with currencies too. I think maybe an event is fired upon mousing over a currency, which was easy to work with in addons. But detecting when moused over a currency and then pressing a key (eg shift) became a lot more tedious, particularly figuring out which currency was actually moused over...

**Comment by Xruptor** [comment]
I have read your suggestion my friend, I'm just trying to catch up to other tickets and workload before I can focus my attention on this particular ticket.  Once I wrap up these rewrites I can work on some of these enhancements.

**Comment by Xruptor** [comment]
I'm currently dabbling in a config screen that allows you to toggle on/off elements of the BagSync scanning and displaying process. 

Such as the following categories:

- bag
- bank
- reagents
- equip
- mailbox
- void
- auction
- guild
- professions
- currency

**Comment by Xruptor** [comment]
I have implemented the External Tooltip for the Currency.  I'm now finalizing the changes to the tracking configuration panel.

**Comment by johndp977** [comment]
Sounding great, I look forward to trying out these changes!

**Comment by Xruptor** [comment]
Tracking has been finalized and so has external tooltips for currency.  Going to wrap up two more additions and cleanups and then I can push this forward.

I even added the font options for the external tooltip lol.

Closing this ticket for the time being.
