### ISSUE TITLE
Some currency shows characters with 0 of that currency

### ISSUE THREAD

**Issue by Sluimerstand** [Xruptor/BagSync#269]
This is _somewhat_ related to #268, but different enough to warrant a separate issue. Basically, title.

![image](https://user-images.githubusercontent.com/29845810/222961869-400832a6-e8e5-4ac4-a54b-3cb789c5e96f.png)

What I would love, is if this worked like the item tooltips did, where it doesn't show characters who have 0 of that thing, or if there were an option to toggle it to be like that. I don't know if this is intended behaviour or not, since it only doesn't show characters who have never had the currency at all.

**Comment by Xruptor** [comment]
Thank you for putting in the ticket.  I'm in the process of doing a major rework in the UI and will take this into consideration when I rework the Currency Module.  I might as well since I'm going to be going in that direction lol.

**Comment by Sluimerstand** [comment]
Great to hear! Good luck with the rework, in the meanwhile I'm absolutely loving the addon. :)

**Comment by Xruptor** [comment]
I have fixed this in the rework.  Should be out any day now.  Closing this ticket for the time being though.
