### ISSUE TITLE
ItemTypes / Expansion missing loc ?

### ISSUE THREAD

**Issue by KatyPurry** [Xruptor/BagSync#286]
Hello

Is it normal that these words appear in brackets or is the translation missing?

![image](https://user-images.githubusercontent.com/89610869/227747769-a7826da2-c12f-4772-8fba-876565b82e79.png)

**Comment by Xruptor** [comment]
The translation is missing.  I'm afraid nobody has really put effort into translating the French localization.

**Comment by Xruptor** [comment]
If you are willing to work on the translations that would be appreciated, otherwise let me know and I'll go ahead and close this ticket.  😃

**Comment by KatyPurry** [comment]
> If you are willing to work on the translations that would be appreciated, otherwise let me know and I'll go ahead and close this ticket. 😃

Sure ! I’ll take a look tomorrow 👌

**Comment by KatyPurry** [comment]
Do you have a tool to add all the missing English language keys to the French translation file?

**Comment by nanjuekaien1** [comment]
Can only be compared to do localization
https://github.com/Xruptor/BagSync/blob/master/locale/enUS.lua

**Comment by Xruptor** [comment]
> Do you have a tool to add all the missing English language keys to the French translation file?

Make the edits here that way I can apply them easier.  Anytime you want to update it, just click this link.  😃 
https://github.com/Xruptor/BagSync/edit/master/locale/frFR.lua

When you are done, just simply add a title and a description at the bottom and submit!  I suggest you do a comparison with the english enUS file as @nanjuekaien1 recommended.

**Comment by Xruptor** [comment]
excellent! Nicely done, if you have ANY issues on any of the localizations terms let me know.  Careful with Color codes btw.  They start with **|c** and have 8 characters so something like `|cFFd1d1d1` followed by the text and finally have an end tag that is `|r`.  So what you should edit is just the text in the middle.  `|cFFd1d1d1` text in the middle` |r`.  Things like `[%s]` are format codes so don't touch those as they will be replaced with text as part of the sentence.

If there is anything else you see that you are confused about, just let me know here.

**Comment by Xruptor** [comment]
I will close this ticket since you are working on the french localizations.
