### ISSUE TITLE
Error when font outline of external tooltip is set to 'None'

### ISSUE THREAD

**Issue by tflo** [Xruptor/BagSync#294]
Getting this error if the outline is set to 'None':

```text
32x BagSync/core.lua:398: Usage: self:SetFont(fontFile, height, flags)
[string "=[C]"]: in function `SetFont'
[string "@BagSync/core.lua"]:398: in function `CreateFonts'
[string "@BagSync/modules/config.lua"]:147: in function <BagSync/modules/config.lua:90>

```

I could get rid of the error by defaulting the `flags` variable to an empty string instead of nil:

core.lua, line 387:

```lua
	local flags = ""
```

Found the hint here: https://wowpedia.fandom.com/wiki/API_FontInstance_SetFont#Arguments

**Comment by Xruptor** [comment]
Yep you are correct!  It appears that an empty string is required or it generates an error.  Nice find!  Thanks for posting a ticket.  😃
