### ISSUE TITLE
Professions

### ISSUE THREAD

**Issue by JimGiordano2** [Xruptor/BagSync#295]

**Comment by JimGiordano2** [comment]
The professions screen has a slight flaw.  I have eleven alts on two different connected servers.  The professions screen only shows ten on each server (using fishing).  This is not a big deal, but something to look at next time you are working in that area.  Thanks for the great addon!

**Comment by JimGiordano2** [comment]
I'm gonna slip this in here because...   I can't find the place for feature requests, could you provide a link please?

**Comment by Xruptor** [comment]
Unless those particular characters actually have fishing and were scanned it will not show.  You may have to open the Fishing Profession screen that's available now if you are on retail.

**Comment by JimGiordano2** [comment]
yes, they all have fishing and were scanned.  I open the fishing profession screen on the missing alt, but no change.  Is some built in limit of 10  on an array or something?

**Comment by JimGiordano2** [comment]
wait-- I take it back.  When i forcibly open the fishing profession window, the missing one now showed up.  I swear I did it before, but it looks good now, at least on the first server.  I try the second server and let you know if it doesn't work.  Thanks for your patience.

**Comment by JimGiordano2** [comment]
yup, all working now.  sorry to waste your time.  thanks again for a great addon.

**Comment by Xruptor** [comment]
No worries!  Glad to have helped.
