### ISSUE TITLE
Saved searches are overlapping in the Saved Search field

### ISSUE THREAD

**Issue by tflo** [Xruptor/BagSync#296]
Started to try out the new Saved Search feature (thanks again for adding!), and found this:

With these two saved searches…

```
Draconic Treatise
```

…and…

```
Strange Petrified Orb || Scrap of Black Dragonscales || Particularly Ordinary Egg || Drop of Blue Dragon Magic || Magically Altered Egg || Everburning Ruby Coals || Egg of Unknown Contents || Speck of Bronze Dust || Sleeping Ancient Mammoth || Emerald Dragon Brooch
```

…the Saved Search filed looks like this:

<img width="603" alt="WoWScrnShot_040823_163633" src="https://user-images.githubusercontent.com/1410282/230727290-8ebf5ac3-951d-48be-a295-5e02d6417812.png">

Both searches are there, if you look closely (and I can even click them both), but I guess the line overlapping isn't intended.

Just added a couple more searches (one liners) for testing: <span>#</span>3 is also shown "behind" the big search string, <span>#</span>4 then finally appears below the big one. So, it seems, the searches are ignoring the (wrapped) line count of the other ones.

**Comment by Xruptor** [comment]
Yep that's a bug it shouldn't be doing that.
