### ISSUE TITLE
Gold Details

### ISSUE THREAD

**Issue by Zaef** [Xruptor/BagSync#297]
Hi! I love this addon, firstly, so thank you so much for your work on it!

I was wondering if you could add an option (or maybe I just missed it on live) so that the "/bgs gold" command would show the Silver and Copper amounts as well.

This is a super low-priority request, mostly because I have slight OCD, as I know you can hover over each character's Gold total to see this. It would just be super convenient for it to display automatically.

Thanks again! <3

**Comment by Xruptor** [comment]
Technically it does show silver and copper if a character has less than 1 gold. Most people have more than 1 gold on their characters and thus the primary form of transactions is usually gold.  This is why it was done this way and honestly to save space on the display screen.  If a user had lets say their server name showing + their faction + race Icon + character name and then all the gold and silver and copper.  That's a huge line and there is a possibility that it will overlap.

If I were to put such an option, you BETTER believe that someone will complain and file a ticket about the stuff overlapping.  It's bound to happen.  This is one of the reasons I decided on displaying the gold the way it is.  I'll think about it and get back to you after the weekend.

**Comment by Xruptor** [comment]
It has been added as an option in the Config.

**Comment by Zaef** [comment]
Thank you so much! I understand your reservations now that you highlighted them. I don't display faction, race, or server so overlapping text hadn't occurred to me. Have a great day and thank you again. ❤️
