### ISSUE TITLE
Feature Request - Add ability to blacklist guild

### ISSUE THREAD

**Issue by jrowles** [Xruptor/BagSync#30]
It would be nice if we had the ability to blacklist a guild.  I want to track some of my guilds but not all of them.

**Comment by Xruptor** [comment]
One of the many reasons I didn't add this in the past is to prevent any future issues with the DB cleanup routine.  I suppose I can make a dropdown of all the current stored guilds and have a blacklist option for it.  Something like the profiles window.  I'll give it some thought.  I don't have a subscription right now so I can't get to it right away.

**Comment by Xruptor** [comment]
After some consideration, I just don't see the need for this ability in BagSync right now.  If there is enough demand for it in the future I may implement it.
