### ISSUE TITLE
Equipped items show in wrong quality

### ISSUE THREAD

**Issue by AlterMannomann** [Xruptor/BagSync#302]
e.g. Item ID 192013 shows with quality 350 green in the extended search (equipped), but equipped ist 382 lila. Found no way to scan this correctly. resetdb didn't help either. Would be great if this could be fixed. Btw. very smooth and nice addon, thanks for that.

**Comment by AlterMannomann** [comment]
Minor issue with /bgs commands. They are localized, which means /bgs berufe opens the professions window correctly in german edition. /bgs professions opens the search window with search text professions in german edition. Took me some time to find it out. Probably a good point in documentation

**Comment by Xruptor** [comment]
> Minor issue with /bgs commands. They are localized, which means /bgs berufe opens the professions window correctly in german edition. /bgs professions opens the search window with search text professions in german edition. Took me some time to find it out. Probably a good point in documentation

That's because any other command after /bgs that isn't a built in localized one goes to the search window.  It's for fast searches like /bgs ghost iron

To get a list of commands just type /bgs or /bgs help

**Comment by Xruptor** [comment]
😄 Thanks for putting in a ticket btw.  These sort of things really help me look through the code and analyze if there is anything wrong.  I will review the documentation and localization though to see if it can be a bit clearer for the future!
