### ISSUE TITLE
Type search for caged pets?

### ISSUE THREAD

**Issue by tflo** [Xruptor/BagSync#304]
How can I narrow down my search to _show only caged pets_ and eliminate noise like shown in the screenshot ("Peanut" is a pet, "Skewered peanut Chicken" is noise):

<img width="589" alt="WoWScrnShot_050223_142101" src="https://user-images.githubusercontent.com/1410282/235665421-32aed347-bdeb-441e-820a-38203001798e.png">

I tried many things, like `Peanut && t:pet`, `Peanut && t:battle pet`, `Peanut && t:battlepet`, `Peanut && t:pet cage`, but to no avail. A negated type (like `t:!=consumable`) doesn't seem to work either.

The `t:pet` seems to match the pet install items (the ones that say "Teaches you how to summon this companion") and is the same as `t:companion` (which is the 'official' type of these things AFAIK), but it doesn't match caged pets (i.e. the ones you have moved from the pet journal into a bag).

Sorry if I'm missing the obvious…

If I'm not missing the obvious —and you are able to improve this— here a proposal:

- `t:pet` should match both caged pets _and_ Companions (the install thingies)
- `t:companion` should match Companions (the install thingies) — as it is now
- `t:battle pet` or `t:pet cage` (or `t:battlepet` or `t:petcage`) should match caged pets

**Comment by Xruptor** [comment]
I never added any qualifiers for battle pets because of the whole issue with the guild bank and mailbox.  I suppose I can have it parse the cache for the information.  It may not be 100% accurate though as remember it's using itemID for the most part.  Let me review the code.

**Comment by tflo** [comment]
OK, I see.

Maybe – just a spur-of-the-moment thought – ***if*** caged pets are the only things that do not belong to any category/type for BS, then you could define a caged pet qualifier by excluding any item that has an associated type?

**Comment by Xruptor** [comment]
I'll just see if I can have it check the Cache that is passed for the SpeciesID.  If it exists then it's a battlepet.  If no cache is passed and a FakeID is passed, then again it's a battlepet.

I will do **t:battlepet** and **t:petcage**

**Comment by Xruptor** [comment]
t:pet the use of just "pet" would be too generic and may cause complications in the future for any equip slot or type that may have the letters "pet" in the word.  So to prevent this I'm sticking with petcage and battlepet.

**Comment by tflo** [comment]
I said `t:pet` just because it already was there before (apparently as synonym to `t:companion`).

Something like `t:allpets` or `t:anypet` would of course also be fine (to match both "types" of pet, i.e. battlepet and petcage). But if you don't want to add such a catch-both qualifier at all, it's also fine :-)

**Comment by tflo** [comment]
Fixed my above post: … i.e. companion and petcage

**Comment by Xruptor** [comment]
Okay I have it set to t**:petcage** or **t:battlepe**t,  it will take companions into account when processing

I have it working now.  This will definitely be my last enhancement or modification.  I'm really only going to do bug fixes from now on.  I don't have a subscription and I'm taking a break from WOW for the time being 😄 .  I do hope this addition does help you though.

**Comment by tflo** [comment]
> Okay I have it set to t:petcage or t:battlepet, it will take companions into account when processing

That's great too :-)

> This will definitely be my last enhancement or modification.

Understood, will only report bugs then from now on ;)

> I don't have a subscription and I'm taking a break from WOW for the time being

I hope you're not going to abandon the addon!

**Comment by Xruptor** [comment]
I'm not going to abandon the addon.  I haven't abandoned it since I created it back in Vanilla WOW.  I just really need a break and I did spend a huge amount of time and resources rewriting the addon.  I just want to put it in maintenance mode for the time being until I get back into WOW again.

**Comment by tflo** [comment]
Good to hear.

> I don't have a subscription

If you ever need someone to test a bugfix or whatever, I'm there.

**Comment by tflo** [comment]
Loaded your new version now, t:battlepet / t:petcage works great. 

Thank you very much! And I wish you a relaxing WoW-free time!

**Comment by Xruptor** [comment]
> Good to hear.
> 
> > I don't have a subscription
> 
> If you ever need someone to test a bugfix or whatever, I'm there.

Thanks!  That is really kind of you.  I'll keep that in mind.

Also I'm glad it worked out and works properly for you.
