### ISSUE TITLE
Minimap button left click selection

### ISSUE THREAD

**Issue by zhpzhp** [Xruptor/BagSync#307]
Hi, is it possible to add an option for us to choose the function when left click on the minimap button? Thank you.

**Comment by nanjuekaien1** [comment]
Left Click Search Window
Right Click BagSync Menu

**Comment by zhpzhp** [comment]
No, I mean if it's possible to change the search to something else, like gold, with an extra option.

**Comment by Xruptor** [comment]
Hello there!  Thanks for reaching out and a possible enhancement.  At the moment you are correct there is no option to change the function of the minimap mouse click actions.  At the current moment it's not a feature that I'd implement as I don't have an active subscription.  So I'm only really doing bug fixes for the time being.  Perhaps in the future I will consider doing something like this.  Thanks for putting in the suggestion!
