### ISSUE TITLE
LUA error constantly

### ISSUE THREAD

**Issue by Xpatro** [Xruptor/BagSync#309]
2x BagSync/libs/LibDDI-1.0/lib.lua:203: attempt to concatenate local 'text' (a nil value)
[string "@BagSync/libs/LibDDI-1.0/lib.lua"]:203: in function `SetText'
[string "@BagSync/libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown.lua"]:566: in function <...nc/libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown.lua:560>
[string "@BagSync/libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown.lua"]:605: in function `SetList'
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1279: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110>
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1639: in function `FeedGroup'
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1564: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1548>
[string "=[C]"]: ?
[string "@BagSync/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <BagSync/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@BagSync/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@BagSync/libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1675: in function `FeedGroup'
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1564: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1548>
[string "=[C]"]: ?
[string "@BagSync/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <BagSync/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@BagSync/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@BagSync/libs/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:508: in function `SetSelected'
[string "@BagSync/libs/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:185: in function <...ibs/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua:181>

Locals:
self = <table> {
 OnRelease = <function> defined @BagSync/libs/LibDDI-1.0/lib.lua:70
 SetOnLeave = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:139
 SetText = <function> defined @BagSync/libs/LibDDI-1.0/lib.lua:198
 OnAcquire = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:73
 GetText = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:105
 userdata = <table> {
 }
 SetPoint = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:110
 SetPullout = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:90
 sub = Texture {
 }
 type = "DDI-Font"
 AceGUIWidgetVersion = 2003
 GetValue = <function> defined @BagSync/libs/LibDDI-1.0/lib.lua:90
 base = <table> {
 }
 text = FontString {
 }
 highlight = Texture {
 }
 useHighlight = true
 Show = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:115
 SetOnEnter = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:146
 events = <table> {
 }
 Hide = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:120
 check = Texture {
 }
 frame = AceGUI30DropDownItem65 {
 }
 SetDisabled = <function> defined @BagSync/libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:125
 SetValue = <function> defined @BagSync/libs/LibDDI-1.0/lib.lua:86
}
text = nil
_ = "Fonts\FRIZQT__.TTF"
size = 10
flags = ""
font = "Fonts\FRIZQT__.TTF"
(*temporary) = "DDI-Font-"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
 AR ZhongkaiGBK Medium = "Fonts\ARKai_T.TTF"
 Fira Mono Medium = "Interface\Addons\WeakAuras\Media\Fonts\FiraMono-Medium.ttf"
 Gentium Plus = "Interface\Addons\SharedMedia\fonts\gentium_plus\GentiumPlus-Regular.ttf"
 Expressway = "Interface\AddOns\Spy\Fonts\Expressway.ttf"
 Big Noodle Titling = "Interface\AddOns\Spy\Fonts\BigNoodleTitling.ttf"
 Myriad = "Interface\AddOns\Spy\Fonts\Myriad.ttf"
 Noto Sans Regular = "Interface\AddOns\BigWigs\Media\Fonts\Noto.ttf"
 NotUI Font light = "Interface\Addons\SharedMedia_MyMedia\font\NotUI Font light.ttf"
 MoK = "Fonts\K_Pagetext.TTF"
 DejaVu (U) = "Interface\Addons\Prat-3.0\fonts\DejaVuSansMono.ttf"
 NotUI Font Heavy = "Interface\Addons\SharedMedia_MyMedia\font\NotUI Font Heavy.ttf"
 WenQuanYi Zen Hei = "Interface\Addons\SharedMedia\fonts\wen_quan_yi_zen_hei\wqy-zenhei.ttf"
 White Rabbit = "Interface\Addons\Prat-3.0\fonts\WHITRABT.ttf"
 TrashHand = "Interface\Addons\Details\fonts\TrashHand.TTF"
 Nimrod MT = "Fonts\NIM_____.ttf"
 Anonymous Pro Bold (U) = "Interface\Addons\Prat-3.0\fonts\AnonymousPro-Bold.ttf"
 All Hooked Up = "Interface\Addons\SharedMedia\fonts\all_hooked_up\HookedUp.ttf"
 Skurri = "Fonts\SKURRI_CYR.TTF"
 Windows 98 System = "Interface\Addons\SharedMedia_Haldu\font\WindowsRegular.ttf"
 Adventure = "Interface\Addons\SharedMedia\fonts\adventure\Adventure.ttf"
 2002 Bold = "Fonts\2002B.TTF"
 AR ZhongkaiGBK Medium (Combat) = "Fonts\ARKai_C.TTF"
 Liberation Serif = "Interface\Addons\SharedMedia\fonts\liberation\LiberationSerif-Regular.ttf"
 ITC Avant Garde Gothic Medium = "Interface\Addons\SharedMedia_MyMedia\font\ITC Avant Garde Gothic Medium.ttf"
 Ubuntu = "Interface\Addons\SharedMedia_Haldu\font\Ubuntu-Regular.ttf"
 Hack = "Interface\Addons\SharedMedia\fonts\hack\Hack-Regular.ttf"
 GothamNarrowUltra = "Interface\Addons\SharedMedia_Haldu\font\GothamNarrowUltra.ttf"
 Yellowjacket = "Interface\Addons\SharedMedia\fonts\yellowjacket\yellow.ttf"
 Ubuntu Bold = "Interface\Addons\SharedMedia_Haldu\font\Ubuntu-Bold.ttf"
 SF Atarian System = "Interface\Addons\SharedMedia\fonts\sf_atarian_system\SFAtarianSystem.ttf"
 TeX Gyre Adventor Bold = "Interface\Addons\SharedMedia\fonts\tex_gyre_adventor\texgyreadventor-bold.otf"
 Fitzgerald = "Interface\A

**Comment by Xruptor** [comment]
What type of WOW server are you playing on?  Are you on the PTR or live?  This is a library issue conflict with (https://www.curseforge.com/wow/addons/libddi-1-0) it seems.  But I need to know a bit more.

@tflo or @nanjuekaien1 can you confirm this bug?

**Comment by tflo** [comment]
BS is running absolutely error-free for me. (WoW 100100 Live)

**Comment by Xruptor** [comment]
> BS is running absolutely error-free for me. (WoW 100100 Live)

That's what I figured.  That library is updated and even BigWigs uses it.  So I'm not entirely sure it's that causing it.

@Xpatro please make sure to answer my question above, in addition, please disable ALL addons except BagSync and see if you still get the error.  If you don't then another addon may be causing a conflict.

**Comment by Xruptor** [comment]
Hmm still have not heard back?

**Comment by tflo** [comment]
What I don’t understand here is how `text` can be nil _at this point_. `font` holds the font path, `text` holds the display name of the font. Trying to reproduce the error, I’ve manipulated the font registrations in my SharedMedia.lua and MyMedia.lua in a couple of ways, but either I don’t get an error at all (font just doesn’t appear in the dropdown) or an error comes much earlier, e.g. already from SharedMedia.

**Comment by Xruptor** [comment]
> What I don’t understand here is how `text` can be nil _at this point_. `font` holds the font path, `text` holds the display name of the font. Trying to reproduce the error, I’ve manipulated the font registrations in my SharedMedia.lua and MyMedia.lua in a couple of ways, but either I don’t get an error at all (font just doesn’t appear in the dropdown) or an error comes much earlier, e.g. already from SharedMedia.

Yep it's one of those things I just can't understand how it happened.  font is a path string to the text name.  Then the SharedLibrary loads that font object and returns it.  It's up to the object to use it.  However, it's stating that text is nil which makes no point as the object was created in the first place.  So how it marks it at nil with a font return is a bit weird.  Almost as if it was intercepted someway by another addon.  That or the error got generated as a cascade error from another addon.  Which is a possibility.

In any case I'm trying an experiment and have reverted the LibDDI library that was used to a much older one that is used by many more addons.  AceGUI-3.0-SharedMediaWidgets is used by ElvUI, AdiBags, etc... wtc.. it's been around for a long time.

Here is a test version which I swapped out LibDDI with AceGUI-3.0-SharedMediaWidgets @tflo and @Xpatro .  Let me know if it works for you.
[BagSync.zip](https://github.com/Xruptor/BagSync/files/11536613/BagSync.zip)


P.S: I don't understand why people file tickets if they don't plan on following up or responding to questions.

**Comment by tflo** [comment]
It works for me (only briefly tested, playing around with the font menu for the extra tooltip). But – for me – LibDDI also works, so not a groundbreaking information ;)

Now I get the typical empty entries in the font dropdown list (at first open), which the author of LibDDI has mentioned in his comment at line 198 in lib.lua. So, LibDDI indeed seems better :)

**Comment by Xruptor** [comment]
> It works for me (only briefly tested, playing around with the font menu for the extra tooltip). But – for me – LibDDI also works, so not a groundbreaking information ;)
> 
> Now I get the typical empty entries in the font dropdown list (at first open), which the author of LibDDI has mentioned in his comment at line 198 in lib.lua. So, LibDDI indeed seems better :)

That's very interesting.  Considering that ElvUI, AdiBags, Skada, and many others use the **AceGUI-3.0-SharedMediaWidgets**.  I wonder how and IF they deal with the empty entries in the dropdown.  I don't recall seeing them myself but that doesn't mean it doesn't happen.  The library swap is just an experiment, it is interesting though that the dropdown does load a bit faster without a pause though for me like LibDDI did.

**Comment by tflo** [comment]
>  I wonder how and IF they deal with the empty entries in the dropdown.

I said "typical" because I know those empty entries from many addons. So I would say most of them don't deal with it ;)
(And it isn't a super-big deal, as the entries are only missing at the first opening, and heck, how often do I change the font of something? I use the same font almost everywhere.)

**Comment by Xpatro** [comment]
> What type of WOW server are you playing on? Are you on the PTR or live? This is a library issue conflict with (https://www.curseforge.com/wow/addons/libddi-1-0) it seems. But I need to know a bit more.
> 
> @tflo or @nanjuekaien1 can you confirm this bug?

I dont run any addon called Lib.


Just had ANOTHER bug... crap happens when mouseover stuff
RETAIL EU / 10.1.0 (49679)

Bagsync Version: 19.14

**Comment by Xruptor** [comment]
> > What type of WOW server are you playing on? Are you on the PTR or live? This is a library issue conflict with (https://www.curseforge.com/wow/addons/libddi-1-0) it seems. But I need to know a bit more.
> > @tflo or @nanjuekaien1 can you confirm this bug?
> 
> I dont run any addon called Lib.
> 
> Just had ANOTHER bug... crap happens when mouseover stuff RETAIL EU / 10.1.0 (49679)
> 
> Bagsync Version: 19.14

can you please provide the error that occurs when you mouse over stuff?  I'm having a hard time reproducing this bug.  

Did you disable ALL addons except BagSync and see if you still get errors?  I need to rule out if its a conflict with any other addon.

**Comment by Xruptor** [comment]
> > I wonder how and IF they deal with the empty entries in the dropdown.
> 
> I said "typical" because I know those empty entries from many addons. So I would say most of them don't deal with it ;) (And it isn't a super-big deal, as the entries are only missing at the first opening, and heck, how often do I change the font of something? I use the same font almost everywhere.)

Well I may switch it over to the other library as LibDDI  is only really used in BigWigs.  I did notice a slight improvement in that weird delay I'd get when opening the config screen when using LibDDI.  I don't seem to get it with AceGUI-3.0-SharedMediaWidgets.  Also AceGUI-3.0-SharedMediaWidgets doesn't require me to do a for/loop through a list for the results (not that it matters much LOL).  I'll give it a few more tries and decide.  The only nice thing about LibDDI is that it's updated code whereas AceGUI-3.0-SharedMediaWidgets hasn't been updated in ages.  (if it's not broke, don't fix it situation XD)

**Comment by Xruptor** [comment]
> AceGUI-3.0-SharedMediaWidgets

Yeah lol I only realized it afterwards.  I need more coffee ☕ .  On a side note I cannot for the love of me reproduce this error.  It only occurs in my mind if LibSharedMedia just doesn't create the mediaList table to pass in it's **List** function.  Which in turn would cause LibDDI to fail during it's constructor on SetText.  The issue i'm having is what could possibly make LibSharedMedia fail?  I just don't get it.  It has to be some sort of cascading error from a previous error somewhere.

@Xpatro don't forget to follow my instructions above.
https://github.com/Xruptor/BagSync/issues/309#issuecomment-1559029228

BTW you may be getting multiple errors that you aren't seeing.  I highly recommend the following addons to track multiple bugs happening.  **(Bugsack requires bug-grabber to work)**
https://www.curseforge.com/wow/addons/bug-grabber
https://www.curseforge.com/wow/addons/bugsack

**Comment by nanjuekaien1** [comment]
I'm taking a lazy break these days.

**Comment by tflo** [comment]
And, btw, …

> whereas AceGUI-3.0-SharedMediaWidgets hasn't been updated in ages. (if it's not broke, don't fix it situation XD)

… this is a poor philosophy. The correct phrase is "fix it before it breaks" 😁

**Comment by Xpatro** [comment]
right now i have not had the same issue coming up but a new one came up after the update... 
everytime i hover over quest item (flightstone) atleast now i nnoticed it keep trigger something with tooltip bagsync issue (index frame?)
![51df4a913051e920a7f07ae9e8c034b9](https://github.com/Xruptor/BagSync/assets/105673072/61482c87-05e9-4846-a7fc-51cf649a3dea)

**Comment by Xruptor** [comment]
> right now i have not had the same issue coming up but a new one came up after the update... everytime i hover over quest item (flightstone) atleast now i nnoticed it keep trigger something with tooltip bagsync issue (index frame?) ![51df4a913051e920a7f07ae9e8c034b9](https://user-images.githubusercontent.com/105673072/240972664-61482c87-05e9-4846-a7fc-51cf649a3dea.jpg)

Interesting, I wonder if they are modifying stuff with the Currency window yet again?  I'll take a look.

**Comment by Xruptor** [comment]
@Xpatro I'm determined to fix these darn bugs for you XD.  Try this version it should fix it I think.  Hopefully everything should work with no errors.

[BagSync.zip](https://github.com/Xruptor/BagSync/files/11568466/BagSync.zip)

**Comment by Xruptor** [comment]
:) let me know if everything works so I can push it to the live servers.

**Comment by nanjuekaien1** [comment]
@Xruptor 
Wow, xan whole family bucket update.

**Comment by Xpatro** [comment]
So faar with the file you sent has not triggered a single error for me.
Going to keep testing to latest of wednesday when i repeat the quest on warlock for the same questline that triggered the error that i garantied also got it from.

Compressed original and deleted it, replaced the folder with the file you sent me.

**Comment by Xruptor** [comment]
> So faar with the file you sent has not triggered a single error for me. Going to keep testing to latest of wednesday when i repeat the quest on warlock for the same questline that triggered the error that i garantied also got it from.
> 
> Compressed original and deleted it, replaced the folder with the file you sent me.

Oh good :)  I figured it was something to do with the QTip extra tooltip option.  There was a frame call issue when it would display on the Currency window.  I must have missed that.  Thanks for pointing it out!  I'll go ahead and push this version since I was able to replicate your error myself on my end.

**Comment by tflo** [comment]
Out of curiosity, the OP issue with the missing font display text (LibDDI-1.0/lib.lua:203: attempt to concatenate local 'text' (a nil value)) was also caused by or related to the tootltip issue?

**Comment by Xruptor** [comment]
> Out of curiosity, the OP issue with the missing font display text (LibDDI-1.0/lib.lua:203: attempt to concatenate local 'text' (a nil value)) was also caused by or related to the tootltip issue?

I believe so yes.  Since the QTip uses the font and subsequent library.  I believe what was happening was a domino effect in terms of errors.  When it would fail so would all other functions associated with QTip.  I'm assuming what happened was the error was generated, then they went to the config panel which would cause another error due to the one already have occurred.  It would make sense as that would explain why the font object was never created to pass to SharedMedia.
