### ISSUE TITLE
Request: on Tooltip, Add ICON-ID please?

### ISSUE THREAD

**Issue by Xpatro** [Xruptor/BagSync#310]
Request: on Tooltip, Add ICON-ID please?
I can only see spellid.

Wish it could add icon-id aswell.
Since im making addons/weakauras, the iconid is quite important.

**Comment by Xruptor** [comment]
I'm not sure how useful that would be for an inventory management system?  It wouldn't give you the iconid for action abilities if you ever use weakauras for that.  It would only give you icon ids for items only.  So I don't know if this would be incredibly useful as a huge majority of weakauras deal with abilities rather then items.  If you have a good reason for it, I may possibly add it in the future.

Also right now I currently do not have a subscription.  I'm REALLY REALLY avoiding adding any new features or content to BagSync.  Honestly, at the moment I'd prefer just to have it in maintenance mode and fix bugs as folks come across them.

**Comment by Xpatro** [comment]
Well would be very handy, right now i have to wowhead search icons to find it and can be very annoying to find it.
especilly if u need it for weakaura to show correct icon for WA/Addon, when trinket or item is found, usable or triggered.

**Comment by Xruptor** [comment]
Hmm okay but it would only apply to items?  Not sure how good that will be.  I'll consider it if it's not TOO much of a hassle.  Otherwise it may be awhile before I implement it.
