### ISSUE TITLE
"Amount" enhancement

### ISSUE THREAD

**Issue by Rolfeg** [Xruptor/BagSync#315]
Hello.
I use the AllTheThings addon, and sometimes it makes some frames VERY big - you can't tell what amount of currency corresponds to which character.

An example:
![frKZ8VI](https://github.com/Xruptor/BagSync/assets/86924313/b062ee87-4ded-47db-918e-e85ed25ee325)
So I came up with a few possible enhancements.
1) Add an option like the existing "display total item count by character class color", but for amount only or extend existing option for the amount of items too.
2) Or/and add an option like "add class icon at the end"

Something like this:
![BZphUd1](https://github.com/Xruptor/BagSync/assets/86924313/8c7a3569-9ed5-44ba-8780-ede4c10382be)

It is possible?

**Comment by Xruptor** [comment]
Have you tried using the External Extra Tooltip option in BagSync?  It's on the main setup panel.  That may be better for you since you have an incredibly long tooltip.  Let me know if that helps?

**Comment by Rolfeg** [comment]
Thanks, I didn't know about this option. It's better, but a little weird.
I would still prefer the option with color, but if it's difficult, then it will do.
![изображение](https://github.com/Xruptor/BagSync/assets/86924313/244483fa-8faa-48dc-8e56-100a46c04cbb)

**Comment by Xruptor** [comment]
Hmm that's odd it shouldn't show up in the middle like that.  My only guess is that All the Things is stretching the tooltip so much that it's basically beyond the scope of the middle position for the tooltip.  That is why it's centered.  In terms of your addition, I don't have a subscription and I really don't want to add anymore enhancements at the moment.  Hopefully the extra tooltip helps.
