### ISSUE TITLE
Keybinds are not obvious now after DF

### ISSUE THREAD

**Issue by mbattersby** [Xruptor/BagSync#319]
Because header= is no longer shown in the keybindings they aren't obviously part of BagSync now.

![image](https://github.com/Xruptor/BagSync/assets/1300207/84849e04-5f8d-4a3c-809b-32ca2b33fb18)

I would suggest the right fix is probably to remove header= and set category="BINDING_HEADER_BAGSYNC" in Bindings.xml

**Comment by mbattersby** [comment]
Unless header= being not shown is some bug in my UI.

**Comment by Xruptor** [comment]
That's very odd!  It should be showing BagSync as I provide a header format for the Addon.  Unless they changed things (which they always freaking do) it should be working?  I'd have to take a look at it honestly to see what's going on.

**Comment by mbattersby** [comment]
Seems like header= is no longer working (WeakAuras authors confirmed also) and just shows a blank line. It may be a bug but Blizzard don't seem to be going to fix it. I think the right fix is to remove header= and add category= to all the bindings.

**Comment by Xruptor** [comment]
Why am I not surprised when it comes to Blizzard fixing things.... lol.  I'll take a look.

**Comment by nanjuekaien1** [comment]
Get used to it.

**Comment by Xruptor** [comment]
Hmmm I wonder if there is a conflict from the other WOW clients vs Dragonflight in terms of the headers.  That could be why it's picked up in the WOTLK and Classic but not Dragonflight.  If I used categories it may break that.  Would have to do some testing sometime next week.

**Comment by Xruptor** [comment]
Okay I took some time to look into this.  You were right, they did remove the header parameter.  Apparently now all you need is to set your own category and it adds it to the list.  I will be pushing an update for this.  Thank you very much for filing this ticket!

**Comment by Xruptor** [comment]
This was fixed in latest commit:
https://github.com/Xruptor/BagSync/commit/25cb6614ff45b68f529284d628a037e0db9f1c58
