### ISSUE TITLE
Emblem counts in WOTLK

### ISSUE THREAD

**Issue by sam-k-taylor** [Xruptor/BagSync#320]
Would be nice to see the number of emblems, Scourgestones ect... across characters on tooltip

**Comment by Xruptor** [comment]
If it's a currency, you should be able to see your characters and totals in the currency window of BagSync.  Currency and Items are treated differently by the WOW client.  That's why it's separated.

**Comment by Xruptor** [comment]
Whoops closed it by accident LOL.

**Comment by sam-k-taylor** [comment]
Currency window is empty on WotLK classic

![image](https://github.com/Xruptor/BagSync/assets/71709524/b2baa6e3-1e61-4b60-b4bb-ac5cee34df14)

Tracking enabled

![image](https://github.com/Xruptor/BagSync/assets/71709524/a74369e8-ca32-4c60-846e-2d9e5b84a342)

**Comment by Xruptor** [comment]
That's really odd?  Perhaps the currency is broken in the WOTLK client or it's treated differently?  I recall it working before.

**Comment by sam-k-taylor** [comment]
if you need me to test anything to get this working i can do

**Comment by sam-k-taylor** [comment]
@Xruptor any update?

**Comment by sam-k-taylor** [comment]
bcmnopqrstuvwxyz1234567890

**Comment by Xruptor** [comment]
> @Xruptor any update?

I've been worked up in stuff at the moment.  I hadn't had a chance to pop in the PTR version of WOTLK to check.  Mmm perhaps I have some time in the afternoon to quickly hop on and see what's going on.

**Comment by Xruptor** [comment]
Just to make sure you are referring to these right? @sam-k-taylor 
https://www.wowhead.com/wotlk/item=12841/invaders-scourgestone
https://www.wowhead.com/wotlk/item=12841/invaders-scourgestone

and these right?
https://www.wowhead.com/wotlk/currency=102/emblem-of-valor

for the stones, note they are items that go in your inventory and not the currency window of your character.  That's probably why they aren't showing.  They are treated as items rather then actual (game coded) currency.  I'd have to review that.

In terms of the emblems if they ARE showing in the in game currency window for Blizzards stuff, then it should be counting them in BagSync. I'd have to see a screenshot of your in game currency window (the blizzard one, not the BagSync one).

**Comment by Xruptor** [comment]
Okay so I was able to do the stuff that is considered currency.  But the items that go into your inventory or bags, really aren't considered "currency" in the code itself.  It's just regular items that you stack up to turn in.  These types of items ARE counted in BagSync, just not in the Currency window.  You can do a search for them and view the tooltip there in BagSync for those.

**Comment by sam-k-taylor** [comment]
@Xruptor these https://www.wowhead.com/wotlk/currency=2711/defilers-scourgestone

**Comment by sam-k-taylor** [comment]
![image](https://github.com/Xruptor/BagSync/assets/71709524/fc7f8a09-79bf-483d-a365-500711078581)
Legend
