### ISSUE TITLE
Due to changes in the database. Your BagSync database has been reset.

### ISSUE THREAD

**Issue by WHTJunior** [Xruptor/BagSync#324]
I couldn't find this issue, I just installed today, and every character is resetting the database, with the following message. This includes the very first character that I logged in with, after installing it.
![image](https://github.com/Xruptor/BagSync/assets/159966536/30cc2d01-9ddb-4fc5-bf0d-6521979b083a)

Checking the profile of the character shows that it deleted any previous profiles (in this example, I had managed to get three in here, by popping back into previously loaded characters, but now it is only showing this one).
![image](https://github.com/Xruptor/BagSync/assets/159966536/0a16582f-a716-43bf-9e1d-240b54ef81da)

As I stated above, I found out that if I go back to previously-loaded characters, it's working, but for each new character that BagSync has not seen, it does this. Before I continue logging into my many, many, many alts, I just want to make sure there's not something that I'm doing, or not doing, that might drive this behavior.

**Comment by WHTJunior** [comment]
Also, while I'm here, is it possible to add an Account Profile, so that I can check a box, and it stops creating a separate profile for each character? I'd like to be able to set the configs once, and not have to keep setting them again, especially if I keep losing the entire database sync.

**Comment by Xruptor** [comment]
That should not be happening.  The only way that gets toggled is if the BagSync.lua file is being overwritten every single time.  The reason I say that is because the flag that checks for that is **forceDBReset** in the BagSync.lua file.  It should be **3** currently as I only raise that when I want to force the DB to be refreshed to all users.

I would check your **WTF\Account\<<YOUR ACCOUNT NAME>>\SavedVariables** folder for the BagSync.lua file.  See if it keeps being overwritten somehow.  Because if the BagSyncDB is being overwritten, then that flag is constantly being reset.  Let me know if that is the problem.

**Comment by Xruptor** [comment]
Don't forget to check to see if the BagSync.lua file keeps being overwritten.  If that is happening then the symlink is causing issues with the multiple accounts.  Meaning the file is being regenerated each time the addon loads, normally this doesn't occur when you use one account.

Try this version of BagSync.  I disabled the DB checks.  Please let me know if the data still gets rewritten.  If it does, then it may be an unattended side effect of using sysmlinks that I'm unaware of.
[BagSync.zip](https://github.com/Xruptor/BagSync/files/14274190/BagSync.zip)

**Comment by WHTJunior** [comment]
I did a full restart, still using the listed newest version of the addon, and the next new character did not get the error. I'll keep checking, and let you know if anything else glitches. Maybe something bugged out the first session, and hopefully it will be fine from here. I appreciate the quick responses.

**Comment by Xruptor** [comment]
> I did a full restart, still using the listed newest version of the addon, and the next new character did not get the error. I'll keep checking, and let you know if anything else glitches. Maybe something bugged out the first session, and hopefully it will be fine from here. I appreciate the quick responses.

Sure thing, just keep me informed.  What I did was disabled the DB check in that test version I listed above.  If it works out for you, then I'll just update the code to reflect that.  I'm pretty sure by now everyone has been using the new version of BagSync anyways with the updated DB.

**Comment by WHTJunior** [comment]
Looks good. I have here, a cross-faction, cross-server, cross-account profile list. You might not be able to tell, but Stormwell is on a different subaccount than the rest. Each character seems to use the same profile settings as the previous ones, now.
![image](https://github.com/Xruptor/BagSync/assets/159966536/8dba24db-429b-4615-a40d-533929a9caa1)
I do appreciate all of your help with this, even though I can't replicate it.

**Comment by Xruptor** [comment]
> Looks good. I have here, a cross-faction, cross-server, cross-account profile list. You might not be able to tell, but Stormwell is on a different subaccount than the rest. Each character seems to use the same profile settings as the previous ones, now. ![image](https://private-user-images.githubusercontent.com/159966536/304944729-8dba24db-429b-4615-a40d-533929a9caa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDE3MTYsIm5iZiI6MTcwODEwMTQxNiwicGF0aCI6Ii8xNTk5NjY1MzYvMzA0OTQ0NzI5LThkYmEyNGRiLTQyOWItNDYxNS1hNDBkLTUzMzkyOWE5Y2FhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxNjM2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWE5ZWM2YTlhMDA2MzZlMDQxMmFhMWFmMWViMzRiMTlmM2I2Zjg4YTUwZTRkMGJhMDdiN2Y1NWE2MjQxYWZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f96N-a7aKEj263PBA9MyjolYlgpsgB4Ir12plwYwxu8) I do appreciate all of your help with this, even though I can't replicate it.

That's great news.  I'll just go ahead and upload the updated version with the DB checks off.  Honestly, I'm sure most people have upgraded by now anyways.

**Comment by tflo** [comment]
> I have 5 accounts under my Bnet, and they are all symlinked to the same primary folder.

Out of curiosity:

Assuming this includes the Saved Variables folder, does this work reliably?

What happens if you log out of two accounts at the same time, or if you lose connection, so each client tries to write to the files at the same time? Have you ever had data loss / corrupted files?

**Comment by WHTJunior** [comment]
Yes, the Saved Variables file is in my main account, and all of the other accounts are just fake forwarded folders, pointing at that folder, as if its contents was their own.
![image](https://github.com/Xruptor/BagSync/assets/159966536/e6234af6-bfc1-4339-abec-516f47fa6e9f)
![image](https://github.com/Xruptor/BagSync/assets/159966536/bc7f02fa-1035-42bd-ac4e-b97a5af4fb0d)
I forget what the extra ones are, but the unlinked one is my wife's.

 I had too many issues with other addons, so I don't log into them on the same computer any more.

**Comment by Xruptor** [comment]
> Yes, the Saved Variables file is in my main account, and all of the other accounts are just fake forwarded folders, pointing at that folder, as if its contents was their own.
> 
> I forget what the extra ones are, but the other named one is my wife's.
> 
> I had too many issues with other addons, so I don't log into them on the same computer any more.

I removed the pics as it was showing your account names as directories.  Just for safety reasons.  You can do the pics again but just blur out the account names.  None of that stuff is stored in SavedVariables so that can be shared with no problems.

**Comment by tflo** [comment]
> None of that stuff is stored in SavedVariables so that can be shared with no problems.

Now, in the second image I see 6 folder symlinks named as account folders (like "123456789#1"). If I'm seeing this correctly, he's sharing SavedVariables folders (contained within) from one account with several others.

Just wondering if this goes well, as I had a similar idea some time ago, but it seemed too risky to me, for the above mentioned reasons.

**Comment by Xruptor** [comment]
> > None of that stuff is stored in SavedVariables so that can be shared with no problems.
> 
> Now, in the second image I see 6 folder symlinks named as account folders (like "123456789#1"). If I'm seeing this correctly, he's sharing SavedVariables folders (contained within) from one account with several others.
> 
> Just wondering if this goes well, as I had a similar idea some time ago, but it seemed too risky to me, for the above mentioned reasons.

The ones inside the SavedVariables or at least the ones under the account level folder.

So WOW uses two systems actually for the account folder.  The older system uses an account name that is still used today as it's backwards compatible and plenty of people still utilize it.  Normally this is usually still used in the Retail versions.  Newer accounts or linked accounts use the numbered system even with Retail.  I'm not entirely sure why they never fully migrated over to this system, but the older named ones are still in use.  It's best to avoid linking or showing those in general, the numbered ones doesn't really matter.  It's the named ones that's an issue.
