### ISSUE TITLE
[Bug?] Duplicate currencies in module if you change client language

### ISSUE THREAD

**Issue by zeenk** [Xruptor/BagSync#328]
Yesterday I was testing loading up my wow client in german just to see if my weakaura I made was working for other languages and today when I was gonna check currencies in BagSync I noticed some had duplicated with the german name, is it possible to get rid of them or should I just do a savedvariable wipe on my account? 😂 

![2024-03-18_23-36-19](https://github.com/Xruptor/BagSync/assets/68170439/95ae24f0-eedf-40e8-8a37-c78fc22852e7)

**Comment by Xruptor** [comment]
The only way that can happen is if for SOME reason Blizzard decided to use different currencyID's for various languages.  I'd have to check but this isn't a bug that would normally happen unless you specifically changed languages.  Meaning it's not something you see everyday or would affect that many people.  I'd need a look at your BagSync.lua file from WTF/SavedVariables folder to determine that.

**Comment by zeenk** [comment]
[BagSync.zip](https://github.com/Xruptor/BagSync/files/14655346/BagSync.zip)

**Comment by zeenk** [comment]
The currency id is the same but I'm guessing since the german name is different it then created a new line for the german version

**Comment by zeenk** [comment]
Oh right.. I found why it was doing this, it was because I have not logged in on every alt yet with the different language client so the addon was still storing the english version names as well, but once I logged on all alts with german client then all english names were gone, so you can ignore this. sorry :)

**Comment by Xruptor** [comment]
> Oh right.. I found why it was doing this, it was because I have not logged in on every alt yet with the different language client so the addon was still storing the english names as well on some alts, but after I logged in on all alts with german client then all english names were gone, so you can ignore this. sorry :)

Are you sure though?  I could always look at the code and just add some sort of check not to duplicate based on CurrencyID.

**Comment by zeenk** [comment]
Sure, if you have a quick fix for it then go ahead and add it :)

**Comment by Xruptor** [comment]
> Sure, if you have a quick fix for it then go ahead and add it :)

I'll just add a redundancy check to make sure it doesn't repeat the currencies.
