### ISSUE TITLE
Can you add tooltip for equipped bags

### ISSUE THREAD

**Issue by PirateKain** [Xruptor/BagSync#330]
I know I asked this before along with adding tooltip for Equipped Profession Tools. 

I want to give all my alts new bags again but it would be easier if I could see who has what bags so I know who needs bigger bags. Also with the Hearthstone Event I had a hard time remembering what characters had already got the new 36 slot bag "Collector's Carryall" without logging onto each of them and turning on the option to see bags on my bag addon. Then turn it off again when I'm done.

So what I', asking is could you add Tool Tips for Equipped Bags like you did for the Equipped Profession Tools.

Please and thank you.

**Comment by Xruptor** [comment]
I'd have to check but this has always been an issue with the various Bag addons that are out there.  If multiples of the same type of bag are equipped, how would I even display that?  Equipped: 1,3,4,5? What if you hover over a bag type in your actual bags?  Not only will it show how many you have but you'd get an Equipped mention to it.  There is a lot of confusing stuff to have to sort out in those scenarios.  I like things to be as simple as possible in the tooltip displays.  I will revisit the code and look into this again, but I can't promise you I'll implement anything though.

**Comment by PirateKain** [comment]
I'd imagine it would be the same as all the rest.

Wouldn't it be an Icon for either: equipped, inventory, Mailbox, Auction house, Guild bank, bank and a
NEW icon for bank equipped followed by the number of them.

This is already within the addon is it not? Except for the new icon for Bank Equipped.

I don't think it's another addon I have, I could be wrong.

**Comment by Xruptor** [comment]
In the next version I added the ability to track the amount of equipped bags a character has.  In addition I added the ability to display what [bag slots] the character has the bags equipped in.  NOTE:  The display of bag slots is disabled by default.  So you have to enable it in the config window.  I also added a config to set the color for it.

**Comment by PirateKain** [comment]
Sweet I see this thanks. Would it be possible to show bank equipped separate from bank inventory. Right now it just shows the bank symbol no matter if the bag is equipped or just in the banks inventory. I suppose you'll need a new symbol for Bank Equipped though.

Anyway thanks for what have added so far. It's a big help.

**Comment by Xruptor** [comment]
The bank bags actually aren't tracked.  It's just the character bag slots.  When you hover over a tooltip in the bank bag, what you are seeing is the tooltip slots for any bags your character may have equipped in their bag slots, not the bank slots.

Bank bags are treated differently by Blizzard then actual character bags.  It would require additional code to do as developers can't access the bank when it's not in use.
