### ISSUE TITLE
no longer working in PrePatch

### ISSUE THREAD

**Issue by asa-git** [Xruptor/BagSync#333]
Hi there,

Since prepatch the addon is no longer working.
There are no errors on the UI.
I have even delete the BagSync.lua from my WTF folder, but still no tooltip while moving the mouse over an item nor while using the search function of the addon.

Best regards.
asa

**Comment by Xruptor** [comment]
Hmmm I'll need to figure out a way to test that.  This is the first I hear of this and I was able to get the addon working in 10.2.7 PTR.  If there are no errors then I'm not sure what would cause it to stop working?  Usually it would generate an error or something and I can track down the issue.

Try installing these two addons to track possible bugs.

https://www.curseforge.com/wow/addons/bugsack
https://www.curseforge.com/wow/addons/bug-grabber

Bugsack requires bug-grabber.  Also make sure addon errors are turned on in your game settings.

**Comment by Maarslet** [comment]
To specify, this is an issue in the Cataclysm pre-patch, not on Retail. 
- Searching up items with /bgs works just fine
- No tooltip appears on any items
- BagSync causes a significantly longer loading screen (From 10 seconds without to almost 60 seconds with it)

Bagnon released an update today with the changelog including "Cata: Now displays item and currency tooltips properly.", so there might be something different going on in the API

**Comment by Xruptor** [comment]
> To specify, this is an issue in the Cataclysm pre-patch, not on Retail.
> 
> * Searching up items with /bgs works just fine
> * No tooltip appears on any items
> * BagSync causes a significantly longer loading screen (From 10 seconds without to almost 60 seconds with it)
> 
> Bagnon released an update today with the changelog including "Cata: Now displays item and currency tooltips properly.", so there might be something different going on in the API

Let me double check then as I wasn't sure what pre-patch what you guys were referring to.  I'll need to figure out a way to test it without having a subscription.

**Comment by Maarslet** [comment]
The "Public Test Realm (Wrath Classic)" is on patch 4.4.0, you should be able to test it there

**Comment by Xruptor** [comment]
> The "Public Test Realm (Wrath Classic)" is on patch 4.4.0, you should be able to test it there

I found the bug.  It's incredibly stupid.  They broke their own tooltip processor.  I updated the check for it, it's literally ONE single word that had to be changed.  Go figure....
