### ISSUE TITLE
LUA errors [TWW beta]

### ISSUE THREAD

**Issue by tnwn** [Xruptor/BagSync#338]
**LUA 1/2 (on load)**
Message: ...s/BagSync/libs/LibItemScout-1.0/LibItemScout-1.0.lua:480: attempt to call global 'GetItemClassInfo' (a nil value)
Time: Sun Jun  9 13:39:10 2024
Count: 1
Stack: ...s/BagSync/libs/LibItemScout-1.0/LibItemScout-1.0.lua:480: attempt to call global 'GetItemClassInfo' (a nil value)

Locals: 

**LUA 2/2 (on hovering item in bag)**
Message: Interface/AddOns/BagSync/wireframe/data.lua:616: attempt to index field 'tracking' (a nil value)
Time: Sun Jun  9 13:40:49 2024
Count: 10
Stack: Interface/AddOns/BagSync/wireframe/data.lua:616: attempt to index field 'tracking' (a nil value)
[string "@Interface/AddOns/BagSync/wireframe/data.lua"]:616: in function `GetPlayerGuildObj'
[string "@Interface/AddOns/BagSync/wireframe/tooltip.lua"]:764: in function `TallyUnits'
[string "@Interface/AddOns/BagSync/wireframe/tooltip.lua"]:1191: in function <Interface/AddOns/BagSync/wireframe/tooltip.lua:1166>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1532: in function `OnUpdate'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1491: in function `OnEnter'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1487: in function <...s/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua:1486>

Locals: self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 __cache = <table> {
 }
 name = "BagSync_Data"
 orderedModules = <table> {
 }
 enabledState = true
 baseName = "BagSync"
 defaultModuleState = true
 moduleName = "Data"
}
player = <table> {
 lowerKey = "alleria;khadgar"
 realmKey = "Alleria;Khadgar"
 money = 10332434612
 gender = 2
 race = "NightElf"
 name = "Elotharion"
 faction = "Alliance"
 rwsKey = "Alleria;Khadgar"
 class = "PRIEST"
 realm = "Khadgar"
}
(*temporary) = 3
(*temporary) = "GetPlayerGuild"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'tracking' (a nil value)"
Unit = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 realmKey = "Alleria;Khadgar"
 name = "BagSync_Unit"
 orderedModules = <table> {
 }
 lowerKey = "alleria;khadgar"
 rwsKey = "Alleria;Khadgar"
 baseName = "BagSync"
 enabledState = true
 defaultModuleState = true
 moduleName = "Unit"
}
BSYC = <table> {
 IsRetail = true
 modules = <table> {
 }
 baseName = "BagSync"
 db = <table> {
 }
 enabledState = true
 FakePetCode = 10000000000
 aboutPanel = Frame {
 }
 IsClassic = false
 defaultModuleLibraries = <table> {
 }
 options = <table> {
 }
 IsWLK_C = false
 name = "BagSync"
 orderedModules = <table> {
 }
 bgsMinimapDD = bgsMinimapDD {
 }
 blizzPanel = Frame {
 }
 timers = <table> {
 }
 defaultModuleState = true
 timerFrame = Frame {
 }
}

**Comment by Xruptor** [comment]
This one MAY be difficult for me to debug as I don't have access to the TWW beta.  In addition it looks like they removed or changed how GetItemClassInfo functions.

What you can do until I can sort it out is just disable that part of the code.

Open LibItemScout-1.0.lua
find 

`[GetItemClassInfo(Enum.ItemClass.Questitem):lower()] = ITEM_BIND_QUEST,`

which is line 480 and replace it with this

`--[GetItemClassInfo(Enum.ItemClass.Questitem):lower()] = ITEM_BIND_QUEST,`
