### ISSUE TITLE
Unsure where to put this but thank you.

### ISSUE THREAD

**Issue by Swarfimus** [Xruptor/BagSync#339]
Hi, I discovered this addon when looking for something new after the addon I usually rely on no longer works.  BagSync fits my needs perfectly of showing me mouseover tooltips on items in my bags to show me how many I have in my bank.  I just wanted to say thanks.  Wasn't sure where to put this so tossed it in here, thnx again

**Comment by Xruptor** [comment]
Aww thank you, it's really appreciated!!  I'm glad the addon is working for you and suits your needs.  If you ever find any bugs or have suggestions please let me know!  Happy gaming 😄
