### ISSUE TITLE
11.0 GetMouseFocus Lua Error

### ISSUE THREAD

**Issue by sudoalias** [Xruptor/BagSync#340]
When running /bgs gold or /bgs currency it throws an error for the associated module.

1x BagSync/modules/gold.lua:200: attempt to call global 'GetMouseFocus' (a nil value)
[string "@BagSync/modules/gold.lua"]:200: in function `RefreshList'
[string "@BagSync/modules/gold.lua"]:75: in function `OnShow'
[string "@BagSync/modules/gold.lua"]:38: in function <BagSync/modules/gold.lua:38>
[string "=[C]"]: in function `Show'
[string "@BagSync/wireframe/data.lua"]:280: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5440: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5092: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5091>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5128: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
self = <table> {
 goldList = <table> {
 }
 frame = Frame {
 }
 baseName = "BagSync"
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 scrollFrame = ScrollFrame {
 }
 enabledState = true
 moduleName = "Gold"
 defaultModuleState = true
 name = "BagSync_Gold"
 orderedModules = <table> {
 }
}
items = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
}
buttons = <table> {
 1 = Button {
 }
 2 = Button {
 }
 3 = Button {
 }
 4 = Button {
 }
 5 = Button {
 }
 6 = Button {
 }
 7 = Button {
 }
 8 = Button {
 }
 9 = Button {
 }
 10 = Button {
 }
 11 = Button {
 }
 12 = Button {
 }
 13 = Button {
 }
 14 = Button {
 }
 15 = Button {
 }
 16 = Button {
 }
 17 = Button {
 }
 18 = Button {
 }
 19 = Button {
 }
 20 = Button {
 }
 21 = Button {
 }
}
offset = 0
(for index) = 1
(for limit) = 21
(for step) = 1
buttonIndex = 1
button = Button {
 Text2 = FontString {
 }
 Highlight = Texture {
 }
 parentHandler = <table> {
 }
 Text = FontString {
 }
 data = <table> {
 }
 HeaderHighlight = Texture {
 }
 DetailsHighlight = Texture {
 }
 Background = Texture {
 }
}
itemIndex = 1
item = <table> {
 unitObj = <table> {
 }
 count = 2239920
 sortIndex = 1
 colorized = "|TInterface\FriendsFrame\PlusManz-Horde:13:13|t |A:raceicon-orc-male:13:13:0:0|a |cfffff468Sudob|r"
 moneyString = "223|TInterface\MoneyFrame\UI-GoldIcon:0:0:2:0|t"
}
(*temporary) = nil
(*temporary) = "attempt to call global 'GetMouseFocus' (a nil value)"
Gold = <table> {
 goldList = <table> {
 }
 frame = Frame {
 }
 baseName = "BagSync"
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 scrollFrame = ScrollFrame {
 }
 enabledState = true
 moduleName = "Gold"
 defaultModuleState = true
 name = "BagSync_Gold"
 orderedModules = <table> {
 }
}

1x BagSync/modules/currency.lua:168: attempt to call global 'GetMouseFocus' (a nil value)
[string "@BagSync/modules/currency.lua"]:168: in function `RefreshList'
[string "@BagSync/modules/currency.lua"]:66: in function `OnShow'
[string "@BagSync/modules/currency.lua"]:38: in function <BagSync/modules/currency.lua:38>
[string "=[C]"]: in function `Show'
[string "@BagSync/wireframe/data.lua"]:283: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5440: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5092: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5091>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5128: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
self = <table> {
 frame = Frame {
 }
 baseName = "BagSync"
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 scrollFrame = ScrollFrame {
 }
 enabledState = true
 currencies = <table> {
 }
 moduleName = "Currency"
 defaultModuleState = true
 name = "BagSync_Currency"
 orderedModules = <table> {
 }
}
items = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 81 = <table> {
 }
 82 = <table> {
 }
 83 = <table> {
 }
 84 = <table> {
 }
 85 = <table> {
 }
 86 = <table> {
 }
 87 = <table> {
 }
}
buttons = <table> {
 1 = Button {
 }
 2 = Button {
 }
 3 = Button {
 }
 4 = Button {
 }
 5 = Button {
 }
 6 = Button {
 }
 7 = Button {
 }
 8 = Button {
 }
 9 = Button {
 }
 10 = Button {
 }
 11 = Button {
 }
 12 = Button {
 }
 13 = Button {
 }
 14 = Button {
 }
 15 = Button {
 }
 16 = Button {
 }
 17 = Button {
 }
 18 = Button {
 }
 19 = Button {
 }
 20 = Button {
 }
 21 = Button {
 }
 22 = Button {
 }
}
offset = 0
(for index) = 1
(for limit) = 22
(for step) = 1
buttonIndex = 1
button = Button {
 Highlight = Texture {
 }
 parentHandler = <table> {
 }
 Text = FontString {
 }
 data = <table> {
 }
 HeaderHighlight = Texture {
 }
 DetailsButton = Button {
 }
 isHeader = true
 Background = Texture {
 }
 Icon = Texture {
 }
 DetailsHighlight = Texture {
 }
}
itemIndex = 1
item = <table> {
 header = "Battle for Azeroth"
 isHeader = true
}
(*temporary) = nil
(*temporary) = "attempt to call global 'GetMouseFocus' (a nil value)"
Currency = <table> {
 frame = Frame {
 }
 baseName = "BagSync"
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 scrollFrame = ScrollFrame {
 }
 enabledState = true
 currencies = <table> {
 }
 moduleName = "Currency"
 defaultModuleState = true
 name = "BagSync_Currency"
 orderedModules = <table> {
 }
}

**Comment by Xruptor** [comment]
Apparently the recent patch as well as the changes the next expansion TWW is causing a lot of bugs.  I'll tackle these one at a time.
