### ISSUE TITLE
Command /bgs gold Not Working

### ISSUE THREAD

**Issue by Zaef** [Xruptor/BagSync#341]
Hello,

I absolutely LOVE this addon. However, I only use it for /bgs gold as far as specific commands beyond the baseline built-in functionality. Since the pre-patch, using that command only shows gold on one specific character (regardless of which one I'm logged into) yet displays the total gold accurately on the bottom.
![BagSync-TWWPrePatch-Bug](https://github.com/user-attachments/assets/83e98c70-860e-4bee-923f-ed098e98da0a)

**Comment by Xruptor** [comment]
It could be tied with another bug that I'm currently working on.  I'll take a look :)

**Comment by Zaef** [comment]
> It could be tied with another bug that I'm currently working on. I'll take a look :)

Awesome! Thank you so much!  :)

**Comment by Xruptor** [comment]
Okay it seems it's tied to an internal error that is occurring with BagSync that is tied to the recent GetMouseFocus changes.  Meaning that an error is being triggered and it's preventing the addon from working correctly in other parts of it.  :)  You probably have "show errors" off.

I recommend the following if you don't have them.

https://www.curseforge.com/wow/addons/bugsack
https://www.curseforge.com/wow/addons/bug-grabber

Anyways!  LOL... it should definitely be fixed in the next push.  If for SOME reason it still doesn't work.  Please feel free to place another ticket here and I will work with you to get it fixed! 😃 💚

**Comment by Zaef** [comment]
> Okay it seems it's tied to an internal error that is occurring with BagSync that is tied to the recent GetMouseFocus changes. Meaning that an error is being triggered and it's preventing the addon from working correctly in other parts of it. :) You probably have "show errors" off.
> 
> I recommend the following if you don't have them.
> 
> https://www.curseforge.com/wow/addons/bugsack https://www.curseforge.com/wow/addons/bug-grabber
> 
> Anyways! LOL... it should definitely be fixed in the next push. If for SOME reason it still doesn't work. Please feel free to place another ticket here and I will work with you to get it fixed! 😃 💚
> 
> I'll be pushing the updates soon for all my addons. :)

Thanks for the update/feedback. Do you know (approximately) when you expect to have a new release/version out?

**Comment by Xruptor** [comment]
> > Okay it seems it's tied to an internal error that is occurring with BagSync that is tied to the recent GetMouseFocus changes. Meaning that an error is being triggered and it's preventing the addon from working correctly in other parts of it. :) You probably have "show errors" off.
> > I recommend the following if you don't have them.
> > https://www.curseforge.com/wow/addons/bugsack https://www.curseforge.com/wow/addons/bug-grabber
> > Anyways! LOL... it should definitely be fixed in the next push. If for SOME reason it still doesn't work. Please feel free to place another ticket here and I will work with you to get it fixed! 😃 💚
> > I'll be pushing the updates soon for all my addons. :)
> 
> Thanks for the update/feedback. Do you know (approximately) when you expect to have a new release/version out?

Ooooo in about 5 or 10 minutes LOL....

**Comment by Xruptor** [comment]
Oh btw I should note that Bug-grabber is required for BugSack.

**Comment by Zaef** [comment]
> > > Okay it seems it's tied to an internal error that is occurring with BagSync that is tied to the recent GetMouseFocus changes. Meaning that an error is being triggered and it's preventing the addon from working correctly in other parts of it. :) You probably have "show errors" off.
> > > I recommend the following if you don't have them.
> > > https://www.curseforge.com/wow/addons/bugsack https://www.curseforge.com/wow/addons/bug-grabber
> > > Anyways! LOL... it should definitely be fixed in the next push. If for SOME reason it still doesn't work. Please feel free to place another ticket here and I will work with you to get it fixed! 😃 💚
> > > I'll be pushing the updates soon for all my addons. :)
> > 
> > 
> > Thanks for the update/feedback. Do you know (approximately) when you expect to have a new release/version out?
> 
> Ooooo in about 5 or 10 minutes LOL....

Oh, awesome, haha! I will try it out (the /bgs gold command) as soon as the update goes live. 🤞
