### ISSUE TITLE
TWW -Beta

### ISSUE THREAD

**Issue by nanjuekaien1** [Xruptor/BagSync#342]
Errors are all from TWW Beta

Message: Interface/AddOns/BagSync/wireframe/data.lua:424: attempt to call global 'GetItemInfo' (a nil value)
Time: Sat Jul 27 08:30:03 2024
Count: 1
Stack: Interface/AddOns/BagSync/wireframe/data.lua:424: attempt to call global 'GetItemInfo' (a nil value)
[string "@Interface/AddOns/BagSync/libs/AceAddon-3.0/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/BagSync/libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...ce/AddOns/BagSync/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: self = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
addon = <table> {
 IsRetail = true
 modules = <table> {
 }
 baseName = "BagSync"
 __font = BagSyncExtTT_Font {
 }
 db = <table> {
 }
 enabledState = true
 FakePetCode = 10000000000
 aboutPanel = Frame {
 }
 IsClassic = false
 defaultModuleLibraries = <table> {
 }
 options = <table> {
 }
 IsWLK_C = false
 name = "BagSync"
 orderedModules = <table> {
 }
 __fontFlags = "OUTLINE"
 tracking = <table> {
 }
 blizzPanel = Frame {
 }
 timers = <table> {
 }
 defaultModuleState = true
 colors = <table> {
 }
 timerFrame = Frame {
 }
}
embeds = <table> {
 1 = "AceEvent-3.0"
 2 = "AceConsole-3.0"
}
modules = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
}
(for index) = 5
(for limit) = 18
(for step) = 1
i = 5
AceAddon = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}

Error two:

Message: Interface/AddOns/BagSync/wireframe/tooltip.lua:875: attempt to call global 'GetItemCount' (a nil value) Time: Sat Jul 27 08:30:13 2024 Count: 3 Stack: Interface/AddOns/BagSync/wireframe/tooltip.lua:875: attempt to call global 'GetItemCount' (a nil value) [string "@Interface/AddOns/BagSync/wireframe/tooltip.lua"]:875: in function `TallyUnits' [string "@Interface/AddOns/BagSync/wireframe/tooltip.lua"]:1191: in function <Interface/AddOns/BagSync/wireframe/tooltip.lua:1166> [string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction' [string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56> [string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77> [string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107> [string "=[C]"]: in function `SetAttribute' [string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135> [string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238> [string "=[C]"]: in function `securecallfunction' [string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234> [string "=(tail call)"]: ? [string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/BankFrame.lua"]:918: in function <...AddOns/Blizzard_UIPanels_Game/Mainline/BankFrame.lua:916>

Locals: self = <table> { __lastLink = "[心核隧途之尘]" modules = <table> { } defaultModuleLibraries = <table> { } name = "BagSync_Tooltip" orderedModules = <table> { } __lastTally = <table> { } objTooltip = GameTooltip { } baseName = "BagSync" enabledState = true defaultModuleState = true moduleName = "Tooltip" } objTooltip = GameTooltip { ItemTooltip = Frame { } BottomOverlay = Texture { } NineSlice = Frame { } textLeft1Font = "GameTooltipHeaderText" hasMoney = 1 textRight2Font = "GameTooltipText" TopOverlay = Texture { } TextLeft1 = GameTooltipTextLeft1 { } StatusBar = GameTooltipStatusBar { } numMoneyFrames = 1 supportsDataRefresh = true shownMoneyFrames = 1 processingInfo = <table> { } infoList = <table> { } waitingForData = false __tooltipUpdated = false shoppingTooltips = <table> { } updateTooltipTimer = 0.096000 TextRight1 = GameTooltipTextRight1 { } supportsItemComparison = true textRight1Font = "GameTooltipHeaderText" layoutType = "TooltipDefaultLayout"
 textLeft2Font = "GameTooltipText" TextRight2 = GameTooltipTextRight2 { } TextLeft2 = GameTooltipTextLeft2 { } } link = "222697" source = "OnTooltipSetItem" isBattlePet = nil showQTip = false skipTally = false origLink = "[心核隧途之尘]" shortID = "222697" permIgnore = <table> { 141605 = "Flight Master's Whistle" 6948 = "Hearthstone"
 128353 = "Admiral's Compass" 110560 = "Garrison Hearthstone" 140192 = "Dalaran Hearthstone" } grandTotal = 0 unitList = <table> { } countList = <table> { equip = 0 auction = 0 void = 0 mailbox = 0 } player = <table> { lowerKey = "thesegotoeleven" realmKey = "These Go To Eleven" money = 1038312700 gender = 3 race = "NightElf" name = "Tigervdh" faction = "Alliance" rwsKey = "TheseGoToEleven" class = "DEMONHUNTER" realm = "These Go To Eleven" } guildObj = nil allowList = <table> {
 bag = true auction = true void = true equip = true mailbox = true reagents = true bank = true } advUnitList = nil turnOffCache = false advPlayerChk = false advPlayerGuildChk = false playerObj = <table> { isXRGuild = false name = "Tigervdh" isConnectedRealm = true isGuild = false data = <table> { } realm = "These Go To Eleven

**Comment by nanjuekaien1** [comment]
## Version: 19.42
Lack of warring bank support
![战团3](https://github.com/user-attachments/assets/52406edb-fd9b-42f4-ae77-fd80dfa180df)

**Comment by Xruptor** [comment]
GetItemInfo a nil value?  >.> they must have either changed that function or moved it.  This is really getting tiring with Blizzard every single patch or expansion.

**Comment by Xruptor** [comment]
Try this version and let me know if it works.

[BagSync.zip](https://github.com/user-attachments/files/16399117/BagSync.zip)

**Comment by nanjuekaien1** [comment]
## Interface: 100207, 110000, 110002

**Comment by Xruptor** [comment]
They are up to 110002 already?  TWW isn't even out yet.

**Comment by nanjuekaien1** [comment]
![屏幕截图 2024-07-27 211503](https://github.com/user-attachments/assets/590463a2-2df9-4ead-ae98-0791fe99d9d1)

**Comment by nanjuekaien1** [comment]
It's TWW eve.
![8mQk1u-9k7xZ1xT3cS1hc-u0](https://github.com/user-attachments/assets/a65f92d0-e404-41b2-bb2e-fdc208632848)

**Comment by Xruptor** [comment]
Okay thanks for the heads up.  I'll go ahead and modify the Interface then to the newer format.

**Comment by nanjuekaien1** [comment]
https://www.townlong-yak.com/framexml/beta

This one too.
