### ISSUE TITLE
Update Currency Count on Currency Transfer

### ISSUE THREAD

**Issue by F-Lambda** [Xruptor/BagSync#343]
When transferring currencies from one character to another, the recipient character updates (because it's the one you're on), but the sender character does not. This causes characters to display as having currency amounts they do not have, possibly not even having the currency at all.

If possible, BagSync should update both recipient and sender currency amounts.

**Comment by Xruptor** [comment]
This is an inherent limitation of the system.  I'm assuming you mean sending currency to a character using the Mail system correct and not some sort of trade?

**Comment by F-Lambda** [comment]
No, I mean using the new Currency transfer system added in TWW, from the character window.

![image](https://github.com/user-attachments/assets/48df9ca7-8d5c-4c37-99ca-3e881da8800a)

**Comment by Xruptor** [comment]
> No, I mean using the new Currency transfer system added in TWW, from the character window.
> 
> ![image](https://private-user-images.githubusercontent.com/21232805/353234505-48df9ca7-8d5c-4c37-99ca-3e881da8800a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTQ4OTksIm5iZiI6MTcyMjM1NDU5OSwicGF0aCI6Ii8yMTIzMjgwNS8zNTMyMzQ1MDUtNDhkZjljYTctOGQ1Yy00YzM3LTk5Y2EtM2U4ODFkYTg4MDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE1NDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyOTk4NTFmOTI4MWM0ODliOWZiZDlhNTZlYzI1MjA2ZTdjMTNhMjUxYmZkY2I2YTQxM2E4ZDljNzY2N2JhY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T-w1fi2rU_T3B7jC7Em2moTyoiQfpjutLShkSRrEU-o)

Oh wow.... I didn't even know that was a thing.  Well that is going to be a huge issue for me to deal with I think.  I'll have to look at the code and determine how to properly implement such a fix.  In the meantime the only way to truly keep it accurate is just to login to each toon involved in the transactions (before and after).  This may take some time as I don't have a subscription and I update addons casually.

**Comment by d-schmidt** [comment]
A first simple step would be to show the total for transferable currency. Be aware. not all of them are.

![grafik](https://github.com/user-attachments/assets/b787a20b-eb1c-44a3-aed1-07ecd966bb6c)

**Comment by Sluimerstand** [comment]
The event `CURRENCY_TRANSFER_LOG_UPDATE` can probably be used to track successful currency transfers.
`C_CurrencyInfo.FetchCurrencyDataFromAccountCharacters(currencyID)` then shows all currency for the provided currencyID for every character _except the current one, for some reason_.

There is also `C_CurrencyInfo.IsAccountWideCurrency(currencyID)` to check if the currency is transferrable at all - maybe helpful if you want to treat these differently. (Some are transferrable at 0 loss, some cost a percentage to transfer.)

Most of this isn't documented yet on Warcraft Wiki, but I got the info from [here](https://github.com/Gethe/wow-ui-source/blob/b4c9176d321abca2b959444c0379c5858a02c3af/Interface/AddOns/Blizzard_APIDocumentationGenerated/CurrencyInfoDocumentation.lua).

**Comment by Xruptor** [comment]
> The event `CURRENCY_TRANSFER_LOG_UPDATE` can probably be used to track successful currency transfers. `C_CurrencyInfo.FetchCurrencyDataFromAccountCharacters(currencyID)` then shows all currency for the provided currencyID for every character _except the current one, for some reason_.
> 
> There is also `C_CurrencyInfo.IsAccountWideCurrency(currencyID)` to check if the currency is transferrable at all - maybe helpful if you want to treat these differently. (Some are transferrable at 0 loss, some cost a percentage to transfer.)
> 
> Most of this isn't documented yet on Warcraft Wiki, but I got the info from [here](https://github.com/Gethe/wow-ui-source/blob/b4c9176d321abca2b959444c0379c5858a02c3af/Interface/AddOns/Blizzard_APIDocumentationGenerated/CurrencyInfoDocumentation.lua).

While I was going through the code I did notice the CURRENCY_TRANSFER_LOG_UPDATE but not the functions you mentioned.  This is actually exactly what I need to be able to decipher if a transaction is in progress and to which target it's going to.  I just need to make sure I can pull the category as well.  BagSync stores both the currencyID and it's related category to display properly.  I have a feeling the API doesn't do this during the transaction in any parameters.  So I may have to brute force it.

**Comment by Sluimerstand** [comment]
I'm far from a seasoned addon developer, but I've always gotten tremendous help from the [WoW AddOns discord](https://discord.gg/sXy46yZ). There's a lot of very clever people in there who might be able to help out if you're struggling with anything in particular. A small handful of them are very active and hands-on with new/future API changes, so they may have some insight that could be helpful. :D

**Comment by Xruptor** [comment]
Now that I got Warband Bank implemented, I will be tackling this issue in BagSync.
