### ISSUE TITLE
(Warband) Currencies aren't updated after a transfer between characters

### ISSUE THREAD

**Issue by KatyPurry** [Xruptor/BagSync#345]
Hello,

When you use the currency transfer feature, the amount is not updated on the character until you log on to it.

Feature example : 
https://bnetcmsus-a.akamaihd.net/cms/content_entry_media/I2SA1LIELVXZ1713370376318.png
https://bnetcmsus-a.akamaihd.net/cms/content_entry_media/GC4TZ5AG0BJZ1713370376309.png

https://worldofwarcraft.blizzard.com/en-us/news/24061008/the-war-within-warbands-preview

**Comment by F-Lambda** [comment]
Dupe of #343
