### ISSUE TITLE
This after new update

### ISSUE THREAD

**Issue by Bap455** [Xruptor/BagSync#348]
Keep getting this when I open a bag or mail,

ssage: Interface/AddOns/BagSync/wireframe/events.lua:32: attempt to call method 'StartTimer' (a nil value)
Time: Fri Aug  9 11:44:02 2024
Count: 65
Stack: Interface/AddOns/BagSync/wireframe/events.lua:32: attempt to call method 'StartTimer' (a nil value)

**Comment by Amatyr** [comment]
Errors all over the place in Cata with new update, even trying to look at Bagsync options.

**Comment by Xruptor** [comment]
That shouldn't be happening.  I'll take a look as I had tested it myself and it worked.  It must be something I may have missed?

**Comment by Bap455** [comment]
ty for the fix
