### ISSUE TITLE
lua error: BagSync\BagSync-v8.7.lua:1128: bad argument #1 to 'pairs' (table expected, got no value)

### ISSUE THREAD

**Issue by doneykoo** [Xruptor/BagSync#35]
A lua error occurs when I login and enter game world, with latest BagSync 8.7

lua error detail:
> 
> 3x BagSync\BagSync-v8.7.lua:1128: bad argument #1 to 'pairs' (table expected, got no value)
> [C]: in function `pairs'
> BagSync\BagSync-v8.7.lua:1128: in function `?'
> BagSync\BagSync-v8.7.lua:94: in function <BagSync\BagSync.lua:92>
> 
> Locals:
> (*temporary) = "table expected, got no value"
>  = <function> defined =[C]:-1
> 

Other info:
server region: Chinese
game ver: 7.0.3
character: a lv.100 paladin

**Comment by Xruptor** [comment]
It was an issue with GetAutoCompleteRealms().  It doesn't return the default currentRealm for some reason and therefore defaults to nil.  A patch is already on it's way in a few minutes.
