### ISSUE TITLE
freez when riding race quest start and complete

### ISSUE THREAD

**Issue by Darksky1991** [Xruptor/BagSync#350]
as title described, when i start and complete a riding race world quest, the whole graphic freeze 1-2s for start, and 5-10s for complete. and i checked that when only BagSync loaded, it's not changed. obviously it should be the BaySync's problem i think.

**Comment by Darksky1991** [comment]
i don't know why, maybe not only bagsync, i find that elvui and altoholic has same situation.

**Comment by nanjuekaien1** [comment]
Delete WTF BagSync.lua and BagSync.lua.bak.

**Comment by Darksky1991** [comment]
i have tried to delete all the WTF, Interface, Cache, Logs, Fonts folders and repaired the game and reset all the setting in game, then just installed the bagsync, but no effect

**Comment by Xruptor** [comment]
If other addons are causing the issue it may be something else entirely.  What happens when you have NO addons loaded at all?  Does the issue still occur?

**Comment by Xruptor** [comment]
In addition you stated that even with BagSync disabled the issue still happens.  So technically this isn't a BagSync bug.  The only thing I can recommend is disabling all addons and enabling them one at a time to see which is causing the problem.  Otherwise it may be something with your game client, graphics drivers or something PC related.

**Comment by Darksky1991** [comment]
as i commented previously,
- no addons loaded, no problem
- only Bagsync or Elvui or Altoholic one addon loaded, it happened
- only DBM, Details something others loaded, no problem
------------------------
then i deleted all the WTF, Interface, Cache, Logs, Fonts folders and did repair game operation, and reseted all the setting in game
- no addons loaded, no problem
- only Bagsync or Elvui one addon loaded, freez hanpped(altoholic not checked this time)
- only NDui loaded, no problem

**Comment by Darksky1991** [comment]
> In addition you stated that even with BagSync disabled the issue still happens with other addons (ElviUI and Altoholic). So technically this isn't a BagSync bug. The only thing I can recommend is disabling all addons and enabling them one at a time to see which is causing the problem. Otherwise it may be something with your game client, graphics drivers or something PC related.

maybe some lib goes weird?

**Comment by nanjuekaien1** [comment]
This happened to me on Mar 14, 2024 when I was also using NDui, then I deleted the WTF BagSync.lua and BagSync.lua.bak from WTF and I have not had any problems since.

**Comment by Darksky1991** [comment]
> This happened to me on Mar 14, 2024 when I was also using NDui, then I deleted the WTF BagSync.lua and BagSync.lua.bak from WTF and I have not had any problems since.

thank you. I just tried again, no improve.
but I found a nothing thing, when I just checked the Currency module, freez will happen. Others are OK.

**Comment by Xruptor** [comment]
> > In addition you stated that even with BagSync disabled the issue still happens with other addons (ElviUI and Altoholic). So technically this isn't a BagSync bug. The only thing I can recommend is disabling all addons and enabling them one at a time to see which is causing the problem. Otherwise it may be something with your game client, graphics drivers or something PC related.
> 
> maybe some lib goes weird?

It's possible that it could be a library that all of the addons share.  I'm not exactly sure as I'd have to do a comparison.  



> > This happened to me on Mar 14, 2024 when I was also using NDui, then I deleted the WTF BagSync.lua and BagSync.lua.bak from WTF and I have not had any problems since.
> 
> thank you. I just tried again, no improve. but I found anothing thing, when I just checked the Currency module, freez will happen. Others are OK. just uncheck the currency module for the moment

This doesn't explain why it happens with the other addons though.  Perhaps its an issue associated with currency as the other addons also do handle stuff with currency.  Have you tried unchecking everything and ONLY keeping Currency enabled?  Does the issue still happen?

I'll review the code but it's somewhat hard to fix if I can't reproduce the issue myself.  Lets do some investigation work :)

**Comment by Darksky1991** [comment]
> Have you tried unchecking everything and ONLY keeping Currency enabled? Does the issue still happen?
yes, I have compared only currency be checked and non checked.
I attached the BagSync's debug log below, but it looks goes well.
[race-complete-ng-currency-nocache.txt](https://github.com/user-attachments/files/16570341/complete-ng-currency-nocache.txt)
[race-complete-ok-nocurrency-nocache.txt](https://github.com/user-attachments/files/16570342/complete-ok-nocurrency-nocache.txt)
[race-start-ng-currency-nocache.txt](https://github.com/user-attachments/files/16570343/start-ng-currency-nocache.txt)
[race-start-ok-nocurrency-nocache.txt](https://github.com/user-attachments/files/16570344/start-ok-nocurrency-nocache.txt)

And, internal event trace log as below
the NG case have a event spent 3-4s, but it's not constant, some time PLAYER_STOPPED_TURNING event, some time SPELL_ACTIVATION_OVERLAY_HIDE event.
race complete NG
![complete-ng-onlycurrency](https://github.com/user-attachments/assets/9dabbaf9-1758-4bdb-83c6-323741ba75dd)

race complete  OK
![complete-ok-noaddon](https://github.com/user-attachments/assets/8d9374cd-85c3-404c-bdc1-e66cb32261a4)

**Comment by Xruptor** [comment]
WOW..... CURRENCY_DISPLAY_UPDATE is being spammed by blizzards servers!  No wonder you are getting lag.  I mean look at how much within the same second.  That's insanity...  That has to be the issue as your currencies are being scanned by all the addons each time.

**Comment by Xruptor** [comment]
Out of curiosity, try this version of BagSync.  Let me know if that stops the issue?  All I did was add a spam protection buffer for CURRENCY_DISPLAY_UPDATE.

[BagSync.zip](https://github.com/user-attachments/files/16570408/BagSync.zip)

**Comment by Darksky1991** [comment]
> Out of curiosity, try this version of BagSync. Let me know if that stops the issue? All I did was add a spam protection buffer for CURRENCY_DISPLAY_UPDATE.

it was fixed!! You're so greateful^_^
Maybe China's server just back not for long and not stable, and should be fixed in the future.

**Comment by Xruptor** [comment]
> > Out of curiosity, try this version of BagSync. Let me know if that stops the issue? All I did was add a spam protection buffer for CURRENCY_DISPLAY_UPDATE.
> 
> it was fixed!! You're so greateful^_^ Maybe China's server just back not for long and not stable, and should be fixed in the future.

It definitely has to be the server as nobody else has mentioned this issue.  The only thing I can assume is that it's a bug on their end for spamming CURRENCY_DISPLAY_UPDATE that much.  I'll just add the spam check for everyone in case this happens again.
