### ISSUE TITLE
Warbank count is not updated (when using Convergence)

### ISSUE THREAD

**Issue by d-schmidt** [Xruptor/BagSync#355]
I'm not sure what the problem is, but the item count is not reduced when I take items out of the warbank:
![grafik](https://github.com/user-attachments/assets/ae1cc115-1fc0-4bdf-ab44-19d5d4d54d86)

It still say "Warban**d**" one but I took it from the warban**k** and equipped it.

**Comment by Xruptor** [comment]
Please use this version and let me know if the issue still occurs.

[BagSync.zip](https://github.com/user-attachments/files/16607088/BagSync.zip)

**Comment by Xruptor** [comment]
> fix seems to work, can't reproduce it anymore.
> 
> I just noticed, broken items (0/20 durability) don't count anywhere. They don't show up and don't have a tooltip themselves.

Please type `/bgs debug`
Turn it on.
Then check INFO, TRACE and FINE.

Clear the window then hover over the broken item.  Please copy that here for me to see.  Thanks!  Don't forget to turn off debug when you are done.

**Comment by Xruptor** [comment]
Never mind!  I see what the issue is.
