### ISSUE TITLE
[Bug] Error When Opening Guild Bank

### ISSUE THREAD

**Issue by F-Lambda** [Xruptor/BagSync#356]
Seems 11.0.2 made more API changes, getting the following error now when opening the guild bank. Tooltip breaks after it as well.

```
Message: Interface/AddOns/BagSync/wireframe/scanner.lua:318: attempt to call field 'SurfaceArgs' (a nil value)
Time: Tue Aug 13 16:51:24 2024
Count: 1
Stack: Interface/AddOns/BagSync/wireframe/scanner.lua:318: attempt to call field 'SurfaceArgs' (a nil value)
[string "=[C]"]: in function `SurfaceArgs'
[string "@Interface/AddOns/BagSync/wireframe/scanner.lua"]:318: in function <Interface/AddOns/BagSync/wireframe/scanner.lua:301>
[string "@Interface/AddOns/BagSync/wireframe/scanner.lua"]:382: in function `SaveGuildBank'
[string "@Interface/AddOns/BagSync/wireframe/events.lua"]:257: in function `?'
[string "@Interface/AddOns/BagSync/core.lua"]:566: in function <Interface/AddOns/BagSync/core.lua:556>

Locals: 
```

**Comment by Xruptor** [comment]
Please use this version and let me know if the issue still occurs.

[BagSync.zip](https://github.com/user-attachments/files/16607077/BagSync.zip)

**Comment by F-Lambda** [comment]
Yeah, this version works with no LUA errors!

**Comment by Xruptor** [comment]
Okay great :)  I'll go ahead and commit these once I fix the other bugs.

**Comment by d-schmidt** [comment]
I also got 
Message: Interface/AddOns/BagSync/wireframe/tooltip.lua:611: attempt to call field 'IsAddOnLoaded' (a nil value)
just now

**Comment by Sluimerstand** [comment]
Yeah that moved to C_AddOns.IsAddOnLoaded
