### ISSUE TITLE
No longer totals across all servers

### ISSUE THREAD

**Issue by bubfeeld** [Xruptor/BagSync#357]
Prior to 11.02 i would get a total of an item across all servers, now it seems to be  just the same server totals.

**Comment by bubfeeld** [comment]
it used to tally across all servers, whether they were connected or not, i may not be understanding,lol

**Comment by bubfeeld** [comment]
Ok, on my Remix toon, im seeing the same behavior as my OG issue here, it only totals current server totals on the currency tab.

**Comment by Xruptor** [comment]
Okay so the item counts across servers is fixed.  The issue you are referring to now is the currencies?  I'm a little confused.  Can you show screenshots or something?

**Comment by bubfeeld** [comment]
> Okay so the item counts across servers is fixed. The issue you are referring to now is the currencies? I'm a little confused. Can you show screenshots or something?

yah ill try and get a SS to you, but yah , the currencies that you physically have in your inventory total across servers just fine, but the ones listed on the currency tab that are NOT physical dont total at all
![Scan_0012](https://github.com/user-attachments/assets/e89dd7fa-f882-4f3f-913c-753ba3e5100d)

**Comment by Xruptor** [comment]
OOOOOOOHH you just want a [Total] on the Currency tooltip? Is that it?

**Comment by bubfeeld** [comment]
> OOOOOOOHH you just want a [Total] on the Currency tooltip? Is that it?

yah, it was nice to see, bagbrother used to do it, Althohlic too, but for some reason they stopped, then i found your addon, and it was all i wanted:O)

Having a total across all toons across all servers made it so much easier to see how many Pet charms i had to buy stuff with was great!

**Comment by bubfeeld** [comment]
> OOOOOOOHH you just want a [Total] on the Currency tooltip? Is that it?

yah pretty much:O)
