### ISSUE TITLE
Bug? Feature request? Remember minimap button location

### ISSUE THREAD

**Issue by Protuhj** [Xruptor/BagSync#373]
1. Move the minimap button to the other side  
2. Log out correctly
3. Log in
4. Minimap button is back where it was

**Comment by Xruptor** [comment]
That's REALLY odd.  It was working awhile back when I tested it.  Perhaps they changed something in the code.  Let me look.

**Comment by Xruptor** [comment]
I can't for the love of me replicate this.  Have you tried only loading BagSync and disabling all other addons?

I recommend you install these two addons.  They require each other to function and is useful for tracking bugs.

https://www.curseforge.com/wow/addons/bugsack
https://www.curseforge.com/wow/addons/bug-grabber

**Comment by Protuhj** [comment]
Yeah, not sure what happened. I removed my addon saved variables and it's saving now. 

Something on my system.

**Comment by Protuhj** [comment]
So I used some of BagSync's code to implement an inventory-sharing addon to help a friend play the game, and it was overwriting the full addon's settings. 

That one's on me. Sorry!
