### ISSUE TITLE
Characters with the same name on different servers cannot display item statistics correctly.

### ISSUE THREAD

**Issue by githubc** [Xruptor/BagSync#375]
When I have multiple characters with the same name across different servers, such as a character named John on servers A, B, C, and D, it seems that bagsync is unable to properly display item statistics for these characters.

**Comment by Xruptor** [comment]
That's odd it should be working.  Does ANY of your characters with the same name show up?

**Comment by githubc** [comment]
You are correct, sorry for the confusion, this issue has nothing to do with the character names.
I have resolved the issue: I checked the option "Show all [Battle.net account] information. [BNet] (not recommended)".
All my accounts are under the same Battle.net ID and the same WoW4, and I'm not sure why this option needs to be checked to display normally.
Also, when displayed, the prefix will have [BNet] attached.
By the way, my server is from China; I'm not sure if it has anything to do with the region.

**Comment by nanjuekaien1** [comment]
[BNet]是你战网下角色信息的统计。
[CR]是合并服务器内角色信息的统计。
我在本地化上做了说明

**Comment by Xruptor** [comment]
Characters can't normally share items across servers unless they are connected.  [https://wowpedia.fandom.com/wiki/Connected_Realms](https://wowpedia.fandom.com/wiki/Connected_Realms)  This is especially true on Classic or progression server.  Generally speaking, only connected realms can trade and send items to each other.   So displaying items from characters outside of connected realms really serves no real purpose.

That is why the option to display ALL character information across the Battle.net account (regardless if they are on a connected realm) is turned off.  By default only characters on connected realms will be displayed.
