### ISSUE TITLE
 BagSync attempted to call a protected function (<unnamed>:Hide()) during combat lockdown.

### ISSUE THREAD

**Issue by cyber21tan** [Xruptor/BagSync#38]
Date: 2016-08-11 13:04:09
ID: 2
Error occured in: AddOn: BagSync
Count: 2
Message: Note: AddOn BagSync attempted to call a protected function (<unnamed>:Hide()) during combat lockdown.
Debug:
   [C]: Hide()
   ..\FrameXML\WorldMapActionButton.lua:58: Clear()
   ..\FrameXML\WorldMapActionButton.lua:67: Refresh()
   ..\FrameXML\WorldMapActionButton.lua:19: SetMapAreaID()
   ..\FrameXML\WorldMapFrame.lua:390:
      ..\FrameXML\WorldMapFrame.lua:353
   [C]: ?
   [C]: Hide()
   ..\FrameXML\UIParent.lua:2320: SetUIPanel()
   ..\FrameXML\UIParent.lua:2347: MoveUIPanel()
   ..\FrameXML\UIParent.lua:2378: HideUIPanel()
   ..\FrameXML\UIParent.lua:2052:
      ..\FrameXML\UIParent.lua:2044
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:2846: HideUIPanel()
   ..\FrameXML\UIParent.lua:2812: ToggleFrame()
   ..\FrameXML\WorldMapFrame.lua:219: ToggleWorldMap()
   [string "TOGGLEWORLDMAP"]:1:
      [string "TOGGLEWORLDMAP"]:1
Locals:
None
AddOns:
  Swatter, v5.21f.5579 (SanctimoniousSwamprat)
  WowheadLooter, v60014
  Accountant, v6.02.60200
  ACP, v3.4.28 
  AFKfullscreen, v2.0-Release
  AutoVendor, v31
  BadBoy, v13.025
  BadBoyCCleaner, v
  BadBoyGuilded, v
  BagSync, v9.1
  Bazooka, vv2.7.1
  BazookaOptions, vv2.7.1
  BetterTooltips, vv2.3.1
  Blitz, v6.0
  BlitzOptions, v
  BrokerEverything, v2.16-Release8
  ClassIcons, v7.2
  DBMArchaeology, v
  DBMCore, v
  DBMDefaultSkin, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DBMVoA, v
  DebugLib, v5.1.DEV.337(/embedded)
  ExplorerCoords, v1.5.2
  FactionAddict, v1.34
  HandyNotes, vv1.4.8
  HandyNotesDirections, v1
  HandyNotesEverShiftingMirror, v1.0.1
  HandyNotesHigherLearning, v6.2.0.4
  HandyNotesLostAndFound, v1
  HandyNotesTreasureHunter, v1
  HandyNotesWellRead, v6.1.0.4
  HandyNotesWorldMapButton, v2.4
  ImprovedOptionsFrames, v1.5.5
  InspectorGadgetzan, v7.0.3.7
  InstanceProfits, v
  LagBar, v3.5
  LeatrixPlus, v7.0.48
  LibExtraTip, v5.12.DEV.390(/embedded)
  LibSharedMedia30, v3.0-93
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.146
  MinimapButtonFrame, v3.1.10e
  MinimapButtonFrameSkinPack, v3.0.1b
  mOnArsWardrobeHelper, v1.13.9
  Overachiever, v0.84
  OverachieverTabs, v0.84
  PassLoot, v4.3
  Pawn, v2.0.7
  Postal, vv3.5.8
  Prat30, v3.6.14      
  Prat30Libraries, v
  RaresTip, vr10
  SavedInstances, v7.0.1
  SignOn, vv2.4.2
  SilverDragon, vv3.2.5
  SimpleGold, v5.5.0
  SlashHelp, v4.2
  Stubby, v5.21f.5579 (SanctimoniousSwamprat)
  TipTac, v16.07.23
  TomTom, vv70000-1.0.0
  TradeSkillInfo, vv2.3.11
  TradeSkillInfoUI, vv2.3.11
  TradeSkillMaster, vv3.4.29
  TradeSkillMasterAccounting, vv3.0.16
  TradeSkillMasterAppHelper, vv3.0.1
  TradeSkillMasterAuctionDB, vv3.1.12
  TradeSkillMasterAuctioning, vv3.0.12
  TradeSkillMasterMailing, vv3.0.11
  WoWTokenWatch, v1.0.3
  XToLevel, v7.0.3_46
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=773)

**Comment by Xruptor** [comment]
Doesn't really give me much to go on.  No line number or even a general idea of where it got triggered.  OnHide() function is only called really on the major BagSync frames like Search Window, Tokens Window, etc..  What where you doing that caused this to happen?  Where you using one of these functions when you went into combat or got into combat?  Where you reviewing and item or something?  It can't be the tooltips it has to be the major windows that are part of BagSync.  Please provide a bit more details thanks.

**Comment by cyber21tan** [comment]
Will try to replicate this again. I was fighting one of the bosses in Vault of Archavon on my Mage will check asap on my druid

**Comment by Xruptor** [comment]
Thank you so much Cyber, I truly appreciate it!  Normally I would have addressed the issue but since the error report is so generic, I wouldn't even know where to begin.

**Comment by cyber21tan** [comment]
Just finished testing on 6 other characters...wasn't able to recreate the bug. thanks for the speedy response time sorry for wasting your time

**Comment by Xruptor** [comment]
You didn't waste my time.  It's a shame you weren't able to reproduce the bug.  It may have been a fluke that it happened.  Like I mentioned before, the Hide() function only really applies to major BagSync window frames.  So the only thing I can think of is that one of them was opened when you went into combat or some such and that triggered the CombatLockDown().  The other possible explanation which does happen, is that another addon triggered the error but BagSync got blamed for the error.
