### ISSUE TITLE
Lua error opening bank after upgrade to 19.52

### ISSUE THREAD

**Issue by b-morgan** [Xruptor/BagSync#383]
I upgraded BagSync to 19.52 and when opening the bank on my first login, I got the following Lua error:
```
3x BagSync/wireframe/tooltip.lua:508: bad argument #1 to 'sort' (table expected, got nil)
[string "=[C]"]: in function `sort'
[string "@BagSync/wireframe/tooltip.lua"]:508: in function `UnitTotals'
[string "@BagSync/wireframe/tooltip.lua"]:1005: in function `TallyUnits'
[string "@BagSync/wireframe/tooltip.lua"]:1328: in function <BagSync/wireframe/tooltip.lua:1303>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1553: in function `OnUpdate'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1512: in function `OnEnter'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1508: in function <...s/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua:1507>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
```

**Comment by b-morgan** [comment]
With further testing, it doesn't appear to have anything to do with the Bank (or Warband Bank) but rather mousing over items in my character's reagent bag that are also in my Warband Bank. I am using Baganator for my bag addon.

**Comment by Xruptor** [comment]
Definitely a bug.  I forgot that the tab data needs to be updated since it's no longer being pulled from the cache.  This was a mistake on my part as I completely forgot about that portion of the code.  If you disable the option to see Warband tabs, it should fix it temporarily as I work to patch it.

**Comment by b-morgan** [comment]
Will 19.51 work until you get a patch out?

**Comment by Xruptor** [comment]
I'm working on it right now actually.  Should be out real soon.

**Comment by b-morgan** [comment]
OK, I'll wait (and quit bugging you) :-)

**Comment by Xruptor** [comment]
You're not bugging me at all, in fact I'm actually glad you put a bug report in.

**Comment by Xruptor** [comment]
I fixed it and I'm uploading it now.  :)  💚

**Comment by b-morgan** [comment]
As a fellow addon developer (Skillet, Skillet-Classic), I understand the value of good issue reporting. What I meant by bugging you was continuing to ask questions in this issue while you were working on the solution!

Thank you for your prompt resolution! I was working of consolidating fish from multiple toons into the warband bank. I'll turn the option back on now.
