### ISSUE TITLE
(Question) Disable golds in bank in the gold window ?

### ISSUE THREAD

**Issue by KatyPurry** [Xruptor/BagSync#385]
Hello,

Is it possible to disable the gold in bank in the Gold window (/bgs gold) ? 

Thank you

**Comment by Xruptor** [comment]
Which bank?  Guild or regular bank?

**Comment by Xruptor** [comment]
There is an option in  BagSync to add or remove the Guild Bank totals in the BagSync Gold Window.

"Display [Guild] gold totals in the Gold Window."

**Comment by Zazou89** [comment]
Thank you for your answer but the option is grayed. I can't uncheck.

**Comment by KatyPurry** [comment]
Thank you for your answer but the option is grayed. I can't uncheck.

**Comment by Xruptor** [comment]
If you are seeing it and it's grayed out, then that's definitely a bug.  I'll fix it :)
