### ISSUE TITLE
Transferable currencies

### ISSUE THREAD

**Issue by GreyFoxGer** [Xruptor/BagSync#389]
After i transferred all time walking badges from BN character alt, it wont update. Still showing the same number until i log on to that character. Any fix possible?

**Comment by Xruptor** [comment]
There was a minor update I put in for GUID checks between transfers.  So long as those are matched it should update properly.

I haven't heard back from the original ticket owner in over two weeks, I'm guessing it was resolved.  Closing the ticket.
