### ISSUE TITLE
CrossRealm not always showing

### ISSUE THREAD

**Issue by aastarius** [Xruptor/BagSync#39]
As requested here is a copy of my BagSync.lua.

Characters on Bronze Dragonflight see counts from Nordrassil.

Nordrassil characters do not see counts from Bronze Dragonflight
[BagSync.zip](https://github.com/Xruptor/BagSync/files/427482/BagSync.zip)

**Comment by Xruptor** [comment]
Thanks!  I'll take a look and see if I can reproduce the issue.  It's probably something very silly.  Could you provide me an item you know will not work properly in your situation?  Otherwise I will have to track down an item LOL.  I will use some random ones until you reply ;)

**Comment by aastarius** [comment]
Easy one is: Fleet Commander's Hat

Most of my characters have one

**Comment by Xruptor** [comment]
Alrighty gonna take a look at this today hopefully I can reproduce the error.  I should note though, the servers you mentioned are EU servers and I only have access to US servers.  So it makes this a little more complicated in terms of reproducing the issue.  That being said I've gone ahead and replaced the servers in question with US ones that have a space in between.  (Borean Tundra and Shadowsong).  I'm hoping that this will allow me to reproduce the issue you are having.  If not this may be more problematic for me to resolve then I initially realized.

**Comment by Xruptor** [comment]
Okay there was an issue with whitespace in the server names that was leading to this issue.  I've made the appropriate changes to resolve this issue.  Unfortunately, characters on realms that were affected have to be re-scanned as I've deleted the old realm names from the DB.  From now on we will use the stripped down names that Blizzard uses for its code.  I've saved the original realm name only for display purposes like the tooltip.  Hopefully this should resolve the issue you were having.  Thanks for pointing this out!

**Comment by aastarius** [comment]
Many thanks for maintaining the addon, truly appreciated :)

**Comment by Xruptor** [comment]
Okay I've gone ahead and updated the code.  It's not released yet, but its working perfectly.  I'm taking the time to add some more stuff I've had on the back burner.

https://github.com/Xruptor/BagSync/commit/ec515b06f20d9a08eb629b45f793c17bede9dc0c
