### ISSUE TITLE
Feature request: make BagSync display gold tooltip when gold in bag is mouseovered

### ISSUE THREAD

**Issue by gutko** [Xruptor/BagSync#42]
Id like to ask to make it possible to automatically display gold tooltip (content of /bgs gold) when I mouseover gold amount in bag - same way as it works in bagnon
Thank you

**Comment by Xruptor** [comment]
Working on it now.  Looks like the different bag addons treat the gold display differently.  Will try to do a global hook and see what happens.  Hopefully it works and I can use that on several bag addons.

**Comment by Xruptor** [comment]
Its just as I feared, some addons are using their own custom displays for gold.  I will see if I can do as much of a generic grab as I can.  However, if I'm not satisfied this will work on whole heap of bag addons then I may disregard this request :(  I honestly don't want to add custom support for addons in BagSync.  This is tedious and requires I constantly update it if they make changes on their addon.

Will keep you posted on what I find.

**Comment by gutko** [comment]
Too bad, thank you for trying and investigating this.

**Comment by Xruptor** [comment]
Alright after some tests, it just doesn't seem feasible enough for me to implement this.  It causes all sorts of display issues depending on the bag addon used.  If the default UI is used then it throws this tooltip on the bottom right of the screen every time you hover the gold, which I find a bit annoying.  I will look into this in the future, but for right now it doesn't seem like I'm going to go ahead with this.  Thanks for the suggestion!

BTW You can view the gold tooltip at anytime by assigning a hotkey to it.  You can also right click the minimap icon if you have that enabled.  Finally, if you have some sort of databroker bar addon installed, it should put a BagSync green bag icon.  You can click on this to view the gold tooltip as well.  If you can come up with another clever way to display the gold tooltip, let me know!
