### ISSUE TITLE
BagSync\modules\search-Search.lua:7: Cannot find a library instance of "CustomSearch-1.0"

### ISSUE THREAD

**Issue by gutko** [Xruptor/BagSync#43]
just got this message when logged my char 1st time after upgrade from previous version

1x BagSync\modules\search-Search.lua:7: Cannot find a library instance of "CustomSearch-1.0".
[C]: in function `error'
GatherMate2\Libs\LibStub\LibStub.lua:23: in function `LibStub'
BagSync\modules\search-Search.lua:7: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "CustomSearch-1.0"."

**Comment by Xruptor** [comment]
It looks like WOWInterface didn't properly prepare the zip file like it should have.  I will reupload it there.
