### ISSUE TITLE
Cross realms not working

### ISSUE THREAD

**Issue by Homaxz** [Xruptor/BagSync#46]
Main realm: Ulduar-EU (This server is connected with Gilneas-EU)
Connect realm: Gilneas-EU (works here) http://i.imgur.com/VgdpC6c.jpg
Aegwynn-EU (no relation to Ulduar-EU or Gilneas-EU) http://i.imgur.com/ogIA9Gw.jpg
Blackrock-EU (Horde, no relation to relams above) http://i.imgur.com/4cEprRY.jpg

Suggestion: add all realms (maybe option if people don't want this?), show them as XR-Realm, and use CR-Realm for connected realms.

**Comment by Xruptor** [comment]
Make sure you have same faction enabled.  It will not show information for cross factions unless the option is enabled.  Let me know if that fixes your issue.

**Comment by Homaxz** [comment]
This worked, I've interpreted the option wrong. I thought "Battle.Net account characters" would count different actual instances of WoW of the Battle.net Account (WoW1, WoW2, etc...). (hence the "not recommended" warning.)

Thanks for the assistance.
