### ISSUE TITLE
Feature Request: little check mark next to character

### ISSUE THREAD

**Issue by Homaxz** [Xruptor/BagSync#47]
Currently it's a little overwhelming to see which character I'm on. http://i.imgur.com/P1ppaCk.jpg
ElvUI handels this quite nicely, as shown in the bottom right here: http://i.imgur.com/rWmvd8Z.jpg

**Comment by Xruptor** [comment]
This is a great suggestion.  I'll add it in next patch.

**Comment by Xruptor** [comment]
Okay I released it today in version 10.2.  Enjoy.

**Comment by Homaxz** [comment]
This is great. Thanks a lot! :)
