### ISSUE TITLE
Lua error when hovering over currency

### ISSUE THREAD

**Issue by Nevcairiel** [Xruptor/BagSync#50]
Hey,

i get this error when hovering over a currency entry on the characters currency screen after updating to 10.2
```
2x BagSync\BagSync-v10.2.lua:903: attempt to index field '?' (a nil value)
BagSync\BagSync-v10.2.lua:903: in function `AddCurrencyTooltip'
BagSync\BagSync-v10.2.lua:1256: in function <BagSync\BagSync.lua:1252>
[C]: in function `SetCurrencyToken'
[string "*:OnEnter"]:2: in function <[string "*:OnEnter"]:1>
```

**Comment by Xruptor** [comment]
Odd, let me take a look.

**Comment by Xruptor** [comment]
Okay I see what it is :)  You don't have CrossRealms or Battle.Net characters enabled.  So it's defaulting to the current realm.  When it's parsed it returns nil for the realm; which gives that nil error for indexing.  I'll fix it in a quick patch.

**Comment by Xruptor** [comment]
Alright fixed it.  Thanks for the find!
