### ISSUE TITLE
Tradeskill Window Tooltips show BagSync text below the tooltip

### ISSUE THREAD

**Issue by Nevcairiel** [Xruptor/BagSync#51]
Hi,

In the Tradeskill Window, the tooltips on reagents show the BagSync information below the tooltip, making it only barely readable.

See here:
http://i.imgur.com/LKULpXd.jpg

**Comment by Xruptor** [comment]
Nev I can't seem to replicate this error.  It works fine on my end.  Do you have any other addons installed?  Try disabling them all and only load BagSync.  Tell me if it still does it.  I even tried disabling the empty line separator thinking that was the cause.  From the looks of your issue it seems like a tooltip fresh issue where it doesn't update to expand to the new added lines.

**Comment by Xruptor** [comment]
Okay please do me a favor.  Do the test I mentioned above and let me know if BagSync is still causing the issue.  After you do the test use this version of BagSync I will attach here.  If this fixes the issue then let me know that also.  I want to rule out any other addons that may be causing this.  Hopefully my attached version will fix the issue if it's still happening for you on the original test.

[BagSync.zip](https://github.com/Xruptor/BagSync/files/485147/BagSync.zip)

**Comment by Homaxz** [comment]
I had the same issue with currencies. It would look the same as in OP's screenshot. (No other addons, except BagSync enabled.) 

Your latest commit (https://github.com/Xruptor/BagSync/files/485147/BagSync.zip) fixed this issue for me.

**Comment by Nevcairiel** [comment]
Seems to work with the zip you linked, going back to the latest release and its immediately broken again.

**Comment by Xruptor** [comment]
Okay cool I'll push the changes then.  It was a refresh issue.  It looks like Blizzard doesn't like to re-display the tooltip more than once.  Which is stupid... BUT whatever I can compensate for this problem.  I'll release it now to the public.  Thanks to both of you for helping out.  Will give you both credits in the patch notes :)
