### ISSUE TITLE
[Suggestion] option to remove Cross-Realm and BNet identifiers

### ISSUE THREAD

**Issue by Homaxz** [Xruptor/BagSync#52]
I think it looks nicer without these prefixes: "XR-; BNet", and since you can color BNet/ XR independently, I don't need to have them enabled. Example: http://i.imgur.com/67PTYBk.jpg

**Comment by Xruptor** [comment]
Hmmm seems simple enough.  I'll see if I can add it for next version push.

**Comment by Xruptor** [comment]
Added this into next release v10.5.
