### ISSUE TITLE
[Feature Request] Options to disable

### ISSUE THREAD

**Issue by Stanzilla** [Xruptor/BagSync#55]
* tooltip line on grey/trash items
* the "loaded" print on logon

**Comment by Xruptor** [comment]
Can you give me an example why you would want to filter out the grey/trash items?  I mean you are going to junk them anyways.  There are some junk/trash items that are used for quests throughout the game.  Regardless, if you can give me a good reason for the option, I would be more than happy to implement it.  Right now, I'm just not seeing the necessity.

Shouldn't be too difficult to put an option to remove the printout from login.  I'll see if I can put it in the next push.

**Comment by Stanzilla** [comment]
Well I guess it just was not useful to me, but I can see the argument that it's more work/effort for something that does not matter anyway, so I'm stepping back on that .)

**Comment by Xruptor** [comment]
Okay :)  I was just asking as I really didn't see a real need for the feature to be implemented.  I'll go ahead and add an option to disable the login loading prompt though.

**Comment by Xruptor** [comment]
Okay I implemented it.  It will be available in the next version push.

Commit: https://github.com/Xruptor/BagSync/commit/c70c631b916919b3aa5c3e032026e31237c11f23
