### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Homaxz** [Xruptor/BagSync#56]
Getting this error after update 10.6, addon no longer works for me.

`Message: Interface\AddOns\BagSync\BagSync.lua:1079: bad argument #1 to 'sort' (table expected, got nil)
Time: 10/26/16 16:33:40
Count: 6
Stack: [C]: in function `sort'
Interface\AddOns\BagSync\BagSync.lua:1079: in function `AddItemToTooltip'
Interface\AddOns\BagSync\BagSync.lua:1180: in function <Interface\AddOns\BagSync\BagSync.lua:1174>
[C]: ?
[C]: ?
[C]: in function `SetBagItem'
Interface\FrameXML\ContainerFrame.lua:1149: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: (*temporary) = nil
(*temporary) = <function> defined @Interface\AddOns\BagSync\BagSync.lua:1079
(*temporary) = "table expected, got nil"
`

**Comment by Xruptor** [comment]
Logon to one character of each of the servers you have characters on.  It will fix that error.  I'll add error checks for this in an upcoming update.

**Comment by Xruptor** [comment]
Version 10.7 which I just pushed should address the NIL issue.  That only occurs if you haven't logged in to other characters on other servers yet.
