### ISSUE TITLE
Feature Request: Show guild bank gold

### ISSUE THREAD

**Issue by malaire** [Xruptor/BagSync#60]
It would be nice to show guild bank gold for private guilds where gold is all mine.

It would be nice to also have option to select which guild banks are included and which excluded.

**Comment by Xruptor** [comment]
Do you mean to show the total amount of gold a guild has in the gold tooltip?

**Comment by malaire** [comment]
I meant that when I open the list of gold on characters with "/bgs gold", I'd like that list to also include any gold I have in private guilds, in addition to characters.

For that to work there would also need to be a feature where I can select which guilds I want to include in the list.

**Comment by Xruptor** [comment]
I've added this on the complete rewrite.  I'm almost done and it should be available soon.
