### ISSUE TITLE
Current character checkmark is also shown on XR and BNet characters with same name

### ISSUE THREAD

**Issue by malaire** [Xruptor/BagSync#61]
If I have other characters with exactly same name as current character (either XR or BNet), then current-character-checkmark is also shown for those characters.

This should be easy to fix - just don't show that checkmark for any XR or BNet character.

**Comment by Xruptor** [comment]
I don't understand.  Do you mean you have multiple characters with the same name and that the checkmark is showing for all of them and is incorrect or just one of them?  Or do you mean that I should not displaying multiple characters with same name?

**Comment by malaire** [comment]
I have multiple characters with same name and checkmark is showing for all of them and not just the one I'm logged in with as it should.

**Comment by Xruptor** [comment]
OH I see what you mean.  I'll take a look at this.  I'll just have to make it only show for the current logged in character based on server.  It might be missing the server name check.

**Comment by Xruptor** [comment]
Yeah it was a mistake.  It wasn't taking realm into account.  I have fixed this in the next push.
