### ISSUE TITLE
Feature Request: Indicator for characters not in same faction

### ISSUE THREAD

**Issue by malaire** [Xruptor/BagSync#62]
It would be nice to have optional indicator for all characters which are not in the same faction as current character.

Perhaps just word 'Alliance'/'Horde' shown after character name, before possible XR/BNet indicator.

Other idea would be to color character name according to faction (but this only works if class colors are not used).

**Comment by Xruptor** [comment]
This is not a bad idea actually.  I'll see if I can implement this.

**Comment by Xruptor** [comment]
I have implemented this and will be available in next release push.
