### ISSUE TITLE
Right click for menu not working

### ISSUE THREAD

**Issue by Tamillerkt** [Xruptor/BagSync#64]
Hello, as of patch 7.3, right-clicking the minimap icon no longer brings up the menu.  Thanks for making a great add-on, bagsync is my fave!!

**Comment by Merathilis** [comment]
Open: Interface\AddOns\BagSync\modules\minimap.lua

Change line 41 to:

```lua
PlaySound(SOUNDKIT.GS_TITLE_OPTION_EXIT or 799)
```

**Comment by Xruptor** [comment]
This has been fixed :)  I'm slowly updating all my addons.
