### ISSUE TITLE
Russian language support or me doing somthing wrong 

### ISSUE THREAD

**Issue by acname** [Xruptor/BagSync#66]
Hi 
nice addon 
me from Russian realms 
![wowscrnshot_101117_035623](https://user-images.githubusercontent.com/32693429/31420406-2df22396-ae39-11e7-9af4-9ade0157695a.jpg)

**Comment by Gizmi** [comment]
https://eu.battle.net/forums/ru/wow/topic/5208432674?page=1

**Comment by Xruptor** [comment]
I don't understand what is being asked here :)  So I'll close the comment.

**Comment by Xruptor** [comment]
I see what the issue is and have fixed it for the Russian clients.
