### ISSUE TITLE
Lua Error search module

### ISSUE THREAD

**Issue by Gizmi** [Xruptor/BagSync#68]
7x ...libs\LibItemSearchGrid-1.0\LibItemSearchGrid-1.0-2.lua:521: attempt to call global 'GetNumEquipmentSets' (a nil value)
...libs\LibItemSearchGrid-1.0\LibItemSearchGrid-1.0-2.lua:521: in function <...libs\LibItemSearchGrid-1.0\LibItemSearchGrid-1.0.lua:520>
...libs\LibItemSearchGrid-1.0\LibItemSearchGrid-1.0-2.lua:565: in function `findItem'
...libs\LibItemSearchGrid-1.0\LibItemSearchGrid-1.0-2.lua:196: in function `UseTypedSearch'
...libs\LibItemSearchGrid-1.0\LibItemSearchGrid-1.0-2.lua:183: in function <...libs\LibItemSearchGrid-1.0\LibItemSearchGrid-1.0.lua:149>
(tail call): ?
...libs\LibItemSearchGrid-1.0\LibItemSearchGrid-1.0-2.lua:102: in function `FindIntersectSearch'
...libs\LibItemSearchGrid-1.0\LibItemSearchGrid-1.0-2.lua:91: in function <...libs\LibItemSearchGrid-1.0\LibItemSearchGrid-1.0.lua:88>
(tail call): ?
BagSync\modules\search-Поиск.lua:189: in function `DoSearch'
BagSync\modules\search-Поиск.lua:30: in function <BagSync\modules\search.lua:28>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
BagSync\libs\AceGUI-3.0\AceGUI-3.0-36.lua:314: in function `Fire'
...ync\libs\AceGUI-3.0-36\widgets\AceGUIWidget-EditBox.lua:74: in function <...ync\libs\AceGUI-3.0\widgets\AceGUIWidget-EditBox.lua:71>
...ync\libs\AceGUI-3.0-36\widgets\AceGUIWidget-EditBox.lua:118: in function <...ync\libs\AceGUI-3.0\widgets\AceGUIWidget-EditBox.lua:115>

Locals:
nil

**Comment by Gizmi** [comment]
I have corrected everything
http://www.wowinterface.com/downloads/fileinfo.php?id=24728#changelog

**Comment by Xruptor** [comment]
I'm currently fixing all my addons.  I'm addressing bugs as I can and should have things updated soon for 8.0 and Battle for Azeroth.  Gizmi you could have pushed the changes to the repository silly and I would have merged it.
