### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Meivyn** [Xruptor/BagSync#69]
I just saw your message in ``frFR.lua`` about the translation.
I propose to complete it, if you need. I really like your addon and I'm using it everyday. Will maybe need some of your help to find the context, though.

**Comment by Xruptor** [comment]
I really apologize for the delay.  I've been working on a complete rewrite and it's been taking up my time.  I would LOVE assistance with the french translation.  It's really quite simple.  All you need to do is translate every line found in the enUS.lua file under the locale folder.  Then attach it here or copy and paste.  You can even use pastebin.com as well!  I'll make sure it gets put into the french localization file.  Thanks!!!

**Comment by Meivyn** [comment]
No worries, I was also pretty busy.

I'll start translating using VSCode to retrieve the context of your strings in addon files easier. I'll let you know if I need some precisions, and when it'll be ready.

**Comment by Xruptor** [comment]
I've been working on a complete rewrite and the original enUS is a bit outdated. So please use the following. It's from my Testing branch.

[](https://github.com/Xruptor/BagSync/blob/Testing/locale/enUS.lua)

**Comment by Xruptor** [comment]
Heyas!  If you are still willing to update the French Localization.  Please take a look at this file :)

https://github.com/Xruptor/BagSync/blob/Testing/locale/enUS.lua

**Comment by Meivyn** [comment]
Hey, sorry for this long wait I completely forgot.
I'll get into it when I'll get some free time, but since a new patch released, I can't tell you an ETA. I'll do my best to do it whenever I'll get free time.

**Comment by Xruptor** [comment]
> Hey, sorry for this long wait I completely forgot.
> I'll get into it when I'll get some free time, but since a new patch released, I can't tell you an ETA. I'll do my best to do it whenever I'll get free time.

No problem.  Testing has been moved to Master branch and has been released to the public.   So you can use the following file instead now.

https://github.com/Xruptor/BagSync/blob/master/locale/frFR.lua

**Comment by Xruptor** [comment]
lol Whoops I meant this file.
https://github.com/Xruptor/BagSync/blob/master/locale/enUS.lua
