### ISSUE TITLE
Bfa update?

### ISSUE THREAD

**Issue by Addonman** [Xruptor/BagSync#70]
Was this addon updated for bfa?I can only tellt hat gold module is working ,but profession and currency module arent.I am doing something wrong or this was updated?

**Comment by Xruptor** [comment]
This addon was updated for BfA on wow and curse.  I'm doing a complete rewrite and I'm still working on it.  Which is why it's listed under the 'Testing' category.  Use the regular Main branch download and releases or the ones from wowinterface and curse. :)

**Comment by Xruptor** [comment]
Can you please post the error you are getting here.  I'm unsure as to what exactly is going wrong then.  It's possible my rewrite will fix the issue.  But I had updated the TOC and such on WOWInterface and Curse.  That is why I'm confused.  Is it simply just not loading for you?  Please provide some more information and I should be able to see if I can fix the problem.

**Comment by Addonman** [comment]
I dont errors that i can post because i doesnt throw errors .In proffession window  i can see char have certain number of recipes but when i click on profession nothing happens most of times. When i do see some recipes its like from vanilla or expansion after and i know that char have  recipes from BFA.On currrency modul i can see list of currencies but i cant see how many of that currencis i do have.

**Comment by Xruptor** [comment]
The professions issue was a bug because they changed the way how professions work with BfA.  This feature now works in my rewrite and will be available soon.

**Comment by Addonman** [comment]
"my rewrite and will be available soon".Whats your time frame of soon?

**Comment by Xruptor** [comment]
Please refer to this ticket
https://github.com/Xruptor/BagSync/issues/74
