### ISSUE TITLE
Please come back!

### ISSUE THREAD

**Issue by fnordson** [Xruptor/BagSync#74]
I love this minimalistic add-on.  
Everything else with the feature is overblown with crap I don't need...
Now with Classic out, the situation got even worse. 

Please @Xruptor return!

**Comment by LudiusMaximus** [comment]
I second this!!

@Xruptor, what made you abandon the new work you already started on the Testing branch before even making a new release?

**Comment by Xruptor** [comment]
Thanks! Im glad you enjoy the addon. I was working on a complete revamp
before i took a break. Lots of stuff real life issues happening that
include medical situations. I do plan on returning sometime, but not sure
when. Ill look to see if there is a way I can update it without having
subscription.

**Comment by Xruptor** [comment]
@LudiusMaximus

Basically family illness and continued caregiving care has prevented me
from actively supporting my addons. Im hoping at some point in the near
future to return to it.

**Comment by LudiusMaximus** [comment]
Hey thanks for being in touch with you fan base. :-)
That's completely understandable. Family and health always go first and social interactions are more important than spending time in front of the computer.

Take your time until things may have settled!
If you can single out some TODOs for the Testing branch and note them down as github issues, maybe I could try to have a look at it some time and send you a pull request.

But I also could not promise anything, as my work and family life is also very taxing at the moment. :-)

**Comment by Xruptor** [comment]
@LudiusMaximus if i remember correctly one of the primary things that was preventing me from releasing the add-on at the time was a taint issue that was driving me nuts. I couldn't for the life of me figure out what was causing it. Another addon, Ace, a module? Who knows. Taint errors are so generic in wow its hard to track down sometimes. The hilarious part is my addon barely touches anything that could be tainted. Which is why it was so frustrating.

**Comment by LudiusMaximus** [comment]
@Xruptor OK, how exactly could I reproduce this?

**Comment by Blazeflack** [comment]
@Xruptor I am a big fan of BagSync as well. I always had it enabled when I played WoW some years ago. With Classic out I have returned as an active player and would love to get this addon up to speed.

I am no stranger to addon development, so when you have the time it would be lovely if you could provide a list of outstanding issues as you recall them, and preferably steps to reproduce the issue if you have them. I will help out with pull requests as well.

**Comment by Xruptor** [comment]
I have a lot going on. I just had a loved one pass away and I'm in the process of getting my feet back up again. It's currently a turbulent time for me and I can't promise I will have time to update BagSync for classic, let alone for live. I do plan on returning at some point in time possibly in the next couple of months or after Vision of N'zoth is released. I haven't decided yet. I had completely rewritten BagSync at one point and was struggling with a taint issue that I couldn't resolve. Blizzard makes finding taint issues extremely difficult. I had gotten frustrated and just abandoned WOW altogether. I do want to release it and maybe I will at one point. Like I said I can't promise anything.

That being said I'm currently updating the Testing Branch of BagSync to see if I can get it working on latest WOW.  It will take some time.

**Comment by Xruptor** [comment]
Updated and pushed the reworked and redesigned BagSync.  Hopefully it has no taint issues.  It's version 12.0

https://github.com/Xruptor/BagSync/commit/7cabd323e8065708f6f28bdc441f465c6cc6f525
