### ISSUE TITLE
Can't pick up character data

### ISSUE THREAD

**Issue by DaniTakacs** [Xruptor/BagSync#78]
As of 8.3 the addon can't pick up data from any of my characters. It is still working and I can still search items/gold/etc but it doesn't show any of my characters' data.

**Comment by Westwoodo** [comment]
Mine refuses to load so I can't search.

**Comment by Xruptor** [comment]
I'm current investigating this issue with BagSync.  Since there are multiple issues reported for the same thing.  I'm going to close this one, but please refer to the following issue # instead.

https://github.com/Xruptor/BagSync/issues/80
