### ISSUE TITLE
Lua errors in 8.3

### ISSUE THREAD

**Issue by cremor** [Xruptor/BagSync#79]
Since 8.3 an error is thrown on login/reload because the event AUCTION_OWNED_LIST_UPDATE doesn't exist any more.

And if you open the auction house another error is thrown because the method GetNumAuctionItems doesn't exist any more. I assume there are some more auction house related new errors since everything changed there.

**Comment by NoNick96** [comment]
The 8.3 broke the addon completely. The lua error that's poping up on login:

```
14x ...ceBagSync\libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "AUCTION_OWNED_LIST_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@BagSync\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@BagSync\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:142: in function `RegisterEvent'
[string "@BagSync\BagSync-11.1.lua"]:1538: in function <BagSync\BagSync.lua:1432>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@ACU\Libs\AceAddon-3.0\AceAddon-3.0-12.lua"]:558: in function `EnableAddon'
[string "@ACU\Libs\AceAddon-3.0\AceAddon-3.0-12.lua"]:651: in function <ACU\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:457: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:504: in function `CombatLog_LoadUI'
[string "@FrameXML\UIParent.lua"]:1259: in function <FrameXML\UIParent.lua:1155>
```

**Comment by Xruptor** [comment]
I'm currently reviewing this bug.  Apparently with the Auction House revamp they broke a lot of addons.

**Comment by arderie** [comment]
Replacing `AUCTION_OWNED_LIST_UPDATE` with `OWNED_AUCTIONS_UPDATED` on lines 1459 and 1676 in BagSync.lua should resolve this.

**Comment by Xruptor** [comment]
Updated in version 12.0.
https://github.com/Xruptor/BagSync/commit/7cabd323e8065708f6f28bdc441f465c6cc6f525
