### ISSUE TITLE
Doesn't work at all for me in 8.3

### ISSUE THREAD

**Issue by Westwoodo** [Xruptor/BagSync#80]
Addon is installed and updated but doesn't work, my icon has disappeared and /bgs or /bagsync doesn't work.

**Comment by Xruptor** [comment]
I'm currently investigating this issue.  There are multiple bugs reported for the same thing.  Please refer to this issue # https://github.com/Xruptor/BagSync/issues/79 for the bug report. 

Issue: https://github.com/Xruptor/BagSync/issues/79
