### ISSUE TITLE
Equipped bags are counted as "in bag"

### ISSUE THREAD

**Issue by cremor** [Xruptor/BagSync#81]
Either version 12.1 of the addon or WoW patch 8.3 caused a minor annoyance:

Bags that are currently equipped are counted as "in bag". Previously equipped bags were ignored and only items that are actually **in** a bag were counted.

Update: It even counts bags that are slotted in the bank as "in bank".

**Comment by Xruptor** [comment]
I'll have to double check this.  Blizzard may have changed the API to count the bag itself during iteration using the functions they provide.

**Comment by Xruptor** [comment]
You are right, it looks like bags are being counted twice.  I'll see what I can do to fix this.

**Comment by Xruptor** [comment]
Fixed in the commit listed above.  Will be pushed in the next release version.
