### ISSUE TITLE
Suggestion: Add Config option to disable displaying Guild Gold in Gold Window

### ISSUE THREAD

**Issue by Sinaloit** [Xruptor/BagSync#82]
Currently the Gold window displays the Guild Gold as well.
While there is an option for "Display guild bank items" there is not one to disable only the gold display.  While I am interested in what items may be in the guild bank I do not want to count the guilds money as my own.

**Comment by Xruptor** [comment]
It shouldn't display the guild gold.  It should only list character names and how much gold they have.  I'll double check the code just to make sure.  If anything I'll make it an option so it can be disabled.

**Comment by Xruptor** [comment]
Added it in patch for next major release of BagSync.  Please see commit: https://github.com/Xruptor/BagSync/commit/765b6980b9291e71283c8418678d00d33bd22e31
