### ISSUE TITLE
Minimap icon

### ISSUE THREAD

**Issue by sthdevilish** [Xruptor/BagSync#84]
Minimap icon looks the same as BugSuck addon (where it's either green or red), blue would propably look the same as other popular addon (BankItems). I suggest making or choosing a one that looks more distinguishable. Also, I cannot move the button across the minimap frame, and it doesn't seem to work with MBB addon sadly. Hope you can fix it soon and make those small QoL improvements. Thanks in advance!

**Comment by Xruptor** [comment]
I've been using the same Minimap Icon for years and years.  It's possible people started using that icon and it spread around.  I don't have much background in graphics editing but I can see if I can edit it.  I kinda like it being the green sack though.

The Minimap Icon should be able to be rotated around the minimap.  That or at least moved away from the minimap.  If it's not doing this then it's a bug.  Can you provide a screenshot for me of how or what your minimap looks like?

Also I'm unfamiliar with this MBB addon?

**Comment by Xruptor** [comment]
Out of curiosity, please hold shift on your keyboard and then try dragging the icon.  If you can move it then I need to put a note there for that.

**Comment by Xruptor** [comment]
Updated the minimap icon to be a bit easier to move.  Will be available in next major update.

Please see commit:  https://github.com/Xruptor/BagSync/commit/8e3b64deda2f7c1fb7d02f8e5419149c9f9b5987

**Comment by sthdevilish** [comment]
Thanks, looking forward to it! Ingore that MBB case, I forgot how it works, sorry to trouble you. If you're not familiar with it though, I suggest you try it out, it makes the minimap much more clean with lots of addons installed.
