### ISSUE TITLE
Bagsync don't work after patch 8,3

### ISSUE THREAD

**Issue by hildekv** [Xruptor/BagSync#87]
Hi, my bagsync have worked on and of since the new patch, now it's not working again. And the /bgs fixdb does not work either. So how am i going to see what i have on all my chars, I have 23 chars over 3 realms, so i'm addicted to bagsync

**Comment by Xruptor** [comment]
I've updated to version 12.4.  Use the following issue (https://github.com/Xruptor/BagSync/issues/88) to let me know if that has corrected your problem.
