### ISSUE TITLE
Errors with latest Version : 12.3

### ISSUE THREAD

**Issue by Epidemdabear** [Xruptor/BagSync#88]
Getting following errors using latest version 

5x BagSync\wireframe\tooltip.lua:11: Cannot find a library instance of "LibQTip-1.0".
[string "=[C]"]: in function `error'
[string "@AdvancedTooltips\libs\LibStub\LibStub.lua"]:38: in function `LibStub'
[string "@BagSync\wireframe\tooltip.lua"]:11: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibQTip-1.0"."

15x BagSync\libs\LibQTip-1.0\LibQTip-1.0-46.lua:175: unexpected symbol near ']'

**Comment by Xruptor** [comment]
I have updated to version 12.4.  Please let me know if that has resolved the issue with LibQTip.

**Comment by Sinaloit** [comment]
This has resolved the issue for me.

**Comment by Epidemdabear** [comment]
All working now thanks

**Comment by Merathilis** [comment]
Yea, all good now. I fixed it anyways on my local folder :>
