### ISSUE TITLE
Latest Git (12.4)

### ISSUE THREAD

**Issue by vandiel01** [Xruptor/BagSync#89]
Opening Gbank will lock up WoW

**Comment by Xruptor** [comment]
Are you sure it's just not locking up for a few seconds and then resuming to normal?  It has to scan a lot of items.

**Comment by vandiel01** [comment]
nope total lock up, had to ALT F4 outta of it

**Comment by vandiel01** [comment]
i reverted back to 12.1, locked up again, deleted BagSync.lua and all is well.. haven't went back to 12.4 yet to test with blank slate (yes i have backup copy of BagSync.lua elsewhere)

**Comment by Xruptor** [comment]
I think I know what it is.  It has to do with how the server responds with the guild data.  Give me a sec and I'll fix it.  Are you having issues with the LibQTip btw?  No errors with that right that popup?

**Comment by vandiel01** [comment]
in 12.1 no issue, lemme check with 12.4 (im more than happy to help test, etc as I do with ATT, etc)  Vandiel#2276 is my discord

**Comment by Xruptor** [comment]
Thank you!  Makes this easier!

**Comment by Xruptor** [comment]
This has been resolved with version 12.5.  Game shouldn't lock up now.  Will see if there is a way to lessen the initial guild bank pause.
