### ISSUE TITLE
Please add better Mail tracking.

### ISSUE THREAD

**Issue by Deavan** [Xruptor/BagSync#9]
When you send items through in game mail to a character that BagSync already knows about, it should keep track of the items and list it as in Mail in tooltips and such.

**Comment by Xruptor** [comment]
After thinking about this awhile.  I feel that this would cause more problems then solve.  Especially if the receiving end doesn't actually open their mail or delete their item in the mail.  Would cause item count discrepancies.  When I have more time I'll ponder on a better way to handle the mail system.  For now it's okay as it is.  Thanks for the suggestion though.
