### ISSUE TITLE
dont work (all adoon last version)

### ISSUE THREAD

**Issue by FomaDima** [Xruptor/BagSync#90]
bags elvui 

Message: Interface\AddOns\BagSync\wireframe\data.lua:155: attempt to index global 'BagSyncDB' (a nil value)
Time: Fri Jan 24 10:33:11 2020
Count: 1
Stack: Interface\AddOns\BagSync\wireframe\data.lua:155: attempt to index global 'BagSyncDB' (a nil value)
[string "@Interface\AddOns\BagSync\wireframe\data.lua"]:155: in function `CleanDB'
[string "@Interface\AddOns\BagSync\wireframe\data.lua"]:50: in function <Interface\AddOns\BagSync\wireframe\data.lua:42>
[string "=[C]"]: ?
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:620: in function <...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:605>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:457: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:580: in function `TimeManager_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1257: in function <Interface\FrameXML\UIParent.lua:1155>

Locals: <none>

**Comment by FomaDima** [comment]
Message: Interface\AddOns\BagSync\wireframe\tooltip.lua:252: attempt to index field 'options' (a nil value)
Time: Fri Jan 24 10:35:21 2020
Count: 24
Stack: Interface\AddOns\BagSync\wireframe\tooltip.lua:252: attempt to index field 'options' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\BagSync\wireframe\tooltip.lua"]:252: in function `TallyUnits'
[string "@Interface\AddOns\BagSync\wireframe\tooltip.lua"]:492: in function <Interface\AddOns\BagSync\wireframe\tooltip.lua:488>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1413: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>
[string "=[C]"]: ?

Locals:

**Comment by FomaDima** [comment]
any cursor mouse item error 

Message: Interface\AddOns\BagSync\wireframe\tooltip.lua:252: attempt to index field 'options' (a nil value)
Time: Fri Jan 24 10:35:58 2020
Count: 92
Stack: Interface\AddOns\BagSync\wireframe\tooltip.lua:252: attempt to index field 'options' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\BagSync\wireframe\tooltip.lua"]:252: in function `TallyUnits'
[string "@Interface\AddOns\BagSync\wireframe\tooltip.lua"]:492: in function <Interface\AddOns\BagSync\wireframe\tooltip.lua:488>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1413: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>
[string "=[C]"]: ?

Locals:

**Comment by Xruptor** [comment]
Fixed in latest commit. (https://github.com/Xruptor/BagSync/commit/9743d447c1d1c313b06c745d1ed3bc058518df3f)

Will be pushed with next release.
