### ISSUE TITLE
issue with latest update

### ISSUE THREAD

**Issue by dilvishdamned** [Xruptor/BagSync#91]
With latest update having MASSIVE lag upon mouse over of items, causing Ace & many other addons to lua error & time out.  Disabling bangsync & issues go away.

Message: [string "safecall Dispatcher[1]"]:14: script ran too long
Time: Fri Jan 24 01:41:35 2020
Count: 1
Stack: [string "safecall Dispatcher[1]"]:14: script ran too long
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:14: in function `?'
[string "@Interface\AddOns\AskMrRobot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:90: in function `Fire'
[string "@Interface\AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:

**Comment by Xruptor** [comment]
Can you please send me your SavedVariables for BagSync.lua?  You can find it under C:\WOW\_retail\WTF\YOUR ACCOUNT\SavedVariables\BagSync.lua.  

Please use WOWInterface or Wow.curse.com  to send me the message.  My username is Xruptor.

**Comment by Xruptor** [comment]
You can use https://gist.github.com/ if you want and create a SECRET gist and send me that.  Just copy and paste the bagsync stuff in there, or you can send me the file using a file hosting website.

**Comment by Xruptor** [comment]
I've just uploaded version 12.7.  Please see if that fixes the issue for you.
