### ISSUE TITLE
Guild bank items displayed when disabled

### ISSUE THREAD

**Issue by Timetoregen** [Xruptor/BagSync#92]
I normally choose not to have any of the guild items displayed or enabled for tooltips. I noticed after updating today that the guild bank counts are appearing in item tooltips even with "Display guild bank items" disabled in the Config menu.

**Comment by Xruptor** [comment]
I'll take a look and see what's going on.  It may have been something I overlooked when I did the complete rewrite of BagSync.

**Comment by Xruptor** [comment]
This issue has been fixed in the above commit  (https://github.com/Xruptor/BagSync/commit/c8428ed7130d09ec1caf474ad82bf48f97ac2081).  It will be available in next major version push of BagSync.
