### ISSUE TITLE
GBank Enhancement

### ISSUE THREAD

**Issue by vandiel01** [Xruptor/BagSync#95]
I'm always quick to check gbank and leave.  Message would tell me "Warning, not done".. Maybe it'd help to have those % or wording "Done" to see what to see which tab has been scanned.. something like the image below (not exact but something like it)

![image](https://user-images.githubusercontent.com/52209920/73379203-7938b880-4287-11ea-8053-8f65d6ffc325.png)

**Comment by Xruptor** [comment]
This sounds like a great idea.  Problem is the a lot of people use custom UI's.  So it would be difficult for me to place them appropriately without them using the built in blizzard frame.  That being said, it could possibly be done another way?  Maybe a window or possibly a notification in chat?

**Comment by Xruptor** [comment]
Hmm so I think what I will do is probably a tooltip that appears at center of the screen when scanning initiates.  I could probably use this same tooltip for the auction scanning.  If anything I can put an option to disable it.  I'll play around and see how it comes out.

**Comment by Xruptor** [comment]
Added it as a tooltip notification at center of screen to bypass issues with custom UI's.  It will be available in next major push update.  Commit: (https://github.com/Xruptor/BagSync/commit/ccdb9435e2e4f970b960d5b5aa95345295b3d21e)
