### ISSUE TITLE
Currency Key bind is not working

### ISSUE THREAD

**Issue by Gnovas** [Xruptor/BagSync#96]
It says is bind to my "Alt-B" which I selected but when I do that, nothing happens, and I suppose it should open the cBagsync currency tab

**Comment by Xruptor** [comment]
Yep this is a bug.  It was not carried over with the rewrite.  I took a year off so I was bound to miss a few things.  Thanks for pointing it out!

**Comment by Xruptor** [comment]
Fixed in latest version.

**Comment by Gnovas** [comment]
Yeah the main function of the addon is working excellent, cheers for that, AH items are now working correclty, this is just a minor function i found it wasnt working, thanks anyway!
