### ISSUE TITLE
single-digit FPS collecting mail with TSM4 with recent versions of BagSync

### ISSUE THREAD

**Issue by tordenflesk** [Xruptor/BagSync#97]
Also a tooltip of the items being collected gets flashed along the bottom edge of the screen.

downgrading to for example v12.1 works fine.

**Comment by anotherone20** [comment]
hi! I'm having the same issue but I wasn't sure it was bagsync fault to post here, happy i'm not alone. I've been trying disabling/combinations of addons and it might be it interact with TSM mail module, what about you @tordenflesk ?

**Comment by Xruptor** [comment]
Are you both dealing with a large amount of battle pets in your mailboxes?

**Comment by tordenflesk** [comment]
No, 2-3 at most.

**Comment by Xruptor** [comment]
okay let me check it out, I should have a test version for you soon.  It probably has to do with the battlet pet checks in the mailbox.

**Comment by Xruptor** [comment]
Try this test build.
https://github.com/Xruptor/BagSync/archive/master.zip

NOTE: You have to rename the folder from BagSync-master to BagSync then replace whatever you have in your addons folder. Located at:
C:\WOW FOLDER\ _retail\Interface\Addons\

**Comment by tordenflesk** [comment]
I jsut cancelled and re-posted ~400 auctions and no (significant) slowdown when collecting mail.

**Comment by Xruptor** [comment]
> I just cancelled and re-posted ~400 auctions and no (significant) slowdown when collecting mail.

Okay so I take it that it worked fine then?  Was the slowdown still an annoyance however small or is it passable?  If not then I'll post this update.  Just let me know, to get a green light as I cannot reproduce this issue.

**Comment by tordenflesk** [comment]
Oh, I've always had a slight decrease in frame-rate when collecting mail.
To be expected with the amount of addons I have,  several of which are scanning collected items (TSM4, BagSync etc.). 
I've only tested it this once, so not sure if it'll show up again.

**Comment by Xruptor** [comment]
Okay good, but you aren't hitting those single digit FPS like you were earlier right?  It's passable now?

**Comment by anotherone20** [comment]
I will try now too brb :)

**Comment by anotherone20** [comment]
it looks like it is very smooth now!

**Comment by Xruptor** [comment]
Okay great.  I'll package up the fixes in the next major push release.  Thank both of you for your help!

https://github.com/Xruptor/BagSync/commit/6943e1ad1fa2eeddad309c5c7d14be605d9de435
