### ISSUE TITLE
Icons on currency tab

### ISSUE THREAD

**Issue by Gnovas** [Xruptor/BagSync#98]
This is a suggest, and I believe this will mprove that option 100% will be faster to find things, or mabye changing the name for the icon would work also imo

And also set the same order than retail currency tab, BFA. Dungeons, Miscellaneus, and then expansion release order

**Comment by Xruptor** [comment]
You mean on the BagSync Currency window?

**Comment by Gnovas** [comment]
Yeah to copy Retail Currency Order + Icons to BagSncs Currency Window

**Comment by Xruptor** [comment]
> Yeah to copy Retail Currency Order + Icons to BagSncs Currency Window

Should be easy enough.  Just need to enable it.  Let me look at the code.
