### ISSUE TITLE
Bagsync not working with ElvUI

### ISSUE THREAD

**Issue by martinboy1974** [Xruptor/BagSync#99]
Bagsync no longer Works with ElvUI. I can search, but tooltip no longer shows charactername or item Count for selected item.

ElvUI 11.33
Bagsync 13.0

**Comment by Xruptor** [comment]
Have you tried disabling ElvUI and see if that works?  Then re-enable ElvUI and see if that causes a conflict.  I'm not entirely surprised as a lot of these UI Mods overwrite a lot of the standard blizzard stuff.  This includes hijacking the tooltip.

Has this issue happen to you recently with recent updates or with BagSync revamp in general?  Did you just start using BagSync?  Please provide a bit more details so I can look into it.

**Comment by martinboy1974** [comment]
Seems it wasnt ElvUI but ElvUI_ExtraDataText that caused the problem. Disabling ExtraDataText while leaving ElvUI enabled didnt cause any conflicts with Bagsync after all.

**Comment by Xruptor** [comment]
> ElvUI_ExtraDataText

Thank you for investigating this and determining what was causing the issue.  If you still want to use ElvUI_ExtraDataText, then you can try the new external tooltip option that comes with BagSync.  You can enable it under the "Main" section of BagSync Config.
